### ISSUE TITLE
cannot import word2vec_sample

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#1001]
The gensim example has an import problem on the CI server:

```
File "/scratch/jenkins/workspace/nltk/TOXENV/py26-jenkins/jdk/jdk8latestOnlineInstall/nltk/test/gensim.doctest", line 42, in gensim.doctest
Failed example:
    from nltk.corpus import word2vec_sample
Exception raised:
    Traceback (most recent call last):
      File "/scratch/jenkins/python/python-2.6.9-x86_64/lib/python2.6/doctest.py", line 1253, in __run
        compileflags, 1) in test.globs
      File "<doctest gensim.doctest[7]>", line 1, in <module>
        from nltk.corpus import word2vec_sample
    ImportError: cannot import name word2vec_sample
```

**Comment by longdt219** [comment]
Hi @stevenbird, 
Could you close this issue ?
