### ISSUE TITLE
import nltk causes UnicodeDecodeError when user path contains cyrillic symbols.

### ISSUE THREAD

**Issue by yanykin** [nltk/nltk#1024]
I have Windows 8.1 x64 with Python 2.7 x86 installed in the system.
Unfortunately, path of my user folder contains cyrillic symbols (`C:\Users\Кирилл`) and it makes some inconveniences with using NLTK library.

I have faced with problem trying to import some packages:

``` python
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-1-bd6d8e29525a> in <module>()
----> 1 from nltk.tokenize import word_tokenize

C:\Python27\lib\site-packages\nltk-3.0.3-py2.7-win32.egg\nltk\__init__.py in <module>()
    126 ###########################################################
    127 
--> 128 from nltk.align import *
    129 from nltk.chunk import *
    130 from nltk.classify import *

C:\Python27\lib\site-packages\nltk-3.0.3-py2.7-win32.egg\nltk\align\__init__.py in <module>()
     16 from nltk.align.ibm2 import IBMModel2
     17 from nltk.align.ibm3 import IBMModel3
---> 18 from nltk.align.bleu_score import bleu
     19 
     20 

C:\Python27\lib\site-packages\nltk-3.0.3-py2.7-win32.egg\nltk\align\bleu_score.py in <module>()
     13 import math
     14 
---> 15 from nltk.tokenize import word_tokenize
     16 from nltk.compat import Counter
     17 from nltk.util import ngrams

C:\Python27\lib\site-packages\nltk-3.0.3-py2.7-win32.egg\nltk\tokenize\__init__.py in <module>()
     60 """
     61 
---> 62 from nltk.data              import load
     63 from nltk.tokenize.simple   import (SpaceTokenizer, TabTokenizer, LineTokenizer,
     64                                     line_tokenize)

C:\Python27\lib\site-packages\nltk-3.0.3-py2.7-win32.egg\nltk\data.py in <module>()
     74 # User-specified locations:
     75 path += [d for d in os.environ.get('NLTK_DATA', str('')).split(os.pathsep) if d]
---> 76 if 'APPENGINE_RUNTIME' not in os.environ and os.path.expanduser('~/') != '~/':
     77     path.append(os.path.expanduser(str('~/nltk_data')))
     78 

C:\Python27\lib\ntpath.pyc in expanduser(path)
    308         userhome = join(dirname(userhome), path[1:i])
    309 
--> 310     return userhome + path[i:]
    311 
    312 

UnicodeDecodeError: 'ascii' codec can't decode byte 0xca in position 9: ordinal not in range(128)
```

It doesn't matter whether I want to import some specific package or whole NLTK

After some investigations, I found out what thing in the code causes such error. This code:

``` python
from __future__ import unicode_literals
import os

some_path = os.path.expanduser('~/')
```

throws

``` python
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-3-8d64d3b3b127> in <module>()
      2 import os
      3 
----> 4 some_path = os.path.expanduser('~/')

C:\Python27\lib\ntpath.pyc in expanduser(path)
    308         userhome = join(dirname(userhome), path[1:i])
    309 
--> 310     return userhome + path[i:]
    311 
    312 

UnicodeDecodeError: 'ascii' codec can't decode byte 0xca in position 9: ordinal not in range(128)
```

Since `userhome` is byte string, path must be byte string too to successfully concatenate path elements. Thus I have decided to change line 76 in nltk.data from

``` python
if 'APPENGINE_RUNTIME' not in os.environ and os.path.expanduser('~/') != '~/':
```

to

``` python
if 'APPENGINE_RUNTIME' not in os.environ and os.path.expanduser(str('~/')) != str('~/'):
```

and this gave me successful import.

**Comment by alvations** [comment]
**Easiest Solution Possibly**: Using python3.0 

**Fastest Possible Hack**: Add these lines to your script before the imports 

```
import sys
reload(sys)
sys.setdefaultencoding("utf-8")
```

(But do note the caveats: http://stackoverflow.com/questions/3828723/why-we-need-sys-setdefaultencodingutf-8-in-a-py-script)

**Comment by Khutuck** [comment]
I've encountered the same problem in Windows 7. My path is as "C.\Users\Fırt" (ı has no dot, Turkish letter), and i was getting this:

```
Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.

>>> import nltk

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import nltk
  File "C:\Python27\lib\site-packages\nltk-3.0.0-py2.7-win32.egg\nltk__init__.py", line 117, in <module>
    from nltk.align import *
  File "C:\Python27\lib\site-packages\nltk-3.0.0-py2.7-win32.egg\nltk\align__init__.py", line 15, in <module>
    from nltk.align.ibm1 import IBMModel1
  File "C:\Python27\lib\site-packages\nltk-3.0.0-py2.7-win32.egg\nltk\align\ibm1.py", line 18, in <module>
    from nltk.corpus import comtrans
  File "C:\Python27\lib\site-packages\nltk-3.0.0-py2.7-win32.egg\nltk\corpus__init__.py", line 64, in <module>
    from nltk.tokenize import RegexpTokenizer
  File "C:\Python27\lib\site-packages\nltk-3.0.0-py2.7-win32.egg\nltk\tokenize__init__.py", line 62, in <module>
    from nltk.data              import load
  File "C:\Python27\lib\site-packages\nltk-3.0.0-py2.7-win32.egg\nltk\data.py", line 74, in <module>
    if os.path.expanduser('~/') != '~/':
  File "C:\Python27\lib\ntpath.py", line 311, in expanduser
    return userhome + path[i:]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfd in position 10: ordinal not in range(128)
```

I've tried this solution, and "import nltk" worked: http://stackoverflow.com/questions/31700152/i-can-not-import-nltk-in-python-in-windows7 (But this solution also caused soo may other problems, so it's not very useful).

**Comment by nschneid** [comment]
@Khutuck, what do you get if you type

```py
import os
os.path.expanduser('~/')
```

at the Python prompt? (Just to confirm the problem is due to NLTK's use of `unicode_literals`.)

**Comment by Khutuck** [comment]
@nschneid I still use the same PC and same username, I've updated from 2.7.10 to 2.7.13.

```
>>> import os
>>> os.path.expanduser('~/')
'C:\\Users\\F\xfdrt/'
```

and the "import nltk" still goes the same:

```
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import nltk

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import nltk
  File "C:\Python27\lib\site-packages\nltk\__init__.py", line 128, in <module>
    from nltk.chunk import *
  File "C:\Python27\lib\site-packages\nltk\chunk\__init__.py", line 155, in <module>
    from nltk.data import load
  File "C:\Python27\lib\site-packages\nltk\data.py", line 77, in <module>
    if 'APPENGINE_RUNTIME' not in os.environ and os.path.expanduser('~/') != '~/':
  File "C:\Python27\lib\ntpath.py", line 311, in expanduser
    return userhome + path[i:]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfd in position 10: ordinal not in range(128)
```

**Comment by alvations** [comment]
@nschneid definitely it's something that should be fixed in CPython upstream, `\xfd` looks like a badly read string.

@Khutuck what is your username on your machine?

What happens when you do this?

```
os.path.expanduser('$HOME')
```

And if you say this to a python script, `test.py` and run `python test.py`:

```
# -*- coding: utf8 -*-
import os
print os.path.expanduser('$HOME')
```

Do you still see the error?


How about this:

```
# -*- coding: utf8 -*-
import os
print os.path.expanduser('~/')
```

**Comment by Khutuck** [comment]
My username on the machine is "Fırt" (ı has no dots, it's a Turkish letter, Unicode U+0131 / &#305;)

On IDLE I get this:
```
>>> import os
>>> os.path.expanduser('$HOME')
'$HOME'
```

When I run test.py code below:
```
# -*- coding: utf8 -*-
import os
print os.path.expanduser('$HOME')

# -*- coding: utf8 -*-
import os
print os.path.expanduser('~/')
```
The output is this:
```
$HOME
C:\Users\Fırt/
```
