### ISSUE TITLE
Non deterministic gluesemanitcs tests.

### ISSUE THREAD

**Issue by dimazest** [nltk/nltk#1050]
Sometimes gluesemantics.doctest fails because of nondeterministic output. Here is an example of a successful run

```
[dimazest@mac nltk]$ tox -epy27 -- nltk.sem gluesemantics.doctest -v
GLOB sdist-make: /Users/dimazest/Documents/qmul/tools/src/nltk/setup.py
py27 inst-nodeps: /Users/dimazest/Documents/qmul/tools/src/nltk/.tox/dist/nltk-3.0.4.zip
py27 installed: coverage==3.7.1,nltk==3.0.4,nose==1.3.7,numpy==1.9.2,scikit-learn==0.16.1,scipy==0.15.1,text-unidecode==0.1,wheel==0.24.0
py27 runtests: PYTHONHASHSEED='1437179731'
py27 runtests: commands[0] | pip install --download-cache=/Users/dimazest/Documents/qmul/tools/src/nltk/.tox/_download scipy scikit-learn
You are using pip version 7.0.3, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
DEPRECATION: --download-cache has been deprecated and will be removed in the future. Pip now automatically uses and configures its cache.
Requirement already satisfied (use --upgrade to upgrade): scipy in /Users/dimazest/Documents/qmul/tools/src/nltk/.tox/py27/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): scikit-learn in /Users/dimazest/Documents/qmul/tools/src/nltk/.tox/py27/lib/python2.7/site-packages
py27 runtests: commands[1] | python runtests.py nltk.sem gluesemantics.doctest -v
Doctest: nltk.sem.evaluate.Assignment ... ok
Doctest: nltk.sem ... ok
Doctest: gluesemantics.doctest ... ok

----------------------------------------------------------------------
Ran 3 tests in 0.033s

OK
________________________________
```

This is a failing test

```
[dimazest@mac nltk]$ tox -epy27 -- nltk.sem gluesemantics.doctest -v
GLOB sdist-make: /Users/dimazest/Documents/qmul/tools/src/nltk/setup.py
py27 inst-nodeps: /Users/dimazest/Documents/qmul/tools/src/nltk/.tox/dist/nltk-3.0.4.zip
py27 installed: coverage==3.7.1,nltk==3.0.4,nose==1.3.7,numpy==1.9.2,scikit-learn==0.16.1,scipy==0.15.1,text-unidecode==0.1,wheel==0.24.0
py27 runtests: PYTHONHASHSEED='3335886864'
py27 runtests: commands[0] | pip install --download-cache=/Users/dimazest/Documents/qmul/tools/src/nltk/.tox/_download scipy scikit-learn
You are using pip version 7.0.3, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
DEPRECATION: --download-cache has been deprecated and will be removed in the future. Pip now automatically uses and configures its cache.
Requirement already satisfied (use --upgrade to upgrade): scipy in /Users/dimazest/Documents/qmul/tools/src/nltk/.tox/py27/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): scikit-learn in /Users/dimazest/Documents/qmul/tools/src/nltk/.tox/py27/lib/python2.7/site-packages
py27 runtests: commands[1] | python runtests.py nltk.sem gluesemantics.doctest -v
Doctest: nltk.sem.evaluate.Assignment ... ok
Doctest: nltk.sem ... ok
Doctest: gluesemantics.doctest ... FAIL

======================================================================
FAIL: Doctest: gluesemantics.doctest
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for gluesemantics.doctest
  File "/Users/dimazest/Documents/qmul/tools/src/nltk/nltk/test/gluesemantics.doctest", line 0

----------------------------------------------------------------------
File "/Users/dimazest/Documents/qmul/tools/src/nltk/nltk/test/gluesemantics.doctest", line 346, in gluesemantics.doctest
Failed example:
    for gf in gfl:
        print(gf)
Expected:
    \x y.sees(x,y) : (f -o (i -o g))
    \P Q.exists x.(P(x) & Q(x)) : ((fv -o fr) -o ((f -o F2) -o F2))
    \x.John(x) : (fv -o fr)
    \x.dog(x) : (iv -o ir)
    \P Q.exists x.(P(x) & Q(x)) : ((iv -o ir) -o ((i -o I5) -o I5))
Got:
    \x y.sees(x,y) : (f -o (i -o g))
    \x.dog(x) : (iv -o ir)
    \P Q.exists x.(P(x) & Q(x)) : ((iv -o ir) -o ((i -o I3) -o I3))
    \P Q.exists x.(P(x) & Q(x)) : ((fv -o fr) -o ((f -o F4) -o F4))
    \x.John(x) : (fv -o fr)
----------------------------------------------------------------------
File "/Users/dimazest/Documents/qmul/tools/src/nltk/nltk/test/gluesemantics.doctest", line 366, in gluesemantics.doctest
Failed example:
    print(fstruct)
Expected:
    f:[pred 'sees'
       obj h:[pred 'dog'
              spec 'a']
       subj g:[pred 'John']]
Got:
    f:[pred 'sees'
       obj g:[pred 'dog'
              spec 'a']
       subj h:[pred 'John']]


----------------------------------------------------------------------
Ran 3 tests in 0.040s

FAILED (failures=1)
ERROR: InvocationError: '/Users/dimazest/Documents/qmul/tools/src/nltk/.tox/py27/bin/python runtests.py nltk.sem gluesemantics.doctest -v'
________________________________________ summary _________________________________________
ERROR:   py27: commands failed
```

Am I right, that the different outputs are equivalent, even though they are order and variable names are different?

**Comment by stevenbird** [comment]
That's right, they're equivalent. Solutions are to skip the tests or to make them deterministic, as @kmike did [here](https://github.com/kmike/nltk/commit/0542ec47a69a6bdea00401d15de60e4b979b4feb) vs [here](https://github.com/nltk/nltk/pull/315).

A compromise which I like is to have a doctest for documentation purposes which is maximally readable (and which is skipped), plus a regression test which normalises the return value (sorting or conversion to a set) and then compares it to a literal.

**Comment by dimazest** [comment]
I'll try to make the test deterministic as having untested documentation example will ultimately lead to outdated docs.

**Comment by fievelk** [comment]
@dimazest @stevenbird Any news on this issue?
d3964cf and 7c7ad71 do not seem to have completely solved the problem (i.e. variable names are still different and this causes tests to fail).

I get these errors when I run `tox`:

```
======================================================================
FAIL: Doctest: gluesemantics.doctest
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for gluesemantics.doctest
  File "nltk/test/gluesemantics.doctest", line 0

----------------------------------------------------------------------
File "nltk/test/gluesemantics.doctest", line 346, in gluesemantics.doctest
Failed example:
    for gf in sorted(gfl):
        print(gf)
Expected:
    \P Q.exists x.(P(x) & Q(x)) : ((fv -o fr) -o ((f -o F2) -o F2))
    \P Q.exists x.(P(x) & Q(x)) : ((iv -o ir) -o ((i -o I5) -o I5))
    \x y.sees(x,y) : (f -o (i -o g))
    \x.John(x) : (fv -o fr)
    \x.dog(x) : (iv -o ir)
Got:
    \P Q.exists x.(P(x) & Q(x)) : ((fv -o fr) -o ((f -o F4) -o F4))
    \P Q.exists x.(P(x) & Q(x)) : ((iv -o ir) -o ((i -o I3) -o I3))
    \x y.sees(x,y) : (f -o (i -o g))
    \x.John(x) : (fv -o fr)
    \x.dog(x) : (iv -o ir)
----------------------------------------------------------------------
File "nltk/test/gluesemantics.doctest", line 378, in gluesemantics.doctest
Failed example:
    for gf in sorted(fstruct.to_glueformula_list(GlueDict('nltk:grammars/sample_grammars/glue.semtype'))):
        print(gf)
Expected:
    \P Q.exists x.(P(x) & Q(x)) : ((gv -o gr) -o ((g -o G5) -o G5))
    \P Q.exists x.(P(x) & Q(x)) : ((iv -o ir) -o ((i -o I2) -o I2))
    \x y.sees(x,y) : (i -o (g -o f))
    \x.John(x) : (iv -o ir)
    \x.dog(x) : (gv -o gr)
Got:
    \P Q.exists x.(P(x) & Q(x)) : ((gv -o gr) -o ((g -o G3) -o G3))
    \P Q.exists x.(P(x) & Q(x)) : ((iv -o ir) -o ((i -o I4) -o I4))
    \x y.sees(x,y) : (i -o (g -o f))
    \x.John(x) : (iv -o ir)
    \x.dog(x) : (gv -o gr)
```

**Comment by fievelk** [comment]
Builds are now succeeding, since non-deterministic tests are currently skipped thanks to 80ee12e15b30b4de533d54dc3336236f017bade8.
