### ISSUE TITLE
A request for span_tokenize for TreebankWordTokenizer

### ISSUE THREAD

**Issue by baoilleach** [nltk/nltk#1054]
It would be great to have a span_tokenize for the default word tokenizer. Currently...

```
>>> from nltk.tokenize import TreebankWordTokenizer
>>> a = TreebankWordTokenizer()
>>> a.tokenize("hello there")
['hello', 'there']
>>> a.span_tokenize("hello there")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\nltk\tokenize\api.py", line 39, in span_tokenize
    raise NotImplementedError()
NotImplementedError
```

**Comment by alvations** [comment]
c.f.  #131

**Comment by baoilleach** [comment]
Thanks.
