### ISSUE TITLE
NLTK downloader bug

### ISSUE THREAD

**Issue by IlinAleksey** [nltk/nltk#1056]
```
$ sudo python3 -m nltk.downloader
removing collection member with no package: customer_reviews_1
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.4/dist-packages/nltk/downloader.py", line 2273, in <module>
    halt_on_error=options.halt_on_error)
  File "/usr/local/lib/python3.4/dist-packages/nltk/downloader.py", line 655, in download
    self._interactive_download()
  File "/usr/local/lib/python3.4/dist-packages/nltk/downloader.py", line 974, in _interactive_download
    DownloaderGUI(self).mainloop()
  File "/usr/local/lib/python3.4/dist-packages/nltk/downloader.py", line 1234, in __init__
    self._fill_table()
  File "/usr/local/lib/python3.4/dist-packages/nltk/downloader.py", line 1530, in _fill_table
    items = self._ds.collections()
  File "/usr/local/lib/python3.4/dist-packages/nltk/downloader.py", line 499, in collections
    self._update_index()
  File "/usr/local/lib/python3.4/dist-packages/nltk/downloader.py", line 857, in _update_index
    packages[child.id] = child
AttributeError: 'str' object has no attribute 'id'
```

**Comment by mdegis** [comment]
Same error with python2.7

```
sudo python -m nltk.downloader all                                                                                             
removing collection member with no package: customer_reviews_1
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Library/Python/2.7/site-packages/nltk/downloader.py", line 2267, in <module>
    halt_on_error=options.halt_on_error)
  File "/Library/Python/2.7/site-packages/nltk/downloader.py", line 664, in download
    for msg in self.incr_download(info_or_id, download_dir, force):
  File "/Library/Python/2.7/site-packages/nltk/downloader.py", line 534, in incr_download
    try: info = self._info_or_id(info_or_id)
  File "/Library/Python/2.7/site-packages/nltk/downloader.py", line 508, in _info_or_id
    return self.info(info_or_id)
  File "/Library/Python/2.7/site-packages/nltk/downloader.py", line 875, in info
    self._update_index()
  File "/Library/Python/2.7/site-packages/nltk/downloader.py", line 857, in _update_index
    packages[child.id] = child
AttributeError: 'str' object has no attribute 'id'
```

**Comment by xandergroeneveld** [comment]
Yes all seeing this issue. It looks like the downloader loops over a collection of packages to install each however one of those packages is actually just the string "dependency_treebank". It has been talked about at the bottom of this closed issue: https://github.com/nltk/nltk/issues/882

**Comment by chr15m** [comment]
Hello, we are also getting this bug on `nltk==3.0.4`, Python 2.7.

**Comment by ewan-klein** [comment]
I think this was fixed in https://github.com/nltk/nltk_data/commit/a35beafa6aaa94b6e93895a86d54ed3827286ac4
