### ISSUE TITLE
Gensim errors on CI server

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#1069]
@longdt219 – there's some errors showing up on the [CI Server](https://nltk.ci.cloudbees.com/job/nltk/lastCompletedBuild/TOXENV=py26-jenkins,jdk=jdk8latestOnlineInstall/testReport/%28root%29/gensim_doctest/gensim_doctest/). Would you please take a look? It's also warning about not finding Theano, and printing out a log.

```
Failed doctest test for gensim.doctest
  File "/scratch/jenkins/workspace/nltk/TOXENV/py26-jenkins/jdk/jdk8latestOnlineInstall/nltk/test/gensim.doctest", line 0

----------------------------------------------------------------------
File "/scratch/jenkins/workspace/nltk/TOXENV/py26-jenkins/jdk/jdk8latestOnlineInstall/nltk/test/gensim.doctest", line 43, in gensim.doctest
Failed example:
    model = gensim.models.Word2Vec.load(word2vec_sample)
Exception raised:
    Traceback (most recent call last):
      File "/scratch/jenkins/python/python-2.6.9-x86_64/lib/python2.6/doctest.py", line 1253, in __run
        compileflags, 1) in test.globs
      File "<doctest gensim.doctest[9]>", line 1, in <module>
        model = gensim.models.Word2Vec.load(word2vec_sample)
      File "/scratch/jenkins/workspace/nltk/TOXENV/py26-jenkins/jdk/jdk8latestOnlineInstall/.tox/py26-jenkins/lib/python2.6/site-packages/gensim/models/word2vec.py", line 1383, in load
        v.sample_int = int(round(v.sample_probability * 2**32))
    AttributeError: 'Vocab' object has no attribute 'sample_probability'
----------------------------------------------------------------------
File "/scratch/jenkins/workspace/nltk/TOXENV/py26-jenkins/jdk/jdk8latestOnlineInstall/nltk/test/gensim.doctest", line 46, in gensim.doctest
Failed example:
    len(model.vocab)
Expected:
    43981
Got:
    15173
----------------------------------------------------------------------
File "/scratch/jenkins/workspace/nltk/TOXENV/py26-jenkins/jdk/jdk8latestOnlineInstall/nltk/test/gensim.doctest", line 50, in gensim.doctest
Failed example:
    len(model['university'])
Expected:
    300
Got:
    100
----------------------------------------------------------------------
File "/scratch/jenkins/workspace/nltk/TOXENV/py26-jenkins/jdk/jdk8latestOnlineInstall/nltk/test/gensim.doctest", line 54, in gensim.doctest
Failed example:
    model.most_similar(positive=['university'], topn = 3)
Expected:
    [(u'universities', 0.7003918886184692), (u'faculty', 0.6780908703804016), (u'undergraduate', 0.6587098240852356)]
Got:
    [(u'pension', 0.81222623586654663), (u'factory', 0.78358858823776245), (u'hurricane', 0.76753336191177368)]
----------------------------------------------------------------------
File "/scratch/jenkins/workspace/nltk/TOXENV/py26-jenkins/jdk/jdk8latestOnlineInstall/nltk/test/gensim.doctest", line 63, in gensim.doctest
Failed example:
    model.most_similar(positive=['woman','king'], negative=['man'], topn = 1)
Expected:
    [(u'queen', 0.7118192911148071)]
Got:
    [(u'urbanization', 0.82805019617080688)]
----------------------------------------------------------------------
File "/scratch/jenkins/workspace/nltk/TOXENV/py26-jenkins/jdk/jdk8latestOnlineInstall/nltk/test/gensim.doctest", line 66, in gensim.doctest
Failed example:
    model.most_similar(positive=['Paris','Germany'], negative=['Berlin'], topn = 1)
Expected:
    [(u'France', 0.7884092926979065)]
Got:
    [(u'Italy', 0.76796293258666992)]
```

**Comment by stevenbird** [comment]
Seems ok now.
