### ISSUE TITLE
align.doctest errors

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#1089]
The changes to `nltk.align` have resulted in some doctest errors, e.g.:

```
% cd nltk/nltk/test
% make align.errs
File "/Users/sb/git/nltk/nltk/test/align.doctest", line 86, in align.doctest
Failed example:
    print(round(em_ibm1.probabilities['the']['das'], 1))
Exception raised:
    Traceback (most recent call last):
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/doctest.py", line 1318, in __run
        compileflags, 1), test.globs)
      File "<doctest align.doctest[15]>", line 1, in <module>
        print(round(em_ibm1.probabilities['the']['das'], 1))
    AttributeError: 'IBMModel1' object has no attribute 'probabilities'
```

@hoontw, would you please take a look at this?

**Comment by hoontw** [comment]
Sure. Sorry for the mistake. I didn't realize that there were other doctests hiding in the /test folder.

**Comment by stevenbird** [comment]
Thanks
