### ISSUE TITLE
Tests are failing with python 2.7

### ISSUE THREAD

**Issue by kmike** [nltk/nltk#11]
```
_________________________________ [tox sdist] __________________________________
[TOX] ***creating sdist package
[TOX] /Users/kmike/svn/nltk$ /usr/local/Cellar/python/2.7.2/bin/python setup.py sdist --formats=zip --dist-dir .tox/dist >.tox/log/0.log
[TOX] ***copying new sdistfile to '/Users/kmike/.tox/distshare/nltk-2.0.1rc3.zip'
______________________________ [tox testenv:py27] ______________________________
[TOX] ***reusing existing matching virtualenv py27
[TOX] ***upgrade-installing sdist
[TOX] /Users/kmike/svn/nltk/.tox/py27/log$ ../bin/pip install --download-cache=/Users/kmike/svn/nltk/.tox/_download /Users/kmike/svn/nltk/.tox/dist/nltk-2.0.1rc3.zip -U --no-deps >13.log
[TOX] /Users/kmike/svn/nltk/nltk/test$ ../../.tox/py27/bin/python testrunner.py
[?1034h
***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/align.doctest", line 49, in align.doctest
Failed example:
    als.alignment = align.Alignment([(0, 0), (1, 4), (2, 1), (3, 3)])
Expected:
    Traceback (most recent call last):
        ...
    IndexError: Alignment is outside boundary of mots
Got:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest align.doctest[9]>", line 1, in <module>
        als.alignment = align.Alignment([(0, 0), (1, 4), (2, 1), (3, 3)])
    AttributeError: can't set attribute

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/align.doctest", line 53, in align.doctest
Failed example:
    als.alignment = align.Alignment([(-1, 0), (1, 2), (2, 1), (3, 3)])
Expected:
    Traceback (most recent call last):
        ...
    IndexError: Alignment is outside boundary of words
Got:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest align.doctest[10]>", line 1, in <module>
        als.alignment = align.Alignment([(-1, 0), (1, 2), (2, 1), (3, 3)])
    AttributeError: can't set attribute

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/align.doctest", line 59, in align.doctest
Failed example:
    als.alignment = align.Alignment([(1, 3), (3, 2), (0, 1), (2, 0)])
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest align.doctest[12]>", line 1, in <module>
        als.alignment = align.Alignment([(1, 3), (3, 2), (0, 1), (2, 0)])
    AttributeError: can't set attribute

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/align.doctest", line 60, in align.doctest
Failed example:
    als.alignment
Expected:
    Alignment([(0, 1), (1, 3), (2, 0), (3, 2)])
Got:
    Alignment([(0, 0), (1, 1), (2, 2), (3, 3)])

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/align.doctest", line 67, in align.doctest
Failed example:
    als.alignment = [(0, 0), (1, 1), (2, 2, "boat"), (3, 3, False, (1,2))]
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest align.doctest[14]>", line 1, in <module>
        als.alignment = [(0, 0), (1, 1), (2, 2, "boat"), (3, 3, False, (1,2))]
    AttributeError: can't set attribute

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/align.doctest", line 68, in align.doctest
Failed example:
    als.alignment
Expected:
    Alignment([(0, 0), (1, 1), (2, 2, 'boat'), (3, 3, False, (1, 2))])
Got:
    Alignment([(0, 0), (1, 1), (2, 2), (3, 3)])

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/align.doctest", line 70, in align.doctest
Failed example:
    als.alignment = ((0, 0), (1, 1), (2, 2), (3, 3))
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest align.doctest[16]>", line 1, in <module>
        als.alignment = ((0, 0), (1, 1), (2, 2), (3, 3))
    AttributeError: can't set attribute

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/align.doctest", line 86, in align.doctest
Failed example:
    em_ibm1 = align.EMIBMModel1(corpus, 1e-3)
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest align.doctest[19]>", line 1, in <module>
        em_ibm1 = align.EMIBMModel1(corpus, 1e-3)
    AttributeError: 'module' object has no attribute 'EMIBMModel1'

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/align.doctest", line 87, in align.doctest
Failed example:
    iterations = em_ibm1.train()
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest align.doctest[20]>", line 1, in <module>
        iterations = em_ibm1.train()
    NameError: name 'em_ibm1' is not defined

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/align.doctest", line 88, in align.doctest
Failed example:
    print round(em_ibm1.probabilities['the', 'das'], 1)
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest align.doctest[21]>", line 1, in <module>
        print round(em_ibm1.probabilities['the', 'das'], 1)
    NameError: name 'em_ibm1' is not defined

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/align.doctest", line 90, in align.doctest
Failed example:
    print round(em_ibm1.probabilities['book', 'das'], 1)
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest align.doctest[22]>", line 1, in <module>
        print round(em_ibm1.probabilities['book', 'das'], 1)
    NameError: name 'em_ibm1' is not defined

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/align.doctest", line 92, in align.doctest
Failed example:
    print round(em_ibm1.probabilities['house', 'das'], 1)
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest align.doctest[23]>", line 1, in <module>
        print round(em_ibm1.probabilities['house', 'das'], 1)
    NameError: name 'em_ibm1' is not defined

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/align.doctest", line 94, in align.doctest
Failed example:
    print round(em_ibm1.probabilities['the', 'Buch'], 1)
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest align.doctest[24]>", line 1, in <module>
        print round(em_ibm1.probabilities['the', 'Buch'], 1)
    NameError: name 'em_ibm1' is not defined

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/align.doctest", line 96, in align.doctest
Failed example:
    print round(em_ibm1.probabilities['book', 'Buch'], 1)
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest align.doctest[25]>", line 1, in <module>
        print round(em_ibm1.probabilities['book', 'Buch'], 1)
    NameError: name 'em_ibm1' is not defined

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/align.doctest", line 98, in align.doctest
Failed example:
    print round(em_ibm1.probabilities['a', 'Buch'], 1)
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest align.doctest[26]>", line 1, in <module>
        print round(em_ibm1.probabilities['a', 'Buch'], 1)
    NameError: name 'em_ibm1' is not defined

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/align.doctest", line 100, in align.doctest
Failed example:
    print round(em_ibm1.probabilities['book', 'ein'], 1)
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest align.doctest[27]>", line 1, in <module>
        print round(em_ibm1.probabilities['book', 'ein'], 1)
    NameError: name 'em_ibm1' is not defined

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/align.doctest", line 102, in align.doctest
Failed example:
    print round(em_ibm1.probabilities['a', 'ein'], 1)
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest align.doctest[28]>", line 1, in <module>
        print round(em_ibm1.probabilities['a', 'ein'], 1)
    NameError: name 'em_ibm1' is not defined

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/align.doctest", line 104, in align.doctest
Failed example:
    print round(em_ibm1.probabilities['the', 'Haus'], 1)
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest align.doctest[29]>", line 1, in <module>
        print round(em_ibm1.probabilities['the', 'Haus'], 1)
    NameError: name 'em_ibm1' is not defined

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/align.doctest", line 106, in align.doctest
Failed example:
    print round(em_ibm1.probabilities['house', 'Haus'], 1)
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest align.doctest[30]>", line 1, in <module>
        print round(em_ibm1.probabilities['house', 'Haus'], 1)
    NameError: name 'em_ibm1' is not defined

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/align.doctest", line 112, in align.doctest
Failed example:
    em_ibm1.aligned() # doctest: +NORMALIZE_WHITESPACE
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest align.doctest[31]>", line 1, in <module>
        em_ibm1.aligned() # doctest: +NORMALIZE_WHITESPACE
    NameError: name 'em_ibm1' is not defined
.
***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/chat80.doctest", line 205, in chat80.doctest
Failed example:
    trees = cp.nbest_parse(query.split())
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest chat80.doctest[21]>", line 1, in <module>
        trees = cp.nbest_parse(query.split())
    AttributeError: 'FeatureGrammar' object has no attribute 'nbest_parse'

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/chat80.doctest", line 206, in chat80.doctest
Failed example:
    answer = trees[0].node['SEM']
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest chat80.doctest[22]>", line 1, in <module>
        answer = trees[0].node['SEM']
    NameError: name 'trees' is not defined

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/chat80.doctest", line 207, in chat80.doctest
Failed example:
    q = join(answer)
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest chat80.doctest[23]>", line 1, in <module>
        q = join(answer)
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/string.py", line 318, in join
        return sep.join(words)
    TypeError: sequence item 1: expected string, int found

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/chat80.doctest", line 208, in chat80.doctest
Failed example:
    print q
Expected:
    SELECT City FROM city_table WHERE   Country="china"
Got:
    SELECT City, Population FROM city_table WHERE Country = 'china' and Population > 1000

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/chat80.doctest", line 211, in chat80.doctest
Failed example:
    for r in rows: print "%s" % r,
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest chat80.doctest[26]>", line 1, in <module>
        for r in rows: print "%s" % r,
    TypeError: not all arguments converted during string formatting
.
***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/chunk.doctest", line 99, in chunk.doctest
Failed example:
    chunkscore.recall()
Expected:
    0.33333333333333331
Got:
    0.3333333333333333

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/chunk.doctest", line 102, in chunk.doctest
Failed example:
    chunkscore.f_measure()
Expected:
    0.40000000000000002
Got:
    0.4
........
***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/japanese.doctest", line 23, in japanese.doctest
Failed example:
    type(knbc.words()[0])
Expected:
    <type 'str'>
Got:
    <type 'unicode'>

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/japanese.doctest", line 28, in japanese.doctest
Failed example:
    type(knbc.sents()[0][0])
Expected:
    <type 'str'>
Got:
    <type 'unicode'>

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/japanese.doctest", line 49, in japanese.doctest
Failed example:
    type(jeita.tagged_words()[0][1])
Expected:
    <type 'str'>
Got:
    <type 'unicode'>
..
***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/metrics.doctest", line 22, in metrics.doctest
Failed example:
    accuracy(reference, test)
Expected:
    0.80000000000000004
Got:
    0.8

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/metrics.doctest", line 32, in metrics.doctest
Failed example:
    recall(reference_set, test_set)
Expected:
    0.80000000000000004
Got:
    0.8

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/metrics.doctest", line 34, in metrics.doctest
Failed example:
    f_measure(reference_set, test_set)
Expected:
    0.88888888888888884
Got:
    0.8888888888888888

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/metrics.doctest", line 61, in metrics.doctest
Failed example:
    jaccard_distance(s1, s2)
Expected:
    0.59999999999999998
Got:
    0.6
..
***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/parse.doctest", line 552, in parse.doctest
Failed example:
    prod.prob()
Expected:
    0.29999999999999999
Got:
    0.3
.
***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/resolution.doctest", line 163, in resolution.doctest
Failed example:
    print tp.proof()
Expected:
    [1] {-mortal(Socrates)}     A
    [2] {-man(z2), mortal(z2)}  A
    [3] {man(Socrates)}         A
    [4] {-man(Socrates)}        (1, 2)
    [5] {mortal(Socrates)}      (2, 3)
    [6] {}                      (1, 5)
    <BLANKLINE>
Got:
    [1] {-mortal(Socrates)}     A 
    [2] {-man(z2), mortal(z2)}  A 
    [3] {man(Socrates)}         A 
    [4] {-man(Socrates)}        (1, 2) 
    [5] {mortal(Socrates)}      (2, 3) 
    [6] {}                      (1, 5) 
    <BLANKLINE>

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/resolution.doctest", line 184, in resolution.doctest
Failed example:
    print tp.proof()
Expected:
    [1] {father_of(art,john)}                  A
    [2] {father_of(bob,kim)}                   A
    [3] {-father_of(z4,z3), parent_of(z4,z3)}  A
    [4] {-parent_of(z6,john), ANSWER(z6)}      A
    [5] {parent_of(art,john)}                  (1, 3)
    [6] {parent_of(bob,kim)}                   (2, 3)
    [7] {ANSWER(z6), -father_of(z6,john)}      (3, 4)
    [8] {ANSWER(art)}                          (1, 7)
    [9] {ANSWER(art)}                          (4, 5)
    <BLANKLINE>
Got:
    [1] {father_of(art,john)}                  A 
    [2] {father_of(bob,kim)}                   A 
    [3] {-father_of(z4,z3), parent_of(z4,z3)}  A 
    [4] {-parent_of(z6,john), ANSWER(z6)}      A 
    [5] {parent_of(art,john)}                  (1, 3) 
    [6] {parent_of(bob,kim)}                   (2, 3) 
    [7] {ANSWER(z6), -father_of(z6,john)}      (3, 4) 
    [8] {ANSWER(art)}                          (1, 7) 
    [9] {ANSWER(art)}                          (4, 5) 
    <BLANKLINE>

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/resolution.doctest", line 206, in resolution.doctest
Failed example:
    print tp.proof()
Expected:
    [ 1] {father_of(art,john)}                  A
    [ 2] {mother_of(ann,john)}                  A
    [ 3] {-father_of(z4,z3), parent_of(z4,z3)}  A
    [ 4] {-mother_of(z8,z7), parent_of(z8,z7)}  A
    [ 5] {-parent_of(z10,john), ANSWER(z10)}    A
    [ 6] {parent_of(art,john)}                  (1, 3)
    [ 7] {parent_of(ann,john)}                  (2, 4)
    [ 8] {ANSWER(z10), -father_of(z10,john)}    (3, 5)
    [ 9] {ANSWER(art)}                          (1, 8)
    [10] {ANSWER(z10), -mother_of(z10,john)}    (4, 5)
    [11] {ANSWER(ann)}                          (2, 10)
    [12] {ANSWER(art)}                          (5, 6)
    [13] {ANSWER(ann)}                          (5, 7)
    <BLANKLINE>
Got:
    [ 1] {father_of(art,john)}                  A 
    [ 2] {mother_of(ann,john)}                  A 
    [ 3] {-father_of(z4,z3), parent_of(z4,z3)}  A 
    [ 4] {-mother_of(z8,z7), parent_of(z8,z7)}  A 
    [ 5] {-parent_of(z10,john), ANSWER(z10)}    A 
    [ 6] {parent_of(art,john)}                  (1, 3) 
    [ 7] {parent_of(ann,john)}                  (2, 4) 
    [ 8] {ANSWER(z10), -father_of(z10,john)}    (3, 5) 
    [ 9] {ANSWER(art)}                          (1, 8) 
    [10] {ANSWER(z10), -mother_of(z10,john)}    (4, 5) 
    [11] {ANSWER(ann)}                          (2, 10) 
    [12] {ANSWER(art)}                          (5, 6) 
    [13] {ANSWER(ann)}                          (5, 7) 
    <BLANKLINE>
.
***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/semantics.doctest", line 663, in semantics.doctest
Failed example:
    print cs_semrep.core
Expected:
    chase(z2,z4)
Got:
    chase(z2,z3)

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/semantics.doctest", line 665, in semantics.doctest
Failed example:
    for bo in cs_semrep.store:
        print bo
Expected:
    bo(\P.all x.(girl(x) -> P(x)),z2)
    bo(\P.exists x.(dog(x) & P(x)),z4)
Got:
    bo(\P.all x.(girl(x) -> P(x)),z2)
    bo(\P.exists x.(dog(x) & P(x)),z3)

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/semantics.doctest", line 669, in semantics.doctest
Failed example:
    cs_semrep.s_retrieve(trace=True)
Expected:
    Permutation 1
       (\P.all x.(girl(x) -> P(x)))(\z2.chase(z2,z4))
       (\P.exists x.(dog(x) & P(x)))(\z4.all x.(girl(x) -> chase(x,z4)))
    Permutation 2
       (\P.exists x.(dog(x) & P(x)))(\z4.chase(z2,z4))
       (\P.all x.(girl(x) -> P(x)))(\z2.exists x.(dog(x) & chase(z2,x)))
Got:
    Permutation 1
       (\P.all x.(girl(x) -> P(x)))(\z2.chase(z2,z3))
       (\P.exists x.(dog(x) & P(x)))(\z3.all x.(girl(x) -> chase(x,z3)))
    Permutation 2
       (\P.exists x.(dog(x) & P(x)))(\z3.chase(z2,z3))
       (\P.all x.(girl(x) -> P(x)))(\z2.exists x.(dog(x) & chase(z2,x)))

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/semantics.doctest", line 677, in semantics.doctest
Failed example:
    for reading in cs_semrep.readings:
        print reading
Expected:
    exists x.(dog(x) & all z3.(girl(z3) -> chase(z3,x)))
    all x.(girl(x) -> exists z4.(dog(z4) & chase(x,z4)))
Got:
    exists x.(dog(x) & all z13.(girl(z13) -> chase(z13,x)))
    all x.(girl(x) -> exists z14.(dog(z14) & chase(x,z14)))
.
***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/simple.doctest", line 33, in simple.doctest
Failed example:
    recall(reference_set, test_set)
Expected:
    0.80000000000000004
Got:
    0.8

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/simple.doctest", line 35, in simple.doctest
Failed example:
    f_measure(reference_set, test_set)
Expected:
    0.88888888888888884
Got:
    0.8888888888888888
.
***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/sourcedstring.doctest", line 1246, in sourcedstring.doctest
Failed example:
    re.sub('better', 'worse', sent)
Expected:
    'I got worse.'
Got:
    'I got worse.'@[27:33,27:27,...,27:27,39:40]

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/sourcedstring.doctest", line 1254, in sourcedstring.doctest
Failed example:
    re.sub('better', 'worse', sent)
Expected:
    'I got worse.'
Got:
    'I got worse.'@[27:33,27:27,...,27:27,39:40]

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/sourcedstring.doctest", line 1448, in sourcedstring.doctest
Failed example:
    x.rpartition(y)
Expected:
    ('ascii byte string'@[0:17], ''@[17:17], ''@[17:17])
Got:
    (''@[0:0], ''@[0:0], 'ascii byte string'@[0:17])
...
***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/tokenize.doctest", line 20, in tokenize.doctest
Failed example:
    print regexp_tokenize(s2, r'[,\.\?!"]\s*', gaps=True)
Expected:
    ['Alas', 'it has not rained today', 'When', 'do you think',
     'will it rain again']
Got:
    ['Alas', 'it has not rained today', 'When', 'do you think', 'will it rain again']

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/tokenize.doctest", line 28, in tokenize.doctest
Failed example:
    print regexp_tokenize(s3, r'</?(b|p)>', gaps=True)
Expected:
    ['Although this is ', 'not',
     ' the case here, we must not relax our vigilance!']
Got:
    ['Although this is ', 'not', ' the case here, we must not relax our vigilance!']

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/tokenize.doctest", line 36, in tokenize.doctest
Failed example:
    print regexp_tokenize(s3, r'</?(?P<named>b|p)>', gaps=True)
Expected:
    ['Although this is ', 'not',
     ' the case here, we must not relax our vigilance!']
Got:
    ['Although this is ', 'not', ' the case here, we must not relax our vigilance!']

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/tokenize.doctest", line 44, in tokenize.doctest
Failed example:
    print regexp_tokenize(s2, r'(h|r|l)a(s|(i|n0))', gaps=True)
Expected:
    ['A', ', it ', ' not ', 'ned today. When, do you think, will it ',
     'n again?']
Got:
    ['A', ', it ', ' not ', 'ned today. When, do you think, will it ', 'n again?']

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/tokenize.doctest", line 50, in tokenize.doctest
Failed example:
    print regexp_tokenize(s2, r'(.)\1')
Expected:
    Traceback (most recent call last):
       ...
    ValueError: Regular expressions with back-references are
    not supported: '(.)\\1'
Got:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest tokenize.doctest[12]>", line 1, in <module>
        print regexp_tokenize(s2, r'(.)\1')
      File "/Users/kmike/svn/nltk/nltk/tokenize/regexp.py", line 192, in regexp_tokenize
        tokenizer = RegexpTokenizer(pattern, gaps, discard_empty, flags)
      File "/Users/kmike/svn/nltk/nltk/tokenize/regexp.py", line 112, in __init__
        nongrouping_pattern = convert_regexp_to_nongrouping(pattern)
      File "/Users/kmike/svn/nltk/nltk/internals.py", line 44, in convert_regexp_to_nongrouping
        'are not supported: %r' % pattern)
    ValueError: Regular expressions with back-references are not supported: '(.)\\1'

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/tokenize.doctest", line 55, in tokenize.doctest
Failed example:
    print regexp_tokenize(s2, r'(?P<foo>)(?P=foo)')
Expected:
    Traceback (most recent call last):
       ...
    ValueError: Regular expressions with back-references are
    not supported: '(?P<foo>)(?P=foo)'
Got:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest tokenize.doctest[13]>", line 1, in <module>
        print regexp_tokenize(s2, r'(?P<foo>)(?P=foo)')
      File "/Users/kmike/svn/nltk/nltk/tokenize/regexp.py", line 192, in regexp_tokenize
        tokenizer = RegexpTokenizer(pattern, gaps, discard_empty, flags)
      File "/Users/kmike/svn/nltk/nltk/tokenize/regexp.py", line 112, in __init__
        nongrouping_pattern = convert_regexp_to_nongrouping(pattern)
      File "/Users/kmike/svn/nltk/nltk/internals.py", line 44, in convert_regexp_to_nongrouping
        'are not supported: %r' % pattern)
    ValueError: Regular expressions with back-references are not supported: '(?P<foo>)(?P=foo)'

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/tokenize.doctest", line 63, in tokenize.doctest
Failed example:
    print regexp_tokenize(s, pattern=r'\.(\s+|$)', gaps=True)
Expected:
    ['Good muffins cost $3.88\nin New York',
     'Please buy me\ntwo of them', 'Thanks']
Got:
    ['Good muffins cost $3.88\nin New York', 'Please buy me\ntwo of them', 'Thanks']
..
***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/tree.doctest", line 16, in tree.doctest
Failed example:
    print tree
Expected nothing
Got:
    (s (dp (d the) (np dog)) (vp (v chased) (dp (d the) (np cat))))

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/tree.doctest", line 24, in tree.doctest
Failed example:
    print tree[path]
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest tree.doctest[7]>", line 1, in <module>
        print tree[path]
    NameError: name 'path' is not defined

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/tree.doctest", line 37, in tree.doctest
Failed example:
    print tree.pprint_latex_qtree()
Expected:
    \Tree [.s
            [.np [.d THE ] [.np DOG ] ]
            [.vp [.v CHASED ] [.np [.d THE ] [.np CAT ] ] ] ]
Got:
    \Tree [.s
            [.dp [.d the ] [.np dog ] ]
            [.vp [.v chased ] [.dp [.d the ] [.np cat ] ] ] ]

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/tree.doctest", line 692, in tree.doctest
Failed example:
    ptree[0,0].remove(make_ptree('(Q p)'))
Expected:
    Traceback (most recent call last):
      . . .
    ValueError: list.index(x): x not in list
Got:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest tree.doctest[155]>", line 1, in <module>
        ptree[0,0].remove(make_ptree('(Q p)'))
      File "/Users/kmike/svn/nltk/nltk/tree.py", line 986, in remove
        index = self.index(child)
    ValueError: ParentedTree('Q', ['p']) is not in list

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/tree.doctest", line 698, in tree.doctest
Failed example:
    ptree.remove('h');
Expected:
    Traceback (most recent call last):
      . . .
    ValueError: list.index(x): x not in list
Got:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest tree.doctest[157]>", line 1, in <module>
        ptree.remove('h');
      File "/Users/kmike/svn/nltk/nltk/tree.py", line 986, in remove
        index = self.index(child)
    ValueError: 'h' is not in list

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/tree.doctest", line 994, in tree.doctest
Failed example:
    mptree[0,0].remove(make_mptree('(Q p)'))
Expected:
    Traceback (most recent call last):
      . . .
    ValueError: list.index(x): x not in list
Got:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest tree.doctest[234]>", line 1, in <module>
        mptree[0,0].remove(make_mptree('(Q p)'))
      File "/Users/kmike/svn/nltk/nltk/tree.py", line 986, in remove
        index = self.index(child)
    ValueError: MultiParentedTree('Q', ['p']) is not in list

***************************************************************************
File "/Users/kmike/svn/nltk/nltk/test/tree.doctest", line 1000, in tree.doctest
Failed example:
    mptree.remove('h');
Expected:
    Traceback (most recent call last):
      . . .
    ValueError: list.index(x): x not in list
Got:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/doctest.py", line 1254, in __run
        compileflags, 1) in test.globs
      File "<doctest tree.doctest[236]>", line 1, in <module>
        mptree.remove('h');
      File "/Users/kmike/svn/nltk/nltk/tree.py", line 986, in remove
        index = self.index(child)
    ValueError: 'h' is not in list
....
A test failed unexpectedly. Please report this error
to the nltk-dev mailinglist.
[TOX] ERROR: InvocationError: '../../.tox/py27/bin/python testrunner.py'
________________________________ [tox summary] _________________________________
[TOX] ERROR: py27: commands failed
```

**Comment by timClicks** [comment]
Regarding your recent email thread, many of these examples raise `AttributeError`, which indicates an API change rather than a problem with doctest per se.

**Comment by kmike** [comment]
@timClicks Yeah, you're right, that's why I didn't mention align.doctest in that thread (https://groups.google.com/forum/#!topic/nltk-dev/_pEuA0kTlkg)

**Comment by kmike** [comment]
Some tests were fixed, some are still failing: https://gist.github.com/1596526

**Comment by kmike** [comment]
This ticket doesn't have useful information, the error report is only for .doctest files, and many test failures was fixed so I'm closing it in favor of more specific tickets.

**Comment by zcc973784075** [comment]
what's the way to solve that i.e. 'RecursiveDescentParser' object has no attribute 'nbest_parse'?THX
