### ISSUE TITLE
Download of punkt not working (package vs string issue)

### ISSUE THREAD

**Issue by salimzayat** [nltk/nltk#1147]
I am trying to download the punkt package:
python version: 2.7
nltk version: 1.0.1
command: python -m nltk.downloader punkt
stacktrace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/local/go-agent/pipelines/RightNow-NarrativeScrub-PROD/environment/scrubber/.py/lib/python2.7/site-packages/nltk/downloader.py", line 2257, in <module>
    halt_on_error=options.halt_on_error)
  File "/home/local/go-agent/pipelines/RightNow-NarrativeScrub-PROD/environment/scrubber/.py/lib/python2.7/site-packages/nltk/downloader.py", line 665, in download
    for msg in self.incr_download(info_or_id, download_dir, force):
  File "/home/local/go-agent/pipelines/RightNow-NarrativeScrub-PROD/environment/scrubber/.py/lib/python2.7/site-packages/nltk/downloader.py", line 535, in incr_download
    try: info = self._info_or_id(info_or_id)
  File "/home/local/go-agent/pipelines/RightNow-NarrativeScrub-PROD/environment/scrubber/.py/lib/python2.7/site-packages/nltk/downloader.py", line 509, in _info_or_id
    return self.info(info_or_id)
  File "/home/local/go-agent/pipelines/RightNow-NarrativeScrub-PROD/environment/scrubber/.py/lib/python2.7/site-packages/nltk/downloader.py", line 873, in info
    self._update_index()
  File "/home/local/go-agent/pipelines/RightNow-NarrativeScrub-PROD/environment/scrubber/.py/lib/python2.7/site-packages/nltk/downloader.py", line 855, in _update_index
    packages[child.id] = child
AttributeError: 'str' object has no attribute 'id'
```

**Comment by stevenbird** [comment]
Please update your NLTK installation to the current version.

**Comment by salimzayat** [comment]
That did it.  Thanks, Steven.

BTW, I don't know if you remember me.  I worked for you at the LDC after I got out of college, back in 2001 or so.  I don't think any of the stuff I did for the nltk back then stuck around, but it was a good time.
