### ISSUE TITLE
Gale-Church aligner raises TypeError

### ISSUE THREAD

**Issue by cassidylaidlaw** [nltk/nltk#1293]
Running

```
nltk.translate.gale_church.align_blocks([10] * 20, [200, 400])
```

raises

```
TypeError: 'NoneType' object is not iterable
```

---

Example:

``` python
>>> from nltk.translate import gale_church
>>> gale_church.align_blocks([5,5,5], [7,7,7])
[(0, 0), (1, 1), (2, 2)]
>>> gale_church.align_blocks([10,] * 20, [5])
[(18, 0), (19, 0)]
>>> gale_church.align_blocks([10,] * 20, [5, 10])
[(16, 0), (17, 0), (18, 1), (19, 1)]
>>> gale_church.align_blocks([10] * 20, [5, 10])
[(16, 0), (17, 0), (18, 1), (19, 1)]
>>> gale_church.align_blocks([10] * 20, [200, 400])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nltk/translate/gale_church.py", line 168, in align_blocks
    return trace(backlinks, source_sents, target_sents)
  File "nltk/translate/gale_church.py", line 84, in trace
    s, t = backlinks[pos]
TypeError: 'NoneType' object is not iterable
```

**Comment by alvations** [comment]
Looks like a quirky bug:

``` python
>>> gale_church.align_blocks([500, 400], [500])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nltk/translate/gale_church.py", line 168, in align_blocks
    return trace(backlinks, source_sents, target_sents)
  File "nltk/translate/gale_church.py", line 84, in trace
    s, t = backlinks[pos]
TypeError: 'NoneType' object is not iterable
>>> gale_church.align_blocks([500, 300], [500])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nltk/translate/gale_church.py", line 168, in align_blocks
    return trace(backlinks, source_sents, target_sents)
  File "nltk/translate/gale_church.py", line 84, in trace
    s, t = backlinks[pos]
TypeError: 'NoneType' object is not iterable
>>> gale_church.align_blocks([500, 200], [500])
[(0, 0), (1, 0)]
>>> gale_church.align_blocks([500, 201], [500])
[(0, 0), (1, 0)]
>>> gale_church.align_blocks([500, 250], [500])
[(0, 0), (1, 0)]
>>> gale_church.align_blocks([500, 251], [500])
[(0, 0), (1, 0)]
>>> gale_church.align_blocks([500, 299], [500])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nltk/translate/gale_church.py", line 168, in align_blocks
    return trace(backlinks, source_sents, target_sents)
  File "nltk/translate/gale_church.py", line 84, in trace
    s, t = backlinks[pos]
TypeError: 'NoneType' object is not iterable
>>> gale_church.align_blocks([500, 275], [500])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nltk/translate/gale_church.py", line 168, in align_blocks
    return trace(backlinks, source_sents, target_sents)
  File "nltk/translate/gale_church.py", line 84, in trace
    s, t = backlinks[pos]
TypeError: 'NoneType' object is not iterable
>>> gale_church.align_blocks([500, 250], [500])
[(0, 0), (1, 0)]
>>> gale_church.align_blocks([500, 252], [500])
[(0, 0), (1, 0)]
>>> gale_church.align_blocks([500, 260], [500])
[(0, 0), (1, 0)]
>>> gale_church.align_blocks([500, 270], [500])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nltk/translate/gale_church.py", line 168, in align_blocks
    return trace(backlinks, source_sents, target_sents)
  File "nltk/translate/gale_church.py", line 84, in trace
    s, t = backlinks[pos]
TypeError: 'NoneType' object is not iterable
>>> gale_church.align_blocks([500, 271], [500])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nltk/translate/gale_church.py", line 168, in align_blocks
    return trace(backlinks, source_sents, target_sents)
  File "nltk/translate/gale_church.py", line 84, in trace
    s, t = backlinks[pos]
TypeError: 'NoneType' object is not iterable
>>> gale_church.align_blocks([500, 265], [500])
[(0, 0), (1, 0)]
```

**Comment by alvations** [comment]
This is indeed a quirky bug =)

When trying to [align blocks of sentences](https://github.com/nltk/nltk/blob/develop/nltk/translate/gale_church.py#L119), there's a chance that [none of the sentence pairs meets the minimum distance](https://github.com/nltk/nltk/blob/develop/nltk/translate/gale_church.py#L154) with respect to the parameters set at https://github.com/nltk/nltk/blob/develop/nltk/translate/gale_church.py#L61. And that will cause [`min_align` to remain as None](https://github.com/nltk/nltk/blob/develop/nltk/translate/gale_church.py#L147) and if all sentence pairs has no possible alignments, the values to all `backlinks` will be None, thus the error.

To resolve this we could ~~either go the LBYL way and~~ change how `trace()` work:

``` python

def trace(backlinks, source, target):
    links = []
    pos = (len(source), len(target))

    while pos != (0, 0) and all(backlinks.values()) != None:
        s, t = backlinks[pos]
        for i in range(s):
            for j in range(t):
                links.append((pos[0] - i - 1, pos[1] - j - 1))
        pos = (pos[0] - s, pos[1] - t)

    return links[::-1]
```

~~or the EAFP way~~ (the EAFP won't work in a while loop, it'll go into infinite loops):

``` python
def trace(backlinks, source, target):
    links = []
    pos = (len(source), len(target))

    while pos != (0, 0):
        try:
            s, t = backlinks[pos]
        except TypeError:
            continue
        for i in range(s):
            for j in range(t):
                links.append((pos[0] - i - 1, pos[1] - j - 1))
        pos = (pos[0] - s, pos[1] - t)

    return links[::-1]
```

**Comment by alvations** [comment]
After referencing my old code, I realize that NLTK is still saving the traces differently from @vchahun's implementation, https://github.com/alvations/NTU-MC/blob/master/ntumc/toolkit/gale_church.py#L115

**Comment by alvations** [comment]
The issue seems to be a problem where the `backlinks[pos]` return a `None` type at `trace()`, when the `align_blocks()` didn't assign an align type to the pair of sentence blocks. That usually happens when you have non-monotonic sentence/paragraph pairs (see [slide 3 in gacha's technical manual](https://dl.dropboxusercontent.com/u/45771499/GaChalign.pdf)).

To overcome it, we would have to reduce the pointer value when the `backlinks[pos]` is a None and at every loop we have to re-validate that alignment pairs are above 0th position. 

With the #1366 patch:

``` python
# Previously breaking examples:
>>> from nltk.translate import gale_church
>>> gale_church.align_blocks([10] * 20, [200, 400])
[]
>>> gale_church.align_blocks([500, 299], [500])
[(1, 0)]
>>> gale_church.align_blocks([500, 270], [500])
[(1, 0)]
>>> gale_church.align_blocks([500, 265], [500])
[(0, 0), (1, 0)]

# Previously working examples:
>>> gale_church.align_blocks([5,5,5], [7,7,7])
[(0, 0), (1, 1), (2, 2)]
>>> gale_church.align_blocks([10,] * 20, [5])
[(18, 0), (19, 0)]
>>> gale_church.align_blocks([10,] * 20, [5, 10])
[(16, 0), (17, 0), (18, 1), (19, 1)]
```

The weird situation when gale-church algorithm thinks that block of length 265 aligns with 500 which 270 is a flaw of the algorithm itself (I think), that's because gale-church is agnostic to any linguistic information of the sentences it's aligning and purely determine on meta-linguistic length feature and the  "language independent" priors for alignment.
