### ISSUE TITLE
Receiving GetURLError

### ISSUE THREAD

**Issue by Moon-Raven** [nltk/nltk#1326]
When calling function nltk.pos_tag, I get the following error in nltk-3.2:

```
Traceback (most recent call last):
  File "nltk-tests.py", line 22, in <module>
    tagged = nltk.pos_tag(tokens)
  File "C:\Users\Vukan\AppData\Local\Programs\Python\Python35\lib\site-packages\nltk\tag\__init__.py", line 110, in pos_tag
    tagger = PerceptronTagger()
  File "C:\Users\Vukan\AppData\Local\Programs\Python\Python35\lib\site-packages\nltk\tag\perceptron.py", line 141, in __init__
    self.load(AP_MODEL_LOC)
  File "C:\Users\Vukan\AppData\Local\Programs\Python\Python35\lib\site-packages\nltk\tag\perceptron.py", line 209, in load
    self.model.weights, self.tagdict, self.classes = load(loc)
  File "C:\Users\Vukan\AppData\Local\Programs\Python\Python35\lib\site-packages\nltk\data.py", line 801, in load
    opened_resource = _open(resource_url)
  File "C:\Users\Vukan\AppData\Local\Programs\Python\Python35\lib\site-packages\nltk\data.py", line 924, in _open
    return urlopen(resource_url)
  File "C:\Users\Vukan\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Vukan\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 465, in open
    response = self._open(req, data)
  File "C:\Users\Vukan\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 488, in _open
    'unknown_open', req)
  File "C:\Users\Vukan\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "C:\Users\Vukan\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 1310, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: c>
```

The error does not happen in nltk-3.1. I am using Windows 7, python 3.5.1

**Comment by tastyminerals** [comment]
This is a bug in `perceptron.py`.
Here is the [solution](http://stackoverflow.com/questions/35836907/nltk-unable-to-nltk-pos-tag).
You can also downgrade to `3.1.0`.

**Comment by alvations** [comment]
This issue has been resolved. Please upgrade your NLTK, `pip install -U nltk`, take a look at the start of gist for tried/tested installation instructions for Windows: https://gist.github.com/alvations/0ed8641d7d2e1941b9f9
