### ISSUE TITLE
Perceptron data loading issue with UNC paths

### ISSUE THREAD

**Issue by mikejewell** [nltk/nltk#1400]
Hi,

We're storing our data under an UNC path (i.e. our NLTK_DATA is on the lines of \\mypath.com\nltkdata), and this causes the following error on data loading for tag/perceptron.py. All other data loading seems to be fine (e.g. chunk/__init__.py has no problems).

We've been tweaking perceptron.py a little to debug, so the line numbers are a little off. We're currently using this alteration which is working:

`AP_MODEL_LOC = 'taggers/averaged_perceptron_tagger/'+PICKLE`

Traceback as follows:

```
Traceback (most recent call last):
 File ".\test_parser.py", line 20, in <module>
   parsed = parser.parse(data['text'])
 File "C:\Users\mike\Project\parser.py", line 50, in parse
   tagged_sentences = [nltk.pos_tag(sentence) for sentence in tokenized_sentences]
 File "C:\Users\mike\Project\lib\site-packages\nltk\tag\__init__.py", line 110, in pos_tag
   tagger = PerceptronTagger()
 File "C:\Users\mike\Project\lib\site-packages\nltk\tag\perceptron.py", line 143, in __init__
   self.load(AP_MODEL_LOC)
 File "C:\Users\mike\Project\lib\site-packages\nltk\tag\perceptron.py", line 211, in load
   self.model.weights, self.tagdict, self.classes = load(loc)
 File "C:\Users\mike\Project\lib\site-packages\nltk\data.py", line 800, in load
   opened_resource = _open(resource_url)
 File "C:\Users\mike\Project\lib\site-packages\nltk\data.py", line 921, in _open
   return find(path_, ['']).open()
 File "C:\Users\mike\Project\lib\site-packages\nltk\data.py", line 640, in find
   raise LookupError(resource_not_found)
LookupError:
**********************************************************************
 Resource u'/C:/Users/mike/Project/mypath.com/nltkdata/taggers/averaged
 _perceptron_tagger/averaged_perceptron_tagger.pickle' not found.
 Please use the NLTK Downloader to obtain the resource:  >>>
 nltk.download()
 Searched in:
   - u''
**********************************************************************
```

Cheers,
Mike

**Comment by alvations** [comment]
@mikejewell sorry for letting the issue slip through. Are you still having the same problems in the latest version of NLTK?
