### ISSUE TITLE
Issues with MaltParser interface with Glue Semantics

### ISSUE THREAD

**Issue by nprad** [nltk/nltk#1406]
```
>>> from nltk.tag import RegexpTagger
>>> tagger = RegexpTagger(
...     [('^(chases|runs)$', 'VB'),
...      ('^(a)$', 'ex_quant'),
...      ('^(every)$', 'univ_quant'),
...      ('^(dog|boy)$', 'NN'),
...      ('^(He)$', 'PRP')
... ])
>>> rc = nltk.DrtGlueReadingCommand(depparser=nltk.MaltParser(tagger=tagger))
>>> dt = nltk.DiscourseTester(['Every dog chases a boy', 'He runs'], rc)
>>> dt.readings()
```

Even when you specific the malt parser directory, there are more errors. It's inconsistent with the book.

**Comment by alvations** [comment]
@nprad, the maltparser API in NLTK has been revamped last year such that it's less buggy than the interface presented in the book. 

It's now essential to [include the `parser_dirname` directory parameter when instantiating MaltParser](https://github.com/nltk/nltk/blob/develop/nltk/parse/malt.py#L110)

Here's an example of how to get the current MaltParser interface to work: http://stackoverflow.com/questions/13207394/step-by-step-to-getting-malt-parser-in-nltk-to-work

After **setting the environmental variables**, you would have to instantiate the `MaltParser` object with the  `parser_dirname` and the model name `model_filename`:

``` python
>>> from nltk.parse.malt import MaltParser
>>> mp = MaltParser('maltparser-1.8.1', 'engmalt.linear-1.7.mco')
>>> mp.parse_one('I shot an elephant in my pajamas .'.split()).tree()
```

The current MaltParser interface comes with a default regex tagger: https://github.com/nltk/nltk/blob/develop/nltk/parse/malt.py#L29

But to override the tagger:

``` python
>>> from nltk.parse.malt import MaltParser
>>> mp = MaltParser('maltparser-1.8.1', 'engmalt.linear-1.7.mco', tagger=tagger)
>>> mp.parse_one('I shot an elephant in my pajamas .'.split()).tree()
```

Most probably, changing your code to such should work **after you have set the environmental variables**:

``` python
nltk.DrtGlueReadingCommand(depparser=nltk.parser.malt.MaltParser(('maltparser-1.8.1', 'engmalt.linear-1.7.mco', tagger=tagger))
```

But the cleaner idiom with namespaces would look something like this:

``` python
from nltk.parse.malt import MaltParser 
from nltk.inference.discourse import DrtGlueReadingCommand
from nltk.tag import RegexpTagger
tagger = RegexpTagger(
     [('^(chases|runs)$', 'VB'),
      ('^(a)$', 'ex_quant'),
      ('^(every)$', 'univ_quant'),
      ('^(dog|boy)$', 'NN'),
      ('^(He)$', 'PRP')
])
# Instantiate the object first.
mparser = MaltParser(('maltparser-1.8.1', 'engmalt.linear-1.7.mco', tagger=tagger)
# Then feed it to the DRT command.
rc = DrtGlueReadingCommand(depparser=mparser)
```

Without setting the environmental variable, the current MaltParser API should be able to accommodate the full path to the parser's main directory and the model too, e.g.:

``` python
>>> from nltk.parse.malt import MaltParser
>>> from nltk.tag import RegexpTagger
>>> tagger = RegexpTagger(
...     [('^(chases|runs)$', 'VB'),
...      ('^(a)$', 'ex_quant'),
...      ('^(every)$', 'univ_quant'),
...      ('^(dog|boy)$', 'NN'),
...      ('^(He)$', 'PRP')
... ])
>>> path_to_maltparser_main_dir = '/home/yourusername/maltparser-1.8.1'
>>> path_to_maltparser_model = '/home/yourusername/engmalt.linear-1.7.mco'
>>> mp = MaltParser( parser_dirname=path_to_maltparser_main_dir, model_filename=path_to_maltparser_model, tagger=tagger)
>>> mp.parse_one('I shot an elephant in my pajamas .'.split()).tree()
```

**Comment by nprad** [comment]
I am still getting an error on the MaltParser end, even when trying to run your code.

```
Traceback (most recent call last):
  File "inference.py", line 19, in <module>
    mp.parse_one(sent1).tree()
  File "/Library/Python/2.7/site-packages/nltk/parse/api.py", line 66, in parse_one
    return next(self.parse(sent, *args, **kwargs), None)
  File "/Library/Python/2.7/site-packages/nltk/parse/api.py", line 45, in parse
    return next(self.parse_sents([sent], *args, **kwargs))
  File "/Library/Python/2.7/site-packages/nltk/parse/malt.py", line 164, in parse_tagged_sents
    for line in taggedsents_to_conll(sentences):
  File "/Library/Python/2.7/site-packages/nltk/parse/util.py", line 138, in taggedsents_to_conll
    for sentence in sentences:
  File "/Library/Python/2.7/site-packages/nltk/parse/malt.py", line 206, in <genexpr>
    tagged_sentences = (self.tagger(sentence) for sentence in sentences)
TypeError: 'RegexpTagger' object is not callable
```

**Comment by alvations** [comment]
Must you use your own `RegexpTagger`? 

If not, try:

``` python
from nltk.parse.malt import MaltParser 
from nltk.inference.discourse import DrtGlueReadingCommand
# Instantiate the object first.
mparser = MaltParser(('maltparser-1.8.1', 'engmalt.linear-1.7.mco')
# Then feed it to the DRT command.
rc = DrtGlueReadingCommand(depparser=mparser)
```

If so, then:

``` python
from nltk.parse.malt import MaltParser 
from nltk.inference.discourse import DrtGlueReadingCommand
from nltk.tag import RegexpTagger
tagger = RegexpTagger(
     [('^(chases|runs)$', 'VB'),
      ('^(a)$', 'ex_quant'),
      ('^(every)$', 'univ_quant'),
      ('^(dog|boy)$', 'NN'),
      ('^(He)$', 'PRP')
])
# Instantiate the object first.
mparser = MaltParser(('maltparser-1.8.1', 'engmalt.linear-1.7.mco', tagger=tagger.tag)
# Then feed it to the DRT command.
rc = DrtGlueReadingCommand(depparser=mparser)
```

Or when using the default NLTK `pos_tag`:

``` python
from nltk import pos_tag
from nltk.parse.malt import MaltParser 
from nltk.inference.discourse import DrtGlueReadingCommand
# Instantiate the object first.
mparser = MaltParser(('maltparser-1.8.1', 'engmalt.linear-1.7.mco', tagger=pos_tag)
# Then feed it to the DRT command.
rc = DrtGlueReadingCommand(depparser=mparser)
```

**Comment by nprad** [comment]
This got me further down, but I'm still getting errors. I'm just using `pos_tag` and trying to run the following code.

``` python
import nltk
import os

sent1 = nltk.word_tokenize('Every dog chases a boy')
sent2 = nltk.word_tokenize('He runs')

mp = nltk.MaltParser(parser_dirname=path_to_maltparser_main_dir, model_filename=path_to_maltparser_model, tagger = nltk.pos_tag)
rc = nltk.DrtGlueReadingCommand(depparser=mp)
dt = nltk.DiscourseTester([sent1, sent2], rc)
dt.readings()

```

But I get this error.

```
Traceback (most recent call last):
  File "inference.py", line 20, in <module>
    dt.readings()
  File "/Library/Python/2.7/site-packages/nltk/inference/discourse.py", line 350, in readings
    self._construct_readings()
  File "/Library/Python/2.7/site-packages/nltk/inference/discourse.py", line 281, in _construct_readings
    readings = self._get_readings(sentence)
  File "/Library/Python/2.7/site-packages/nltk/inference/discourse.py", line 271, in _get_readings
    return self._reading_command.parse_to_readings(sentence)
  File "/Library/Python/2.7/site-packages/nltk/inference/discourse.py", line 145, in parse_to_readings
    return self._glue.parse_to_meaning(sentence)
  File "/Library/Python/2.7/site-packages/nltk/sem/glue.py", line 461, in parse_to_meaning
    for agenda in self.parse_to_compiled(sentence):
  File "/Library/Python/2.7/site-packages/nltk/sem/glue.py", line 543, in parse_to_compiled
    gfls = [self.depgraph_to_glue(dg) for dg in self.dep_parse(sentence)]
  File "/Library/Python/2.7/site-packages/nltk/sem/glue.py", line 564, in depgraph_to_glue
    return self.get_glue_dict().to_glueformula_list(depgraph)
  File "/Library/Python/2.7/site-packages/nltk/sem/glue.py", line 241, in to_glueformula_list
    return self.to_glueformula_list(depgraph, root, Counter(), verbose)
  File "/Library/Python/2.7/site-packages/nltk/sem/glue.py", line 243, in to_glueformula_list
    glueformulas = self.lookup(node, depgraph, counter)
  File "/Library/Python/2.7/site-packages/nltk/sem/glue.py", line 265, in lookup
    if not len(lookup):
TypeError: object of type 'NoneType' has no len()
```

**Comment by alvations** [comment]
Now that has to do with how DRT code is interfacing MaltParser's output. Possibly @dhgarrette would know better about the `nltk.sem.glue` module.

BTW, for sanity check, what is your output for:

``` python
mp = nltk.MaltParser(parser_dirname=path_to_maltparser_main_dir, model_filename=path_to_maltparser_model, tagger = nltk.pos_tag)
mp.parse_one('I shot an elephant in my pajamas .'.split()).tree()
```

**Comment by nprad** [comment]
```
(shot I (elephant an) (in (pajamas my)) .)
```

Here is my output. Thanks for all the help.

**Comment by dhgarrette** [comment]
After looking into it a bit, I think the issue must be that the newer version of MaltParser is using different dependency labels from the version against which the glue.py code was developed (which was <=2008).  For example, the glue.semtype grammar says that a transitive verb should have arguments 'subj' and 'obj', but MaltParser is returning 'nsubj' and 'dobj', which is why it's failing.  

Furthermore, using a standard pos tagger isn't going to work either because glue.py expects some more semantically-oriented tags like 'ex_quant' and 'univ_quant', which nltk.pos_tag isn't going to give you, but that tiny RegexTagger would.

If you feel up to it, you could try updating things to match the new version of MaltParser and do a pull request.

**Comment by michalstepniewski** [comment]
so what can I do to make it work? use an older version of malt parser or find some newer version of nltk?
