### ISSUE TITLE
Test Suite Errors and SSL Certificate Issues

### ISSUE THREAD

**Issue by jmwoloso** [nltk/nltk#1425]
Hello,

Linux: Mint 17.3
NLTK: 3.2.1
Python: 3.5 (and 3.4)

When I try and run <code>nltk.download()</code>, I get an error stating `SSL: CERTIFICATE_VERIFY_FAILED`

Also, when I attempt to run the `nosetests`, none of the files that should be in `nltk/test/unit/files/` are there and some tests fail with the following traceback:

```
jwolosonovich@LINUX115XFC2 ~/Desktop $ nosetests -v nltk
/usr/local/python3.5i/lib/python3.5/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/twitter/__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn("The twython library has not been installed. "
test_full_matches (nltk.test.unit.translate.test_bleu.TestBLEU) ... ok
Examples from the original BLEU paper ... ok
test_partial_matches_hypothesis_longer_than_reference (nltk.test.unit.translate.test_bleu.TestBLEU) ... ok
test_zero_matches (nltk.test.unit.translate.test_bleu.TestBLEU) ... ok
test_brevity_penalty (nltk.test.unit.translate.test_bleu.TestBLEUFringeCases) ... SKIP: Skipping fringe cases for BLEU.
test_case_where_n_is_bigger_than_hypothesis_length (nltk.test.unit.translate.test_bleu.TestBLEUFringeCases) ... SKIP: Skipping fringe cases for BLEU.
test_empty_hypothesis (nltk.test.unit.translate.test_bleu.TestBLEUFringeCases) ... SKIP: Skipping fringe cases for BLEU.
test_empty_references (nltk.test.unit.translate.test_bleu.TestBLEUFringeCases) ... SKIP: Skipping fringe cases for BLEU.
test_prob_t_a_given_s (nltk.test.unit.translate.test_ibm1.TestIBMModel1) ... ok
test_set_uniform_translation_probabilities (nltk.test.unit.translate.test_ibm1.TestIBMModel1) ... ok
test_set_uniform_translation_probabilities_of_non_domain_values (nltk.test.unit.translate.test_ibm1.TestIBMModel1) ... ok
test_prob_t_a_given_s (nltk.test.unit.translate.test_ibm2.TestIBMModel2) ... ok
test_set_uniform_alignment_probabilities (nltk.test.unit.translate.test_ibm2.TestIBMModel2) ... ok
test_set_uniform_alignment_probabilities_of_non_domain_values (nltk.test.unit.translate.test_ibm2.TestIBMModel2) ... ok
test_prob_t_a_given_s (nltk.test.unit.translate.test_ibm3.TestIBMModel3) ... ok
test_set_uniform_distortion_probabilities (nltk.test.unit.translate.test_ibm3.TestIBMModel3) ... ok
test_set_uniform_distortion_probabilities_of_non_domain_values (nltk.test.unit.translate.test_ibm3.TestIBMModel3) ... ok
test_prob_t_a_given_s (nltk.test.unit.translate.test_ibm4.TestIBMModel4) ... ok
test_set_uniform_distortion_probabilities_of_max_displacements (nltk.test.unit.translate.test_ibm4.TestIBMModel4) ... ok
test_set_uniform_distortion_probabilities_of_non_domain_values (nltk.test.unit.translate.test_ibm4.TestIBMModel4) ... ok
test_prob_t_a_given_s (nltk.test.unit.translate.test_ibm5.TestIBMModel5) ... ok
test_prune (nltk.test.unit.translate.test_ibm5.TestIBMModel5) ... ok
test_set_uniform_vacancy_probabilities_of_max_displacements (nltk.test.unit.translate.test_ibm5.TestIBMModel5) ... ok
test_set_uniform_vacancy_probabilities_of_non_domain_values (nltk.test.unit.translate.test_ibm5.TestIBMModel5) ... ok
test_best_model2_alignment (nltk.test.unit.translate.test_ibm_model.TestIBMModel) ... ok
test_best_model2_alignment_does_not_change_pegged_alignment (nltk.test.unit.translate.test_ibm_model.TestIBMModel) ... ok
test_best_model2_alignment_handles_empty_src_sentence (nltk.test.unit.translate.test_ibm_model.TestIBMModel) ... ok
test_best_model2_alignment_handles_empty_trg_sentence (nltk.test.unit.translate.test_ibm_model.TestIBMModel) ... ok
test_best_model2_alignment_handles_fertile_words (nltk.test.unit.translate.test_ibm_model.TestIBMModel) ... ok
test_hillclimb (nltk.test.unit.translate.test_ibm_model.TestIBMModel) ... ok
test_neighboring_finds_neighbor_alignments (nltk.test.unit.translate.test_ibm_model.TestIBMModel) ... ok
test_neighboring_returns_neighbors_with_pegged_alignment (nltk.test.unit.translate.test_ibm_model.TestIBMModel) ... ok
test_neighboring_sets_neighbor_alignment_info (nltk.test.unit.translate.test_ibm_model.TestIBMModel) ... ok
test_sample (nltk.test.unit.translate.test_ibm_model.TestIBMModel) ... ok
test_vocabularies_are_initialized (nltk.test.unit.translate.test_ibm_model.TestIBMModel) ... ok
test_vocabularies_are_initialized_even_with_empty_corpora (nltk.test.unit.translate.test_ibm_model.TestIBMModel) ... ok
test_total_translated_words (nltk.test.unit.translate.test_stack_decoder.TestHypothesis) ... ok
test_translated_positions (nltk.test.unit.translate.test_stack_decoder.TestHypothesis) ... ok
test_translation_so_far (nltk.test.unit.translate.test_stack_decoder.TestHypothesis) ... ok
test_translation_so_far_for_empty_hypothesis (nltk.test.unit.translate.test_stack_decoder.TestHypothesis) ... ok
test_untranslated_spans (nltk.test.unit.translate.test_stack_decoder.TestHypothesis) ... ok
test_untranslated_spans_for_empty_hypothesis (nltk.test.unit.translate.test_stack_decoder.TestHypothesis) ... ok
test_best_returns_none_when_stack_is_empty (nltk.test.unit.translate.test_stack_decoder.TestStack) ... ok
test_best_returns_the_best_hypothesis (nltk.test.unit.translate.test_stack_decoder.TestStack) ... ok
test_push_bumps_off_worst_hypothesis_when_stack_is_full (nltk.test.unit.translate.test_stack_decoder.TestStack) ... ok
test_push_does_not_add_hypothesis_that_falls_below_beam_threshold (nltk.test.unit.translate.test_stack_decoder.TestStack) ... ok
test_push_removes_hypotheses_that_fall_below_beam_threshold (nltk.test.unit.translate.test_stack_decoder.TestStack) ... ok
test_compute_future_costs (nltk.test.unit.translate.test_stack_decoder.TestStackDecoder) ... ok
test_compute_future_costs_for_phrases_not_in_phrase_table (nltk.test.unit.translate.test_stack_decoder.TestStackDecoder) ... ok
test_distortion_score (nltk.test.unit.translate.test_stack_decoder.TestStackDecoder) ... ok
test_distortion_score_of_first_expansion (nltk.test.unit.translate.test_stack_decoder.TestStackDecoder) ... ok
test_find_all_src_phrases (nltk.test.unit.translate.test_stack_decoder.TestStackDecoder) ... ok
test_future_score (nltk.test.unit.translate.test_stack_decoder.TestStackDecoder) ... ok
test_valid_phrases (nltk.test.unit.translate.test_stack_decoder.TestStackDecoder) ... ok
SKIP: test_2x_compat is for testing nltk.compat under Python 2.x
nltk.test.unit.test_classify.test_megam ... SKIP: 

===========================================================================
NLTK was unable to find the megam file!
Use software specific configuration paramaters or set the MEGAM environment variable.

  For more information on megam, see:
    <http://www.umiacs.umd.edu/~hal/megam/index.html>
===========================================================================
nltk.test.unit.test_classify.test_tadm ... SKIP: 

===========================================================================
NLTK was unable to find the tadm file!
Use software specific configuration paramaters or set the TADM environment variable.

  For more information on tadm, see:
    <http://tadm.sf.net>
===========================================================================
test_bigram2 (nltk.test.unit.test_collocations.TestBigram) ... ok
test_bigram3 (nltk.test.unit.test_collocations.TestBigram) ... ok
test_bigram5 (nltk.test.unit.test_collocations.TestBigram) ... ok
test_catalan (nltk.test.unit.test_corpora.TestCess) ... ok
test_esp (nltk.test.unit.test_corpora.TestCess) ... ok
test_parsed_sents (nltk.test.unit.test_corpora.TestCoNLL2007) ... ok
test_sents (nltk.test.unit.test_corpora.TestCoNLL2007) ... ok
test_words (nltk.test.unit.test_corpora.TestFloresta) ... ok
test_tagged_words (nltk.test.unit.test_corpora.TestIndian) ... ok
test_words (nltk.test.unit.test_corpora.TestIndian) ... ok
test_categories (nltk.test.unit.test_corpora.TestPTB) ... SKIP: A full installation of the Penn Treebank is not available
test_category_words (nltk.test.unit.test_corpora.TestPTB) ... SKIP: A full installation of the Penn Treebank is not available
test_fileids (nltk.test.unit.test_corpora.TestPTB) ... SKIP: A full installation of the Penn Treebank is not available
test_news_fileids (nltk.test.unit.test_corpora.TestPTB) ... SKIP: A full installation of the Penn Treebank is not available
test_tagged_words (nltk.test.unit.test_corpora.TestPTB) ... SKIP: A full installation of the Penn Treebank is not available
test_words (nltk.test.unit.test_corpora.TestPTB) ... SKIP: A full installation of the Penn Treebank is not available
test_parsed_sents (nltk.test.unit.test_corpora.TestSinicaTreebank) ... ok
test_sents (nltk.test.unit.test_corpora.TestSinicaTreebank) ... ok
test_raw_unicode (nltk.test.unit.test_corpora.TestUdhr) ... ok
test_words (nltk.test.unit.test_corpora.TestUdhr) ... ok
test_correct_length (nltk.test.unit.test_corpus_views.TestCorpusViews) ... ok
test_correct_values (nltk.test.unit.test_corpus_views.TestCorpusViews) ... ok
nltk.test.unit.test_hmm.test_forward_probability ... ok
nltk.test.unit.test_hmm.test_forward_probability2 ... ok
nltk.test.unit.test_hmm.test_backward_probability ... ok
Sanity check that file comparison is not giving false positives. ... ERROR
test_retweet_original_tweet (nltk.test.unit.test_json2csv_corpus.TestJSON2CSV) ... ERROR
test_textoutput (nltk.test.unit.test_json2csv_corpus.TestJSON2CSV) ... ERROR
test_tweet_hashtag (nltk.test.unit.test_json2csv_corpus.TestJSON2CSV) ... ERROR
test_tweet_media (nltk.test.unit.test_json2csv_corpus.TestJSON2CSV) ... ERROR
test_tweet_metadata (nltk.test.unit.test_json2csv_corpus.TestJSON2CSV) ... ERROR
test_tweet_place (nltk.test.unit.test_json2csv_corpus.TestJSON2CSV) ... ERROR
test_tweet_place_boundingbox (nltk.test.unit.test_json2csv_corpus.TestJSON2CSV) ... ERROR
test_tweet_url (nltk.test.unit.test_json2csv_corpus.TestJSON2CSV) ... ERROR
test_tweet_usermention (nltk.test.unit.test_json2csv_corpus.TestJSON2CSV) ... ERROR
test_user_metadata (nltk.test.unit.test_json2csv_corpus.TestJSON2CSV) ... ERROR
test_userurl (nltk.test.unit.test_json2csv_corpus.TestJSON2CSV) ... ERROR
test_simple (nltk.test.unit.test_naivebayes.NaiveBayesClassifierTest) ... ok
nltk.test.unit.test_seekable_unicode_stream_reader.test_reader('\n    This is a test file.\n    It is fairly short.\n    ', 'ascii') ... ok
nltk.test.unit.test_seekable_unicode_stream_reader.test_reader('\n    This is a test file.\n    It is fairly short.\n    ', 'latin1') ... ok
nltk.test.unit.test_seekable_unicode_stream_reader.test_reader('\n    This is a test file.\n    It is fairly short.\n    ', 'greek') ... ok
nltk.test.unit.test_seekable_unicode_stream_reader.test_reader('\n    This is a test file.\n    It is fairly short.\n    ', 'hebrew') ... ok
nltk.test.unit.test_seekable_unicode_stream_reader.test_reader('\n    This is a test file.\n    It is fairly short.\n    ', 'utf-16') ... ok
nltk.test.unit.test_seekable_unicode_stream_reader.test_reader('\n    This is a test file.\n    It is fairly short.\n    ', 'utf-8') ... ok
nltk.test.unit.test_seekable_unicode_stream_reader.test_reader('This file can be encoded with latin1. \x83', 'latin1') ... ok
nltk.test.unit.test_seekable_unicode_stream_reader.test_reader('This file can be encoded with latin1. \x83', 'greek') ... ok
nltk.test.unit.test_seekable_unicode_stream_reader.test_reader('This file can be encoded with latin1. \x83', 'hebrew') ... ok
nltk.test.unit.test_seekable_unicode_stream_reader.test_reader('This file can be encoded with latin1. \x83', 'utf-16') ... ok
nltk.test.unit.test_seekable_unicode_stream_reader.test_reader('This file can be encoded with latin1. \x83', 'utf-8') ... ok
nltk.test.unit.test_seekable_unicode_stream_reader.test_reader("    This is a test file.\n    Here's a blank line:\n\n    And here's some unicode: î ģ ￣\n    ", 'utf-16') ... ok
nltk.test.unit.test_seekable_unicode_stream_reader.test_reader("    This is a test file.\n    Here's a blank line:\n\n    And here's some unicode: î ģ ￣\n    ", 'utf-8') ... ok
nltk.test.unit.test_seekable_unicode_stream_reader.test_reader('    This is a test file.\n    Unicode characters: ó ∢ ㌳䑄 啕\n    ', 'utf-16') ... ok
nltk.test.unit.test_seekable_unicode_stream_reader.test_reader('    This is a test file.\n    Unicode characters: ó ∢ ㌳䑄 啕\n    ', 'utf-8') ... ok
nltk.test.unit.test_seekable_unicode_stream_reader.test_reader_on_large_string('utf-16',) ... ok
nltk.test.unit.test_seekable_unicode_stream_reader.test_reader_on_large_string('utf-8',) ... ok
test_german (nltk.test.unit.test_stem.SnowballTest) ... ok
test_russian (nltk.test.unit.test_stem.SnowballTest) ... ok
test_short_strings_bug (nltk.test.unit.test_stem.SnowballTest) ... ok
test_spanish (nltk.test.unit.test_stem.SnowballTest) ... ok
nltk.test.unit.test_tag.test_basic ... ok
Test error handling of undefined tgrep operators. ... ok
Test that comments are correctly filtered out of tgrep search ... ok
Test the Basic Examples from the TGrep2 manual. ... ok
Test labeled nodes. ... ok
Test that multiple (3 or more) conjunctions of node relations are ... ok
Test that tgrep search strings handles bytes and strs the same ... ok
Test selecting nodes using case insensitive node names. ... ok
Test node name matching with the search_leaves flag set to False. ... ok
Test that the tgrep print operator ' is properly ignored. ... ok
Test selecting nodes using quoted node names. ... ok
Test regex matching on nodes. ... ok
Test regex matching on nodes. ... ok
Test a simple use of tgrep for finding nodes matching a given ... ok
Test matching on nodes based on NLTK tree position. ... ok
Test matching nodes based on precedence relations. ... ok
Test matching sister nodes in a tree. ... ok
Test that tokenization handles bytes and strs the same way. ... ok
Test tokenization of the TGrep2 manual example patterns. ... ok
Test tokenization of basic link types. ... ok
Test tokenization of macro definitions. ... ok
Test tokenization of labeled nodes. ... ok
Test tokenization of node names. ... ok
Test tokenization of quoting. ... ok
Test tokenization of segmented patterns. ... ok
Simple test of tokenization. ... ok
Test that semicolons at the end of a tgrep2 search string won't ... ok
Test defining and using tgrep2 macros. ... ok
Test matching nodes based on dominance relations. ... ok
Test matching nodes based on their index in their parent node. ... ok
Test TweetTokenizer using words with special and accented characters. ... ok
Failure: SkipTest (The twython library has not been installed.) ... SKIP: The twython library has not been installed.

======================================================================
ERROR: Sanity check that file comparison is not giving false positives.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/test_json2csv_corpus.py", line 182, in test_file_is_wrong
    self.assertFalse(are_files_identical(outfn, ref_fn), msg=self.msg)
  File "/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/test_json2csv_corpus.py", line 29, in are_files_identical
    with open(filename2, "rb") as fileB:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/files/tweets.20150430-223406.retweet.csv.ref'

======================================================================
ERROR: test_retweet_original_tweet (nltk.test.unit.test_json2csv_corpus.TestJSON2CSV)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/test_json2csv_corpus.py", line 171, in test_retweet_original_tweet
    self.assertTrue(are_files_identical(outfn, ref_fn), msg=self.msg)
  File "/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/test_json2csv_corpus.py", line 29, in are_files_identical
    with open(filename2, "rb") as fileB:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/files/tweets.20150430-223406.retweet.csv.ref'

======================================================================
ERROR: test_textoutput (nltk.test.unit.test_json2csv_corpus.TestJSON2CSV)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/test_json2csv_corpus.py", line 61, in test_textoutput
    self.assertTrue(are_files_identical(outfn, ref_fn), msg=self.msg)
  File "/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/test_json2csv_corpus.py", line 29, in are_files_identical
    with open(filename2, "rb") as fileB:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/files/tweets.20150430-223406.text.csv.ref'

======================================================================
ERROR: test_tweet_hashtag (nltk.test.unit.test_json2csv_corpus.TestJSON2CSV)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/test_json2csv_corpus.py", line 93, in test_tweet_hashtag
    self.assertTrue(are_files_identical(outfn, ref_fn), msg=self.msg)
  File "/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/test_json2csv_corpus.py", line 29, in are_files_identical
    with open(filename2, "rb") as fileB:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/files/tweets.20150430-223406.hashtag.csv.ref'

======================================================================
ERROR: test_tweet_media (nltk.test.unit.test_json2csv_corpus.TestJSON2CSV)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/test_json2csv_corpus.py", line 114, in test_tweet_media
    self.assertTrue(are_files_identical(outfn, ref_fn), msg=self.msg)
  File "/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/test_json2csv_corpus.py", line 29, in are_files_identical
    with open(filename2, "rb") as fileB:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/files/tweets.20150430-223406.media.csv.ref'

======================================================================
ERROR: test_tweet_metadata (nltk.test.unit.test_json2csv_corpus.TestJSON2CSV)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/test_json2csv_corpus.py", line 73, in test_tweet_metadata
    self.assertTrue(are_files_identical(outfn, ref_fn), msg=self.msg)
  File "/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/test_json2csv_corpus.py", line 29, in are_files_identical
    with open(filename2, "rb") as fileB:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/files/tweets.20150430-223406.tweet.csv.ref'

======================================================================
ERROR: test_tweet_place (nltk.test.unit.test_json2csv_corpus.TestJSON2CSV)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/test_json2csv_corpus.py", line 147, in test_tweet_place
    self.assertTrue(are_files_identical(outfn, ref_fn), msg=self.msg)
  File "/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/test_json2csv_corpus.py", line 29, in are_files_identical
    with open(filename2, "rb") as fileB:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/files/tweets.20150430-223406.place.csv.ref'

======================================================================
ERROR: test_tweet_place_boundingbox (nltk.test.unit.test_json2csv_corpus.TestJSON2CSV)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/test_json2csv_corpus.py", line 158, in test_tweet_place_boundingbox
    self.assertTrue(are_files_identical(outfn, ref_fn), msg=self.msg)
  File "/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/test_json2csv_corpus.py", line 29, in are_files_identical
    with open(filename2, "rb") as fileB:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/files/tweets.20150430-223406.placeboundingbox.csv.ref'

======================================================================
ERROR: test_tweet_url (nltk.test.unit.test_json2csv_corpus.TestJSON2CSV)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/test_json2csv_corpus.py", line 125, in test_tweet_url
    self.assertTrue(are_files_identical(outfn, ref_fn), msg=self.msg)
  File "/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/test_json2csv_corpus.py", line 29, in are_files_identical
    with open(filename2, "rb") as fileB:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/files/tweets.20150430-223406.url.csv.ref'

======================================================================
ERROR: test_tweet_usermention (nltk.test.unit.test_json2csv_corpus.TestJSON2CSV)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/test_json2csv_corpus.py", line 103, in test_tweet_usermention
    self.assertTrue(are_files_identical(outfn, ref_fn), msg=self.msg)
  File "/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/test_json2csv_corpus.py", line 29, in are_files_identical
    with open(filename2, "rb") as fileB:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/files/tweets.20150430-223406.usermention.csv.ref'

======================================================================
ERROR: test_user_metadata (nltk.test.unit.test_json2csv_corpus.TestJSON2CSV)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/test_json2csv_corpus.py", line 83, in test_user_metadata
    self.assertTrue(are_files_identical(outfn, ref_fn), msg=self.msg)
  File "/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/test_json2csv_corpus.py", line 29, in are_files_identical
    with open(filename2, "rb") as fileB:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/files/tweets.20150430-223406.user.csv.ref'

======================================================================
ERROR: test_userurl (nltk.test.unit.test_json2csv_corpus.TestJSON2CSV)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/test_json2csv_corpus.py", line 136, in test_userurl
    self.assertTrue(are_files_identical(outfn, ref_fn), msg=self.msg)
  File "/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/test_json2csv_corpus.py", line 29, in are_files_identical
    with open(filename2, "rb") as fileB:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jwolosonovich/.virtualenvs/ztrip35i/lib/python3.5/site-packages/nltk/test/unit/files/tweets.20150430-223406.userurl.csv.ref'

----------------------------------------------------------------------
Ran 147 tests in 5.503s

FAILED (SKIP=14, errors=12)
```

This has always worked flawlessly in the past, so I'm thinking it is a system issue, but I'm not sure where to start.

**Comment by jmwoloso** [comment]
Update: After a restart the SSL error ceased. Now just need to figure out why the test files aren't where nose expects them to be...

**Comment by stevenbird** [comment]
@jmwoloso: is this still unresolved?

**Comment by jmwoloso** [comment]
Yes, still unresolved.

**Comment by alvations** [comment]
@jmwoloso after upgrading `nltk`, is the SSL issue resolved?

```
pip3 install -U nltk
```

**Comment by carrickdb** [comment]
Not for me. I'm having the same SSL issue for Python 3.6. The downloader works for me for Python 2.7, however.

I restarted my computer and also upgraded nltk as you suggested. I'm on OSX 10.13.3, using python 3.6. I get the following errors.
![screen shot 2018-03-09 at 6 28 35 pm](https://user-images.githubusercontent.com/7660304/37237429-ed31c1e0-23c7-11e8-94f5-a19653381d3d.png)
![screen shot 2018-03-09 at 6 28 46 pm](https://user-images.githubusercontent.com/7660304/37237432-f047503e-23c7-11e8-99b0-b2e99c09c5b5.png)

**Comment by alvations** [comment]
@carrickdb your issue is different from the original issue. Yours is the Mac issue raised previously.

Please see https://github.com/nltk/nltk/issues/1961#issuecomment-367207040

In the terminal

```
/Applications/Python 3.6/Install Certificates.command
```

**Comment by carrickdb** [comment]
Oh. Thank you.

**Comment by anseljh** [comment]
Here's a variant of this problem. Using a Homebrew-installed Python 3.6, the `Install Certificates.command` script does not exist anywhere. How does one fix this then?

More detailed writeup here: https://stackoverflow.com/questions/52448995/overcome-ssl-error-while-downloading-nltk-data-but-inside-a-virtual-environment
