### ISSUE TITLE
Java issues in using StanfordParser

### ISSUE THREAD

**Issue by ravisekharr** [nltk/nltk#1443]
Usage in program:

from nltk.parse.stanford import StanfordParser
# Initialize the parser

path_to_jar = project_path+'Parsers/sfcn/stanford-corenlp-3.5.2.jar'
path_to_models_jar = project_path+'Parsers/sfcn/stanford-corenlp-3.5.2-models.jar'
parser = StanfordParser(path_to_jar=path_to_jar, path_to_models_jar=path_to_models_jar)
message="This is a test message"
parse = parser.raw_parse(message)

I get the following error when I am using StanfordParser:

Error1:

Exception in thread "main" java.lang.UnsupportedClassVersionError: edu/stanford/nlp/parser/lexparser/LexicalizedParser : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
##     at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

Error 2:
File "/usr/local/lib/python2.7/dist-packages/nltk/parse/stanford.py", line 132, in raw_parse
    return next(self.raw_parse_sents([sentence], verbose))
  File "/usr/local/lib/python2.7/dist-packages/nltk/parse/stanford.py", line 150, in raw_parse_sents
    return self._parse_trees_output(self._execute(cmd, '\n'.join(sentences), verbose))
  File "/usr/local/lib/python2.7/dist-packages/nltk/parse/stanford.py", line 216, in _execute
    stdout=PIPE, stderr=PIPE)
  File "/usr/local/lib/python2.7/dist-packages/nltk/internals.py", line 134, in java
    raise OSError('Java command failed : ' + str(cmd))
OSError: Java command failed : [u'/usr/bin/java', u'-mx1000m', '-cp', '/home/ravisekhar/DS/Car diagnosis/Parsers/sfcn/stanford-corenlp-3.5.2-models.jar:/home/ravisekhar/DS/Car diagnosis/Parsers/sfcn/stanford-corenlp-3.5.2.jar:/home/ravisekhar/DS/Car diagnosis/Parsers/sfcn/stanford-parser-3.5.2-sources.jar:/home/ravisekhar/DS/Car diagnosis/Parsers/sfcn/stanford-parser-3.5.2-javadoc.jar:/home/ravisekhar/DS/Car diagnosis/Parsers/sfcn/ejml-0.23.jar:/home/ravisekhar/DS/Car diagnosis/Parsers/sfcn/stanford-corenlp-3.5.2-models.jar:/home/ravisekhar/DS/Car diagnosis/Parsers/sfcn/backup/stanford-corenlp-3.5.2.jar:/home/ravisekhar/DS/Car diagnosis/Parsers/sfcn/backup/stanford-corenlp-3.5.2-models.jar', u'edu.stanford.nlp.parser.lexparser.LexicalizedParser', u'-model', u'edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz', u'-sentences', u'newline', u'-outputFormat', u'penn', u'-encoding', u'utf8', '/tmp/tmpRnLFOZ']

**Comment by stevenbird** [comment]
Cf https://github.com/nltk/nltk/pull/1249

**Comment by stevenbird** [comment]
This should be resolved in our new interface to the Stanford Tools. If not, please reopen.
