### ISSUE TITLE
nltk.cluster.gaac demo error

### ISSUE THREAD

**Issue by yzmyyff** [nltk/nltk#1445]
I ran this method under python3, but it throws following exception:

``` python
>>> import nltk.cluster.gaac
>>> nltk.cluster.gaac.demo()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/nltk/cluster/gaac.py", line 150, in demo
    clusters = clusterer.cluster(vectors, True)
  File "/usr/local/lib/python3.5/dist-packages/nltk/cluster/gaac.py", line 41, in cluster
    return VectorSpaceClusterer.cluster(self, vectors, assign_clusters, trace)
  File "/usr/local/lib/python3.5/dist-packages/nltk/cluster/util.py", line 57, in cluster
    self.cluster_vectorspace(vectors, trace)
  File "/usr/local/lib/python3.5/dist-packages/nltk/cluster/gaac.py", line 79, in cluster_vectorspace
    self.update_clusters(self._num_clusters)
  File "/usr/local/lib/python3.5/dist-packages/nltk/cluster/gaac.py", line 99, in update_clusters
    clusters = self._dendrogram.groups(num_clusters)
  File "/usr/local/lib/python3.5/dist-packages/nltk/cluster/util.py", line 212, in groups
    return root.groups(n)
  File "/usr/local/lib/python3.5/dist-packages/nltk/cluster/util.py", line 160, in groups
    queue.sort()
TypeError: unorderable types: _DendrogramNode() < _DendrogramNode()
```

**Comment by rsnape** [comment]
I believe @alvations is looking at a very similar issue based on a stackoverflow answer I wrote and some discussion in the comments there - see http://stackoverflow.com/a/28327086/838992 and the discussion on an issue I raised at the time https://github.com/nltk/nltk/issues/873.  Hopefully this helps avoid duplication if the issues have the same root cause (they seem to at a glance).
