### ISSUE TITLE
Training on PerceptronTagger with alpino throws TypeError

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#1486]
With `BigramTagger`:

``` python
>>> from nltk.corpus import alpino as alp
>>> from nltk.tag import UnigramTagger, BigramTagger
>>> training_corpus = alp.tagged_sents()
>>> unitagger = UnigramTagger(training_corpus)
>>> bitagger = BigramTagger(training_corpus, backoff=unitagger)
>>> pos_tag = bitagger.tag
>>> sent = 'NLTK is een goeda taal voor NLP'.split()
>>> pos_tag(sent)
[('NLTK', None), ('is', u'verb'), ('een', u'det'), ('goeda', None), ('taal', u'noun'), ('voor', u'prep'), ('NLP', None)]
```

But with `PerceptronTagger`:

``` python
>>> from nltk.tag import PerceptronTagger
>>> from nltk.corpus import alpino as alp
>>> training_corpus = alp.tagged_sents()
>>> tagger = PerceptronTagger(load=False)
>>> tagger.train(training_corpus)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/nltk/tag/perceptron.py", line 194, in train
    random.shuffle(sentences)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 291, in shuffle
    x[i], x[j] = x[j], x[i]
TypeError: 'StreamBackedCorpusView' object does not support item assignment
```

**Comment by alvations** [comment]
It seems like there's a need to materialize the corpus before feeding it to the `PerceptronTagger`, so that the [`shuffle` operation can be possible when using the `train()` function](https://github.com/nltk/nltk/blob/develop/nltk/tag/perceptron.py#L194):

``` python
>>> from nltk.tag import PerceptronTagger
>>> from nltk.corpus import alpino as alp
>>> training_corpus = list(alp.tagged_sents()) # Materialize the corpus.
>>> tagger = PerceptronTagger(load=True)
>>> tagger.train(training_corpus)
>>> sent = 'NLTK is een goeda taal voor het leren over NLP'.split()
>>> tagger.tag(sent)
[('NLTK', u'noun'), ('is', u'verb'), ('een', u'det'), ('goeda', u'adj'), ('taal', u'noun'), ('voor', u'prep'), ('het', u'det'), ('leren', u'noun'), ('over', u'prep'), ('NLP', u'noun')
```

Possibly, before the iteration at https://github.com/nltk/nltk/blob/develop/nltk/tag/perceptron.py#L174, we will need to do something like `sentences = list(sentences)` to materialize generators / iterables to accommodate the operation. 

@honnibal @longdt219 , is there any other way to circumvent this, other than materializing the list of sentences?

---

Also, the docstring at https://github.com/nltk/nltk/blob/develop/nltk/tag/perceptron.py#L168, should be `:param sentences: A list of sentences, each sentence is a list of (words, tags) tuples.` instead of `:param sentences: A list of (words, tags) tuples.`
