### ISSUE TITLE
Bleu tests failing

### ISSUE THREAD

**Issue by fievelk** [nltk/nltk#1504]
BLEU tests are currently failing

```
tox -e py34 nltk/test/unit/translate/test_bleu.py
```
```
py34 runtests: commands[1] | python runtests.py unit/translate/test_bleu.py
.........E
======================================================================
ERROR: test_corpus_bleu (nltk.test.unit.translate.test_bleu.TestBLEUvsMteval13a)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "nltk/test/unit/translate/test_bleu.py", line 187, in test_corpus_bleu
    nltk_bleu = corpus_bleu(references, hypothesis, weights=(1.0/i,)*i)
  File "nltk/translate/bleu_score.py", line 139, in corpus_bleu
    assert len(list_of_references) == len(hypotheses), "The number of hypotheses and their reference(s) should be the same"
TypeError: object of type 'map' has no len()

----------------------------------------------------------------------
Ran 10 tests in 0.006s

FAILED (errors=1)
```

@alvations Could you please check this issue, if you have time?

P.S. If other test failures or import errors get in the way, you might find it useful to create a new branch and merge the following pending PRs: #1497, #1499, #1500, #1501

**Comment by alvations** [comment]
Ah this is a python2 and python3 difference. `map()` materializes the list in python2 but in python3 doesn't. I'll fix that in a while.

**Comment by alvations** [comment]
Note that there is a deprecation warning from `nltk.util.ngrams` that's kind of irritating but it'll take longer to fix. It will show up in Python3.5 with:

```
~/git/nltk$ python3 -m unittest nltk.test.unit.translate.test_bleu
....../usr/lib/python3.5/collections/__init__.py:617: PendingDeprecationWarning: generator 'ngrams' raised StopIteration
  _count_elements(self, iterable)
....
----------------------------------------------------------------------
Ran 10 tests in 0.282s
OK
```

**Comment by alvations** [comment]
This warning is strange. I can't replicate it when I'm not in unittest mode:

```python
$ python3
Python 3.5.2 (default, Oct 11 2016, 04:59:56) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from nltk import bleu
>>> references = ['The candidate has no alignment to any of the references'.split()]
>>> hypothesis = []
>>> assert bleu(references, hypothesis) == 0
>>> 
```

But in command line unittest:

```
$ python3 -m unittest nltk.test.unit.translate.test_bleu -v
test_brevity_penalty (nltk.test.unit.translate.test_bleu.TestBLEU) ... ok
test_full_matches (nltk.test.unit.translate.test_bleu.TestBLEU) ... ok
test_modified_precision (nltk.test.unit.translate.test_bleu.TestBLEU) ... ok
test_partial_matches_hypothesis_longer_than_reference (nltk.test.unit.translate.test_bleu.TestBLEU) ... ok
test_zero_matches (nltk.test.unit.translate.test_bleu.TestBLEU) ... ok
test_case_where_n_is_bigger_than_hypothesis_length (nltk.test.unit.translate.test_bleu.TestBLEUFringeCases) ... ok
test_empty_hypothesis (nltk.test.unit.translate.test_bleu.TestBLEUFringeCases) ... /usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/collections/__init__.py:617: PendingDeprecationWarning: generator 'ngrams' raised StopIteration
  _count_elements(self, iterable)
ok
test_empty_references (nltk.test.unit.translate.test_bleu.TestBLEUFringeCases) ... ok
test_empty_references_and_hypothesis (nltk.test.unit.translate.test_bleu.TestBLEUFringeCases) ... ok
test_corpus_bleu (nltk.test.unit.translate.test_bleu.TestBLEUvsMteval13a) ... ok

----------------------------------------------------------------------
Ran 10 tests in 0.287s

OK
```

----

Ah, the warnings were turned off by default:


```python
$ python3 -Wd
Python 3.5.2 (default, Oct 11 2016, 04:59:56) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from nltk import bleu
/Users/liling.tan/git-stuff/nltk/nltk/decorators.py:59: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  regargs, varargs, varkwargs, defaults = inspect.getargspec(func)
>>> references = ['The candidate has no alignment to any of the references'.split()]
>>> hypothesis = []
>>> assert bleu(references, hypothesis) == 0
/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/collections/__init__.py:617: PendingDeprecationWarning: generator 'ngrams' raised StopIteration
  _count_elements(self, iterable)
>>> 
```

**Comment by alvations** [comment]
Casting the empty generator into the `collections.Counter` object at https://github.com/alvations/nltk/blob/develop/nltk/translate/bleu_score.py#L269 is causing the `StopIteration`:

```python
$ python3 -Wd
>>> from collections import Counter
>>> from nltk import ngrams
/Users/liling.tan/git-stuff/nltk/nltk/decorators.py:59: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  regargs, varargs, varkwargs, defaults = inspect.getargspec(func)
>>> Counter(ngrams([], 4))
/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/collections/__init__.py:617: PendingDeprecationWarning: generator 'ngrams' raised StopIteration
  _count_elements(self, iterable)
Counter()
```

----

```python
$ python3 -Wd
Python 3.5.2 (default, Oct 11 2016, 04:59:56) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from collections import Counter
>>> from nltk import ngrams
/Users/liling.tan/git-stuff/nltk/nltk/decorators.py:59: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  regargs, varargs, varkwargs, defaults = inspect.getargspec(func)
>>> hyp = []
>>> counts = Counter(ngrams(hyp,4)) if hyp else Counter()
>>> counts
Counter()
>>> _counts = Counter(ngrams(hyp,4)) 
/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/collections/__init__.py:617: PendingDeprecationWarning: generator 'ngrams' raised StopIteration
  _count_elements(self, iterable)
```
