### ISSUE TITLE
Write tests for warnings

### ISSUE THREAD

**Issue by fievelk** [nltk/nltk#1520]
This issue is to keep track of what has been discussed in #1503.

It would be good to test that warnings are actually displayed in all those cases where NLTK provides users with warnings.

E.g.: since `tox` tests will not install many optional dependencies, we could check that a warning is displayed when some module tries to use an uninstalled package (see for example [`twitter/__init__.py`][1]). 

[1]: https://github.com/nltk/nltk/blob/develop/nltk/twitter/__init__.py#L16

**Comment by alvations** [comment]
On a related note, a horror of warnings pops up when executing `$ python3 -Wd -m unittest` ;P


```python
$ python3 -Wd -m unittest
/Users/liling.tan/git-stuff/nltk/nltk/decorators.py:59: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  regargs, varargs, varkwargs, defaults = inspect.getargspec(func)
/usr/local/lib/python3.5/site-packages/matplotlib/externals/six.py:80: PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  __import__(name)
/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/_bootstrap_external.py:415: ImportWarning: Not importing directory /usr/local/lib/python3.5/site-packages/mpl_toolkits: missing __init__
  _warnings.warn(msg.format(portions[0]), ImportWarning)
FFF...../Users/liling.tan/git-stuff/nltk/nltk/test/unit/test_corpora.py:40: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/liling.tan/nltk_data/corpora/cess_cat/06010100-1.tbf'>
  words = cess_cat.words()[:15]
/Users/liling.tan/git-stuff/nltk/nltk/test/unit/test_corpora.py:43: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/liling.tan/nltk_data/corpora/cess_cat/06010100-1.tbf'>
  self.assertEqual(cess_cat.tagged_sents()[0][34][0], "càrrecs")
./Users/liling.tan/git-stuff/nltk/nltk/test/unit/test_corpora.py:46: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/liling.tan/nltk_data/corpora/cess_esp/10017_20000413.tbf'>
  words = cess_esp.words()[:15]
/Users/liling.tan/git-stuff/nltk/nltk/test/unit/test_corpora.py:49: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/liling.tan/nltk_data/corpora/cess_esp/10017_20000413.tbf'>
  self.assertEqual(cess_esp.words()[115], "años")
.../Users/liling.tan/git-stuff/nltk/nltk/test/unit/test_corpora.py:54: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/liling.tan/nltk_data/corpora/floresta/Floresta_7.4.ptb'>
  words = floresta.words()[:10]
./Users/liling.tan/git-stuff/nltk/nltk/test/unit/test_corpora.py:34: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/liling.tan/nltk_data/corpora/indian/bangla.pos'>
  tagged_words = indian.tagged_words()[:3]
./Users/liling.tan/git-stuff/nltk/nltk/test/unit/test_corpora.py:30: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/liling.tan/nltk_data/corpora/indian/bangla.pos'>
  words = indian.words()[:3]
.ssssss/Users/liling.tan/git-stuff/nltk/nltk/test/unit/test_corpora.py:68: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/liling.tan/nltk_data/corpora/sinica_treebank/parsed'>
  parsed_sents = sinica_treebank.parsed_sents()[25]
./Users/liling.tan/git-stuff/nltk/nltk/test/unit/test_corpora.py:61: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/liling.tan/nltk_data/corpora/sinica_treebank/parsed'>
  first_3_sents = sinica_treebank.sents()[:3]
..................ssss/Users/liling.tan/git-stuff/nltk/nltk/test/unit/test_stem.py:74: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/liling.tan/nltk_data/stemmers/porter_test/porter_martin_output.txt'>
  .open(encoding='utf-8')
/Users/liling.tan/git-stuff/nltk/nltk/test/unit/test_stem.py:46: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/liling.tan/nltk_data/stemmers/porter_test/porter_vocabulary.txt'>
  .open(encoding='utf-8')
./Users/liling.tan/git-stuff/nltk/nltk/test/unit/test_stem.py:83: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/liling.tan/nltk_data/stemmers/porter_test/porter_nltk_output.txt'>
  .open(encoding='utf-8')
./Users/liling.tan/git-stuff/nltk/nltk/test/unit/test_stem.py:97: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/liling.tan/nltk_data/stemmers/porter_test/porter_original_output.txt'>
  .open(encoding='utf-8')
./Users/liling.tan/git-stuff/nltk/nltk/corpus/reader/wordlist.py:27: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/liling.tan/nltk_data/corpora/stopwords/german'>
  return concat([self.open(f).read() for f in fileids])
........................................................8 [(7, 7), (34, 42), (21, 19), (8, 10), (14, 17), (6, 6), (29, 23), (19, 24), (31, 22), (30, 23), (24, 25), (18, 17), (40, 33), (11, 11), (11, 7), (24, 24), (6, 6), (19, 19), (29, 18), (19, 19), (18, 17), (27, 23), (26, 29), (14, 15), (21, 18), (25, 21), (25, 23), (31, 25), (12, 10), (29, 36), (32, 33), (30, 28), (16, 19), (13, 13), (10, 10), (10, 9), (9, 8), (22, 17), (14, 12), (21, 19), (16, 15), (12, 8), (12, 9), (18, 19), (6, 8), (80, 72), (15, 14), (9, 11), (13, 13), (16, 16), (17, 23), (23, 25), (22, 30), (16, 14), (18, 20), (12, 13), (18, 17), (30, 32), (29, 29), (17, 18), (49, 39), (27, 24), (40, 38), (17, 15), (25, 24), (25, 21), (25, 19), (28, 28), (8, 8), (7, 6), (27, 17), (9, 7), (33, 23), (16, 15), (32, 28), (13, 12), (10, 10), (18, 17), (14, 13), (28, 26), (9, 8), (20, 17), (21, 18), (17, 16), (23, 22), (7, 7), (29, 19), (9, 9), (15, 14), (14, 8), (10, 9), (9, 11), (14, 14), (11, 13), (23, 23), (13, 13), (20, 14), (34, 32), (27, 24), (9, 8)]

blah blah blah
/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/collections/__init__.py:617: PendingDeprecationWarning: generator 'ngrams' raised StopIteration
  _count_elements(self, iterable)
9 [(7, 7), (34, 42), (21, 19), (8, 10), (14, 17), (6, 6), (29, 23), (19, 24), (31, 22), (30, 23), (24, 25), (18, 17), (40, 33), (11, 11), (11, 7), (24, 24), (6, 6), (19, 19), (29, 18), (19, 19), (18, 17), (27, 23), (26, 29), (14, 15), (21, 18), (25, 21), (25, 23), (31, 25), (12, 10), (29, 36), (32, 33), (30, 28), (16, 19), (13, 13), (10, 10), (10, 9), (9, 8), (22, 17), (14, 12), (21, 19), (16, 15), (12, 8), (12, 9), (18, 19), (6, 8), (80, 72), (15, 14), (9, 11), (13, 13), (16, 16), (17, 23), (23, 25), (22, 30), (16, 14), (18, 20), (12, 13), (18, 17), (30, 32), (29, 29), (17, 18), (49, 39), (27, 24), (40, 38), (17, 15), (25, 24), (25, 21), (25, 19), (28, 28), (8, 8), (7, 6), (27, 17), (9, 7), (33, 23), (16, 15), (32, 28), (13, 12), (10, 10), (18, 17), (14, 13), (28, 26), (9, 8), (20, 17), (21, 18), (17, 16), (23, 22), (7, 7), (29, 19), (9, 9), (15, 14), (14, 8), (10, 9), (9, 11), (14, 14), (11, 13), (23, 23), (13, 13), (20, 14), (34, 32), (27, 24), (9, 8)]

blah blah blah
...............................................
======================================================================
FAIL: test_unnoramlize_fraction (nltk.test.unit.test_2x_compat.TestFraction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/liling.tan/git-stuff/nltk/nltk/test/unit/test_2x_compat.py", line 35, in test_unnoramlize_fraction
    NativePythonFraction(0, 1000, _normalize=False)
AssertionError: TypeError not raised

======================================================================
FAIL: test_repr (nltk.test.unit.test_2x_compat.TestTextTransliteration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/liling.tan/git-stuff/nltk/nltk/test/unit/test_2x_compat.py", line 22, in test_repr
    self.assertEqual(repr(self.txt), br"<Text: S\xe3o Tom\xe9 and Pr\xedncipe...>")
AssertionError: '<Text: São Tomé and Príncipe...>' != b'<Text: S\\xe3o Tom\\xe9 and Pr\\xedncipe...>'

======================================================================
FAIL: test_str (nltk.test.unit.test_2x_compat.TestTextTransliteration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/liling.tan/git-stuff/nltk/nltk/test/unit/test_2x_compat.py", line 25, in test_str
    self.assertEqual(str(self.txt), b"<Text: Sao Tome and Principe...>")
AssertionError: '<Text: São Tomé and Príncipe...>' != b'<Text: Sao Tome and Principe...>'

----------------------------------------------------------------------
Ran 150 tests in 6.598s

FAILED (failures=3, skipped=10)
```

**Comment by gpassero** [comment]
@alvations I am having the same problem here.
