### ISSUE TITLE
Import fails, if userhome contains german umlauts

### ISSUE THREAD

**Issue by Ichaelus** [nltk/nltk#1528]
I'm trying to use the python module for nltk, but while it's working perfectly fine on my desktop PC, my notebook refused to miss out following error:

```
Traceback (most recent call last):
  File "start.py", line 6, in <module>
    from Controllers.HomeController import homebottle, homesetclassifiercollection
  File "D:\Documents\Coding\GithubClassificator\Application\Controllers\HomeController.py", line 6, in <module>
    import Models.ClassifierCollection
  File "D:\Documents\Coding\GithubClassificator\Application\Models\ClassifierCollection.py", line 4, in <module>
    import ClassificationModules.ClassificationModule
  File "D:\Documents\Coding\GithubClassificator\Application\Models\ClassificationModules\ClassificationModule.py", line 8, in <module>
    from FeatureProcessing import getLabelIndex
  File "D:\Documents\Coding\GithubClassificator\Application\Models\ClassificationModules\FeatureProcessing.py", line 9, in <module>
    from nltk.stem import PorterStemmer
  File "C:\Program Files\Python27\lib\site-packages\nltk\__init__.py", line 128, in <module>
    from nltk.chunk import *
  File "C:\Program Files\Python27\lib\site-packages\nltk\chunk\__init__.py", line 155, in <module>
    from nltk.data import load
  File "C:\Program Files\Python27\lib\site-packages\nltk\data.py", line 77, in <module>
    if 'APPENGINE_RUNTIME' not in os.environ and os.path.expanduser('~/') != '~/':
  File "C:\Program Files\Python27\lib\ntpath.py", line 311, in expanduser
    return **userhome + path[i:]**
UnicodeDecodeError: 'ascii' codec can't decode **byte 0xe4 in position 23**: ordinal not in range(128)
```
_I marked the important parts of that output with **_

Tracing it down, I figured out that actualy my username contains a german umlaut (ä) on position 23; not a good choice of mine to be fair. It seems that nltk misses to check the userhome for non-ascii characters.

It shouldn't be that hard to fix, though.

Greetings

**Comment by stevenbird** [comment]
@Ichaelus: this is a problem with Python 2.7 not NLTK (see the error messages). Would you please upgrade to Python 3.4 or 3.5 and see if the problem goes away.
