### ISSUE TITLE
DeprecationWarnings for @memoize for Python3.5

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#1530]
The `memoize` decorator needs some updating such that it's using the new/better `inspect` from Python3.5

```bash
~/git-stuff/nltk$ python3 -W error -m nltk
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/liling.tan/git-stuff/nltk/nltk/__init__.py", line 115, in <module>
    from nltk.decorators import decorator, memoize
  File "/Users/liling.tan/git-stuff/nltk/nltk/decorators.py", line 183, in <module>
    @decorator
  File "/Users/liling.tan/git-stuff/nltk/nltk/decorators.py", line 172, in decorator
    return update_wrapper(_decorator, caller)
  File "/Users/liling.tan/git-stuff/nltk/nltk/decorators.py", line 83, in update_wrapper
    infodict = infodict or getinfo(model)
  File "/Users/liling.tan/git-stuff/nltk/nltk/decorators.py", line 59, in getinfo
    regargs, varargs, varkwargs, defaults = inspect.getargspec(func)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/inspect.py", line 1041, in getargspec
    stacklevel=2)
DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
```

Related to #630

**Comment by naoyak** [comment]
Would it make sense to simply include the original [decorator](https://github.com/micheles/decorator) package as a requirement? It looks like the deprecation issue has been [addressed](https://github.com/micheles/decorator/blob/ae96a8f0844770bfb592012ac3ad06cdc7f8e3f9/src/decorator.py#L44-L77) there. (note that `getfullargspec` has been un-deprecated from Python 3.6 final)

**Comment by dimazest** [comment]
Starting with Python 3.2 there is [lru_cache()](https://docs.python.org/3/library/functools.html#functools.lru_cache) decorator. It was [backported](https://pypi.python.org/pypi/backports.functools_lru_cache/1.3) to Python 2 as well.

So, maybe it worth using Python 3's lru_cache if it's available, otherwise use memoize.
