### ISSUE TITLE
nltk.tokenize.moses.py needs quite some re-working and tests

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#1551]
There are several problems that needs to be fixed for `nltk.tokenize.moses` to work properly:

**Non-well-formed regexes**

E.g. The missing brackets at https://github.com/nltk/nltk/blob/develop/nltk/tokenize/moses.py#L90 will cause the `nltk.tokenize.moses.penn_tokenize()` function to break:

```python
$ python -c 'from nltk.tokenize.moses import MosesTokenizer; m = MosesTokenizer(); m.penn_tokenize("this aint funny")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "nltk/tokenize/moses.py", line 299, in penn_tokenize
    text = re.sub(regexp, subsitution, text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: unbalanced parenthesis
``` 

**Mising global/local self scoping for `MosesTokenizer` object**

At codepoint https://github.com/nltk/nltk/blob/develop/nltk/tokenize/moses.py#L301, local function calling a local object function without `self`, causing: 

```
$ python -c 'from nltk.tokenize.moses import MosesTokenizer; m = MosesTokenizer(); m.penn_tokenize("this aint funny")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "nltk/tokenize/moses.py", line 301, in penn_tokenize
    text = handles_nonbreaking_prefixes(text)
NameError: global name 'handles_nonbreaking_prefixes' is not defined
```

**Misspelling of variables**

It should be `substitution` not `subsitution`, misspelling sprinkled all about the script.

**Typo in comments** 

It should be "tokens" not "toknes" at https://github.com/nltk/nltk/blob/develop/nltk/tokenize/moses.py#L256

**Comment by alvations** [comment]
Also, the `MosesTokenizer.tokenize()` function is outputting erroneous escape backslashes:

```python
$ python -c """from nltk.tokenize.moses import MosesTokenizer; m = MosesTokenizer(); print m.tokenize('''this ain't funny''')"""
[u'this', u'ain', u'\\&apos;', u't', u'funny']
```

This seems to be a problem only for XML escapable characters, i.e. characters from these set https://github.com/nltk/nltk/blob/develop/nltk/tokenize/moses.py#L159 and https://github.com/nltk/nltk/blob/develop/nltk/tokenize/moses.py#L399:

```python
$ python -c 'from nltk.tokenize.moses import MosesTokenizer; m = MosesTokenizer(); print m.tokenize("this aint <funny> & do you |know about [abc] and (def), or {xyz}?")'
[u'this', u'aint', u'\\&lt;', u'funny', u'\\&gt;', u'\\&amp;', u'do', u'you', u'\\&#124;', u'know', u'about', u'\\&#91;', u'abc', u'\\&#93;', u'and', u'(', u'def', u')', u',', u'or', u'{', u'xyz', u'}', u'?']
```

So is the detokenizer() outputting erroneous backslashes, moreover not detokenizing though it unescape the XML escape characters:

```python
$ python -c """from nltk.tokenize.moses import MosesDetokenizer; m = MosesDetokenizer(); print m.detokenize('''this ain &apos;t funny'''.split())"""
[u'this', u'ain', u"\\'t", u'funny']
```

I'm not sure whether this is platform sensitive thing. I am having these erroneous backslashes on a Mac. Anyone having the same problems on a Linux?

----

Also, we need to write tests to check the outputs of our implementation against [Moses' tokenizer.perl](https://github.com/alvations/mosesdecoder/blob/master/scripts/tokenizer/tokenizer.perl) and [detokenizer.perl](https://github.com/alvations/mosesdecoder/blob/master/scripts/tokenizer/detokenizer.perl)

**Comment by alvations** [comment]
Ahhh, pushing on to the wrong branch, reverting.

**Comment by alvations** [comment]
The expected outputs of the English contractions and escaped XML characters from should look like this:

```
$ echo "this ain't funny. I'm funny am I?" | ~/mosesdecoder/scripts/tokenizer/tokenizer.perl 
Tokenizer Version 1.1
Language: en
Number of threads: 1
this ain &apos;t funny . I &apos;m funny am I ?
```

But NLTK is outputing some erroneous backslashes as well as splitting the `&apos;t` up.

```
>>> from nltk.tokenize.moses import MosesTokenizer
>>> m = MosesTokenizer()
>>> m.tokenize("this ain't funny. I'm funny am I?")
[u'this', u'ain', u'\\&apos;', u't', u'funny.', u'I', u'\\&apos;', u'm', u'funny', u'am', u'I', u'?']
```

The main issue of the tokenizer seems to come from https://github.com/nltk/nltk/blob/develop/nltk/tokenize/moses.py#L349 and originally from [moses' code](https://github.com/alvations/mosesdecoder/blob/master/scripts/tokenizer/tokenizer.perl#L301):

```python
>>> from nltk.tokenize.moses import MosesTokenizer
>>> from nltk.corpus import perluniprops, nonbreaking_prefixes
>>> from six import text_type
>>> IsN = text_type(''.join(perluniprops.chars('IsN')))
>>> IsAlnum = text_type(''.join(perluniprops.chars('IsAlnum')))
>>> IsSc = text_type(''.join(perluniprops.chars('IsSc')))
>>> IsSo = text_type(''.join(perluniprops.chars('IsSo')))
>>> IsAlpha = text_type(''.join(perluniprops.chars('IsAlpha')))
>>> IsLower = text_type(''.join(perluniprops.chars('IsLower')))
>>> import re
>>> EN_SPECIFIC_1 = u"([^{alpha}])[']([^{alpha}])".format(alpha=IsAlpha), r"\1 ' \2"
>>> EN_SPECIFIC_2 = u"([^{alpha}{isn}])[']([{alpha}])".format(alpha=IsAlpha, isn=IsN), r"\1 ' \2"
>>> EN_SPECIFIC_3 = u"([{alpha}])[']([^{alpha}])".format(alpha=IsAlpha), r"\1 ' \2"
>>> EN_SPECIFIC_4 = u"([{alpha}])[']([{alpha}])".format(alpha=IsAlpha), r"\1 ' \2"
>>> EN_SPECIFIC_5 = u"([{isn}])[']([s])".format(isn=IsN), r"\1 '\2"
>>> text = "this ain't funny. | I'm funny am I?"
>>> _regexp, _sub = EN_SPECIFIC_1
>>> re.sub(_regexp, _sub, text)
"this ain't funny. | I'm funny am I?"
>>> _regexp, _sub = EN_SPECIFIC_2
>>> re.sub(_regexp, _sub, text)
"this ain't funny. | I'm funny am I?"
>>> _regexp, _sub = EN_SPECIFIC_3
>>> re.sub(_regexp, _sub, text)
"this ain't funny. | I'm funny am I?"
>>> _regexp, _sub = EN_SPECIFIC_4
>>> re.sub(_regexp, _sub, text)
"this ain ' t funny. | I ' m funny am I?"

>>> _regexp, _sub = EN_SPECIFIC_4
>>> x = re.sub(_regexp, _sub, text)
>>> _regexp, _sub = EN_SPECIFIC_5
>>> re.sub(_regexp, _sub, x)
"this ain ' t funny. | I ' m funny am I?"
```

From Moses, https://github.com/alvations/mosesdecoder/blob/master/scripts/tokenizer/tokenizer.perl#L307:

```
$text =~ s/([\p{IsAlpha}])[']([\p{IsAlpha}])/$1 '$2/g;
```

In NLTK, https://github.com/nltk/nltk/blob/develop/nltk/tokenize/moses.py#L172:

```
EN_SPECIFIC_4 = u"([{alpha}])[']([{alpha}])".format(alpha=IsAlpha), r"\1 ' \2"
```

There's a typo there where there shouldn't be a space before `\2`, so the right regex should be 

```
EN_SPECIFIC_4 = u"([{alpha}])[']([{alpha}])".format(alpha=IsAlpha), r"\1 '\2"
```

With the fix of the `EN_SPECIFIC_4` regex, we get:

```python
>>> from nltk.tokenize.moses import MosesTokenizer
>>> m = MosesTokenizer()
>>> m.tokenize("This ain't funny")
[u'This', u'ain', u'\\&apos;t', u'funny']
```

**Comment by alvations** [comment]
Regarding the superfluous `\` from escaping XML, **is it alright if we skip the "correctness" of porting from Perl regexes to Python and in-built Python XML escape functions?**, e.g.:

```python
>>> from xml.sax.saxutils import escape
>>> def xmlescape(data):
...     return escape(data, entities={
...         "'": "&apos;",
...         "\"": "&quot;"
...     })
... 
>>> x = [u'This', u'ain', u"'t", u'funny']
>>> xmlescape(' '.join(x))
u'This ain &apos;t funny'
```

----

After second thoughts. then detokenizing would be harder. Maybe the function is nice in `nltk.tokenize.util` but not in the `MosesTokenizer` class
