### ISSUE TITLE
How to handle BLEU scores for ngrams where n<4 in NLTK? 

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#1554]
From #1545, BLEU is buggy for ngrams where the n<4. 

One simple way is to clip the weights distribution such that the `weights=(0.25, 0.25, 0.25, 0.25)` redistributes uniformly with respect to the highest ngram order from the hypothesis or reference. 

But we're not sure whether that's the most appropriate solution to fix that. 

Meanwhile, while smoothing functions work fine when reference length is n>=4, it goes haywire when n<4 too. 

----

Without smoothing, NLTK's BLEU is overly-optimistic with the condition on https://github.com/nltk/nltk/blob/develop/nltk/translate/bleu_score.py#L170:

```
>>> from nltk import bleu
>>> ref = 'let it go'.split()
>>> hyp = 'let go it'.split()
>>> bleu([ref], hyp)
1.0
```

With smoothing, the BLEU goes haywire:

```python
>>> from nltk.translate.bleu_score import SmoothingFunction
>>> chencherry = SmoothingFunction()
>>> bleu([ref], hyp, smoothing_function=chencherry.method0) # No smoothing
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nltk/translate/bleu_score.py", line 79, in sentence_bleu
    return corpus_bleu([references], [hypothesis], weights, smoothing_function)
  File "nltk/translate/bleu_score.py", line 180, in corpus_bleu
    return bp * math.exp(math.fsum(s))
  File "nltk/translate/bleu_score.py", line 178, in <genexpr>
    s = (w * math.log(p_i) for i, (w, p_i) in enumerate(zip(weights, p_n)))
ValueError: math domain error
>>> bleu([ref], hyp, smoothing_function=chencherry.method1) 
0.14953487812212207
>>> bleu([ref], hyp, smoothing_function=chencherry.method2) 
0.537284965911771
>>> bleu([ref], hyp, smoothing_function=chencherry.method3) 
0.2973017787506803
>>> bleu([ref], hyp, smoothing_function=chencherry.method4)
4.876766661577289
>>> bleu([ref], hyp, smoothing_function=chencherry.method5) 
0.19245008972987526
>>> bleu([ref], hyp, smoothing_function=chencherry.method6) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nltk/translate/bleu_score.py", line 79, in sentence_bleu
    return corpus_bleu([references], [hypothesis], weights, smoothing_function)
  File "nltk/translate/bleu_score.py", line 177, in corpus_bleu
    hypothesis=hypothesis, hyp_len=hyp_len)
  File "nltk/translate/bleu_score.py", line 540, in method6
    pi0 = 0 if p_n[i-2] == 0 else p_n[i-1]**2 / p_n[i-2]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/fractions.py", line 362, in forward
    return monomorphic_operator(a, b)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/fractions.py", line 412, in _div
    a.denominator * b.numerator)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/fractions.py", line 162, in __new__
    raise ZeroDivisionError('Fraction(%s, 0)' % numerator)
ZeroDivisionError: Fraction(0, 0)
>>> bleu([ref], hyp, smoothing_function=chencherry.method7) 
5.5913883085947536
```

Method 4 is surely wrong since the output looks like it's in log space. And the error in method 7 follows from method 4 since 7 is combination of method 4 and method 6.

**Comment by alvations** [comment]
One necessary evil to resolve this BLEU issue for n<4 is to add some sort of weights redistribution if n<4 before https://github.com/nltk/nltk/blob/develop/nltk/translate/bleu_score.py#L159 :

```
    # Uniformly re-weighting based on maximum hypothesis lengths if largest
    # order of n-grams < 4 and weights is set at default.
    if hyp_lengths < 4 and weights == (0.25, 0.25, 0.25, 0.25):
        weights = ( 1 / hyp_lengths ,) * hyp_lengths

    # Collects the various precision values for the different ngram orders.
    p_n = [Fraction(p_numerators[i], p_denominators[i], _normalize=False)
           for i, _ in enumerate(weights, start=1)]
```

This is necessary because without the re-weighting, the smoothing would have assigned probabilities to the 0 counts of ngrams and then heavily penalize the outputs for no particular reason on the higher order of ngrams that doesn't exist in the reference, e.g. for method4 with reweighting and w/o:

```python
# With re-weighting:

>>> from nltk.translate.bleu_score import SmoothingFunction, sentence_bleu
>>> bleu = sentence_bleu
>>> ref = "let it go".split()
>>> hyp = "let go it".split()
>>> cc = SmoothingFunction()
>>> bleu([ref], hyp, smoothing_function=cc.method4)
0.2056462407017238

# w/o reweighting.
>>> bleu = sentence_bleu
>>> ref = "let it go".split()
>>> hyp = "let go it".split()
>>> cc = SmoothingFunction()
>>> bleu([ref], hyp, smoothing_function=cc.method4)
0.09235630903689572
```

The individual ngram scores after smoothing: 
 - with: [Fraction(3, 3), 0.21972245773362198, 0.03958110152551346]
 - w/o: [Fraction(3, 3), 0.21972245773362198, 0.03958110152551346, 0.008365732018625381]

Note that w/o reweighting the 4grams precision are computed. 

----

For `multi-bleu.pl`, they handle such cases where n<3 by return 0.0 for any hypothesis, e.g.:

```
$ ~/mosesdecoder/scripts/generic/multi-bleu.perl ref.txt < hyp.txt 
Use of uninitialized value in division (/) at /Users/liling.tan/mosesdecoder/scripts/generic/multi-bleu.perl line 139, <STDIN> line 1.
Use of uninitialized value in division (/) at /Users/liling.tan/mosesdecoder/scripts/generic/multi-bleu.perl line 139, <STDIN> line 1.
BLEU = 0.00, 100.0/0.0/0.0/0.0 (BP=1.000, ratio=1.000, hyp_len=3, ref_len=3)
```

For `mteval-v13a.pl`, they use NIST smoothing which is equivalent to NLTK implementation of `SmoothingFunction.method3()`: 

```
~$ cat ref.sgm 
<refset setid="newstest2015" srclang="any" trglang="en">
<doc sysid="ref" docid="1012-bbc" genre="news" origlang="en">
<p>
<seg id="1">let it go</seg>
</p>
</doc>
</refset>

~$ cat hyp.sgm 
<tstset setid="newstest2015" srclang="any" trglang="en">
<doc sysid="h1" docid="1012-bbc" genre="news" origlang="en">
<p>
<seg id="1">let got it</seg>
</p>
</doc>
</tstset>

~$ cat src.sgm 
<srcset setid="newstest2015" srclang="any">
<doc sysid="src" docid="1012-bbc" genre="news" origlang="en">
<p>
<seg id="01">let it go</seg>
</p>
</doc>
</srcset>

~$ perl ~/mosesdecoder/scripts/generic/mteval-v13a.pl -r ref.sgm -s src.sgm -t hyp.sgm 
Use of 'Hyphen' in \p{} or \P{} is deprecated because: Supplanted by Line_Break property values; see www.unicode.org/reports/tr14; at /Users/liling.tan/mosesdecoder/scripts/generic/mteval-v13a.pl line 951.
MT evaluation scorer began on 2016 Dec 23 at 13:57:38
command line:  /Users/liling.tan/mosesdecoder/scripts/generic/mteval-v13a.pl -r ref.sgm -s src.sgm -t hyp.sgm
  Evaluation of any-to-en translation using:
    src set "newstest2015" (1 docs, 1 segs)
    ref set "newstest2015" (1 refs)
    tst set "newstest2015" (1 systems)

length ratio: 1 (3/3), penalty (log): 0
NIST score = 1.0566  BLEU score = 0.4518 for system "h1"

# ------------------------------------------------------------------------

Individual N-gram scoring
        1-gram   2-gram   3-gram   4-gram   5-gram   6-gram   7-gram   8-gram   9-gram
        ------   ------   ------   ------   ------   ------   ------   ------   ------
 NIST:  1.0566   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000  "h1"

 BLEU:  0.6667   0.2500   0.2500   1.0000   1.0000   1.0000   1.0000   1.0000   1.0000  "h1"

# ------------------------------------------------------------------------
Cumulative N-gram scoring
        1-gram   2-gram   3-gram   4-gram   5-gram   6-gram   7-gram   8-gram   9-gram
        ------   ------   ------   ------   ------   ------   ------   ------   ------
 NIST:  1.0566   1.0566   1.0566   1.0566   1.0566   1.0566   1.0566   1.0566   1.0566  "h1"

 BLEU:  0.6667   0.4082   0.3467   0.4518   0.5296   0.5888   0.6351   0.6722   0.7025  "h1"
MT evaluation scorer ended on 2016 Dec 23 at 13:57:38
```

If we look at the "Individual N-gram scoring" we see that the `mteval-v13a.pl` is over assigning scores to the individual n-grams but somehow cumulatively, it works within the bounds of 4grams, beyond that, the 9-grams scores shouldn't be accepted. 
 

In comparison, NLTK implementation of NIST smoothing (method3) with reweighting:

```python
>>> from nltk.translate.bleu_score import SmoothingFunction, sentence_bleu
>>> bleu = sentence_bleu
>>> ref = "let it go".split()
>>> hyp = "let go it".split()
>>> cc = SmoothingFunction()
>>> bleu([ref], hyp, smoothing_function=cc.method3)
0.3968502629920499
```

NLTK implementation of NIST smoothing (method3) with w/o reweighting:


```python
>>> from nltk.translate.bleu_score import SmoothingFunction, sentence_bleu
>>> bleu = sentence_bleu
>>> ref = "let it go".split()
>>> hyp = "let go it".split()
>>> cc = SmoothingFunction()
>>> bleu([ref], hyp, smoothing_function=cc.method3)
0.2973017787506803
```

----

We do have to keep in mind that these are all fringe use cases of BLEU.
