### ISSUE TITLE
StanfordNERTagger for Chinese got `java.io.StreamCorruptedException: invalid stream header: 504B0304`

### ISSUE THREAD

**Issue by eromoe** [nltk/nltk#1625]
Hi, I am trying to use ntlk to detect ner in Chinese text.

As https://github.com/stanfordnlp/CoreNLP/issues/358 mentioned , `chinese.misc.distsim.crf.ser.gz` has been merged into 'stanford-chinese-corenlp-2016-10-31-models.jar'

My test code:
```
from nltk.tag import StanfordNERTagger

chi_tagger = StanfordNERTagger('stanford-chinese-corenlp-2016-10-31-models.jar')
sent = u'北海 已 成为 中国 对外开放 中 升起 的 一 颗 明星'
for word, tag in  chi_tagger.tag(sent.split()):
    print word.encode('utf-8'), tag
```

Error:
```
Invoked on Tue Feb 14 06:07:47 UTC 2017 with arguments: -loadClassifier /mnt/nlp/stanford-chinese-model/stanford-chinese-corenlp-2016-10-31-models.jar -textFile /tmp/tmp3mvoLR -outputFormat slashTags -tokenizerFactory edu.stanford.nlp.process.WhitespaceTokenizer -tokenizerOptions "tokenizeNLs=false" -encoding utf8
tokenizerFactory=edu.stanford.nlp.process.WhitespaceTokenizer
tokenizerOptions="tokenizeNLs=false"
loadClassifier=/mnt/nlp/stanford-chinese-model/stanford-chinese-corenlp-2016-10-31-models.jar
encoding=utf8
textFile=/tmp/tmp3mvoLR
outputFormat=slashTags
Exception in thread "main" edu.stanford.nlp.io.RuntimeIOException: java.io.StreamCorruptedException: invalid stream header: 504B0304
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifierNoExceptions(AbstractSequenceClassifier.java:1507)
        at edu.stanford.nlp.ie.crf.CRFClassifier.main(CRFClassifier.java:3017)
Caused by: java.io.StreamCorruptedException: invalid stream header: 504B0304
        at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:808)
        at java.io.ObjectInputStream.<init>(ObjectInputStream.java:301)
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifier(AbstractSequenceClassifier.java:1462)
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifier(AbstractSequenceClassifier.java:1494)
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifierNoExceptions(AbstractSequenceClassifier.java:1505)
        ... 1 more

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-4-120cdfa045bb> in <module>()
      3 chi_tagger = StanfordNERTagger('stanford-chinese-corenlp-2016-10-31-models.jar')
      4 sent = u'北海 已 成为 中国 对外开放 中 升起 的 一 颗 明星'
----> 5 for word, tag in  chi_tagger.tag(sent.split()):
      6     print word.encode('utf-8'), tag
      7

/usr/local/lib/python2.7/dist-packages/nltk/tag/stanford.pyc in tag(self, tokens)
     69     def tag(self, tokens):
     70         # This function should return list of tuple rather than list of list
---> 71         return sum(self.tag_sents([tokens]), [])
     72
     73     def tag_sents(self, sentences):

/usr/local/lib/python2.7/dist-packages/nltk/tag/stanford.pyc in tag_sents(self, sentences)
     92         # Run the tagger and get the output
     93         stanpos_output, _stderr = java(cmd, classpath=self._stanford_jar,
---> 94                                                        stdout=PIPE, stderr=PIPE)
     95         stanpos_output = stanpos_output.decode(encoding)
     96

/usr/local/lib/python2.7/dist-packages/nltk/__init__.pyc in java(cmd, classpath, stdin, stdout, stderr, blocking)
    132     if p.returncode != 0:
    133         print(_decode_stdoutdata(stderr))
--> 134         raise OSError('Java command failed : ' + str(cmd))
    135
    136     return (stdout, stderr)

OSError: Java command failed : [u'/usr/bin/java', '-mx1000m', '-cp', '/mnt/nlp/stanford-ner-2016-10-31/stanford-ner-3.7.0-javadoc.jar:/mnt/nlp/stanford-ner-2016-10-31/stanford-ner-3.7.0-sources.jar:/mnt/nlp/stanford-ner-2016-10-31/stanford-ner.jar:/mnt/nlp/stanford-ner-2016-10-31/stanford-ner-3.7.0.jar:/mnt/nlp/stanford-ner-2016-10-31/lib/joda-time.jar:/mnt/nlp/stanford-ner-2016-10-31/lib/stanford-ner-resources.jar:/mnt/nlp/stanford-ner-2016-10-31/lib/jollyday-0.4.9.jar', 'edu.stanford.nlp.ie.crf.CRFClassifier', '-loadClassifier', '/mnt/nlp/stanford-chinese-model/stanford-chinese-corenlp-2016-10-31-models.jar', '-textFile', '/tmp/tmp3mvoLR', '-outputFormat', 'slashTags', '-tokenizerFactory', 'edu.stanford.nlp.process.WhitespaceTokenizer', '-tokenizerOptions', '"tokenizeNLs=false"', '-encoding', 'utf8']
```

I am not familiar with JAVA stack and don't know if `StanfordNERTagger('stanford-chinese-corenlp-2016-10-31-models.jar')` is correct.

**Comment by eromoe** [comment]
Oh, from stanford docs I found 

> You can either unpack the jar file or add it to the classpath; if you add the jar file to the classpath, you can then load the models from the path edu/stanford/nlp/models/....

Though `StanfordNERTagger('edu/stanford/nlp/models/ner/chinese.misc.distsim.crf.ser.gz')`  not work. 

I have to unpack that `.jar` file , and copy the model file to `stanford-ner-2016-10-31/classifiers`. 

It is better to mention in the docs

**Comment by stevenbird** [comment]
This should be resolved in our new interface to the Stanford Tools. If not, please reopen.

**Comment by KanwalPrakashSingh** [comment]
i dont think it is resolved yet
