### ISSUE TITLE
NLTK support for Python 3.6

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#1659]
Would NLTK be supporting Python3.6? 

Python3.6 had been shipped in Dec 2016 as scheduled on  [PEP 494](https://www.python.org/dev/peps/pep-0494/) . There's also an increase in Py3.6 uptake and the shelf-life should be around 2 years before [Py3.7 reaches the final dev stage](https://www.python.org/dev/peps/pep-0537/).

This might help in the port to Python 3.6 while keeping 2.7 and 3.4/3,5 functionalities: https://docs.python.org/3/whatsnew/3.6.html

**Comment by stevenbird** [comment]
:+1:

**Comment by nschneid** [comment]
When I import the framenet module in Python 3.6.0 with warnings enabled via the `-Wd` flag, I get:

```
/Users/ns1057/anaconda/lib/python3.6/site-packages/nltk/decorators.py:59: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  regargs, varargs, varkwargs, defaults = inspect.getargspec(func)
```

among other non-deprecation warnings. Then, the following code

```py
from nltk.corpus import framenet as fn
sents = fn.ft_sents('ANC__HistoryOfJerusalem')
for i,sent in enumerate(sents):
    pass
```

causes this warning when the loop is exhausted:

```
__main__:1: DeprecationWarning: generator 'LazyIteratorList.iterate_from' raised StopIteration
```

which I believe is due to [PEP 479](https://www.python.org/dev/peps/pep-0479/), and can be avoided by modifying the `LazyIteratorList.iterate_from()` method (which is a generator) to catch `StopIteration` and simply return. Perhaps other collections methods suffer from this as well—e.g. `LazyZip.iterate_from()`, which is another generator that calls `next()` on an iterator. Someone who understands PEP 479 better than I do should probably take a look. :)

**Comment by alvations** [comment]
Bumping issue. Any brave soul(s)?

**Comment by natgillin** [comment]
Porting from py35 to py36 might not be that hard with only 4 failed test =)

```
~/git-stuff/nltk$ tox -e py36

GLOB sdist-make: /Users/minion/git-stuff/nltk/setup.py
py36 create: /Users/minion/git-stuff/nltk/.tox/py36
py36 installdeps: numpy, nose >= 1.2.1, coverage, text-unidecode, twython, pyparsing, python-crfsuite, rednose
py36 inst: /Users/minion/git-stuff/nltk/.tox/dist/nltk-3.2.4.zip
py36 installed: certifi==2017.4.17,chardet==3.0.4,colorama==0.3.9,coverage==4.4.1,idna==2.5,nltk==3.2.4,nose==1.3.7,numpy==1.13.0,oauthlib==2.0.2,pyparsing==2.2.0,python-crfsuite==0.9.2,rednose==1.2.2,requests==2.18.1,requests-oauthlib==0.8.0,six==1.10.0,termstyle==0.1.11,text-unidecode==1.0,twython==3.5.0,urllib3==1.21.1
py36 runtests: PYTHONHASHSEED='1368252847'
py36 runtests: commands[0] | pip install scipy scikit-learn
Collecting scipy
  Downloading scipy-0.19.1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (16.2MB)
    100% |████████████████████████████████| 16.2MB 84kB/s 
Collecting scikit-learn
  Downloading scikit_learn-0.18.2-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (7.2MB)
    100% |████████████████████████████████| 7.2MB 103kB/s 
Requirement already satisfied: numpy>=1.8.2 in /Users/minion/git-stuff/nltk/.tox/py36/lib/python3.6/site-packages (from scipy)
Installing collected packages: scipy, scikit-learn
Successfully installed scikit-learn-0.18.2 scipy-0.19.1
py36 runtests: commands[1] | python runtests.py
-.......................F..F..F...........................-..................
...-.....-...............-........-......................................--..
..............................................................-...-...-...F.-
.-..-.....-..-...............................................................
...........-...--............--------........................................
..........................................--..................
======================================================================
1) FAIL: Doctest: nltk.corpus.reader.framenet.FramenetCorpusReader.frame_relation_types
----------------------------------------------------------------------
   Traceback (most recent call last):
    /usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/doctest.py line 2199 in runTest
      raise self.failureException(self.format_failure(new.getvalue()))
   AssertionError: Failed doctest test for nltk.corpus.reader.framenet.FramenetCorpusReader.frame_relation_types
     File "/Users/minion/git-stuff/nltk/nltk/corpus/reader/framenet.py", line 2239, in frame_relation_types
   
   ----------------------------------------------------------------------
   File "/Users/minion/git-stuff/nltk/nltk/corpus/reader/framenet.py", line 2249, in nltk.corpus.reader.framenet.FramenetCorpusReader.frame_relation_types
   Failed example:
       PrettyDict(frts[0], breakLines=True)
   Expected:
       {'ID': 1,
        '_type': 'framerelationtype',
        'frameRelations': [<Parent=Event -- Inheritance -> Child=Change_of_consistency>, <Parent=Event -- Inheritance -> Child=Rotting>, ...],
        'name': 'Inheritance',
        'subFrameName': 'Child',
        'superFrameName': 'Parent'}
   Got:
       {'ID': 10,
        '_type': 'framerelationtype',
        'frameRelations': [<Causative=Cause_to_move_in_place -- Causative_of -> Inchoative/state=Moving_in_place>, <Causative=Apply_heat -- Causative_of -> Inchoative/state=Absorb_heat>, ...],
        'name': 'Causative_of',
        'subFrameName': 'Inchoative/state',
        'superFrameName': 'Causative'}
======================================================================
2) FAIL: Doctest: nltk.corpus.reader.framenet.FramenetCorpusReader.frames_by_lemma
----------------------------------------------------------------------
   Traceback (most recent call last):
    /usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/doctest.py line 2199 in runTest
      raise self.failureException(self.format_failure(new.getvalue()))
   AssertionError: Failed doctest test for nltk.corpus.reader.framenet.FramenetCorpusReader.frames_by_lemma
     File "/Users/minion/git-stuff/nltk/nltk/corpus/reader/framenet.py", line 1409, in frames_by_lemma
   
   ----------------------------------------------------------------------
   File "/Users/minion/git-stuff/nltk/nltk/corpus/reader/framenet.py", line 1423, in nltk.corpus.reader.framenet.FramenetCorpusReader.frames_by_lemma
   Failed example:
       fn.frames_by_lemma(r'(?i)a little') # doctest: +ELLIPSIS
   Expected:
       [<frame ID=189 name=Quanti...>, <frame ID=2001 name=Degree>]
   Got:
       [<frame ID=2001 name=Degree>, <frame ID=189 name=Quantified_mass>]
======================================================================
3) FAIL: Doctest: nltk.corpus.reader.framenet.FramenetCorpusReader.lus
----------------------------------------------------------------------
   Traceback (most recent call last):
    /usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/doctest.py line 2199 in runTest
      raise self.failureException(self.format_failure(new.getvalue()))
   AssertionError: Failed doctest test for nltk.corpus.reader.framenet.FramenetCorpusReader.lus
     File "/Users/minion/git-stuff/nltk/nltk/corpus/reader/framenet.py", line 1904, in lus
   
   ----------------------------------------------------------------------
   File "/Users/minion/git-stuff/nltk/nltk/corpus/reader/framenet.py", line 1913, in nltk.corpus.reader.framenet.FramenetCorpusReader.lus
   Failed example:
       PrettyList(fn.lus(r'(?i)a little'), maxReprSize=0, breakLines=True)
   Expected:
       [<lu ID=14744 name=a little bit.adv>,
        <lu ID=14733 name=a little.n>,
        <lu ID=14743 name=a little.adv>]
   Got:
       [<lu ID=14744 name=a little bit.adv>,
        <lu ID=14743 name=a little.adv>,
        <lu ID=14733 name=a little.n>]
   ----------------------------------------------------------------------
   File "/Users/minion/git-stuff/nltk/nltk/corpus/reader/framenet.py", line 1917, in nltk.corpus.reader.framenet.FramenetCorpusReader.lus
   Failed example:
       fn.lus(r'interest', r'(?i)stimulus')
   Expected:
       [<lu ID=14920 name=interesting.a>, <lu ID=14894 name=interested.a>]
   Got:
       [<lu ID=14894 name=interested.a>, <lu ID=14920 name=interesting.a>]
======================================================================
4) FAIL: Doctest: framenet.doctest
----------------------------------------------------------------------
   Traceback (most recent call last):
    /usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/doctest.py line 2199 in runTest
      raise self.failureException(self.format_failure(new.getvalue()))
   AssertionError: Failed doctest test for framenet.doctest
     File "/Users/minion/git-stuff/nltk/nltk/test/framenet.doctest", line 0
   
   ----------------------------------------------------------------------
   File "/Users/minion/git-stuff/nltk/nltk/test/framenet.doctest", line 120, in framenet.doctest
   Failed example:
       fn.frames_by_lemma(r'(?i)a little') # doctest: +ELLIPSIS
   Expected:
       [<frame ID=189 name=Quanti...>, <frame ID=2001 name=Degree>]
   Got:
       [<frame ID=2001 name=Degree>, <frame ID=189 name=Quantified_mass>]
   ----------------------------------------------------------------------
   File "/Users/minion/git-stuff/nltk/nltk/test/framenet.doctest", line 190, in framenet.doctest
   Failed example:
       pprint(fn.lus(r'(?i)a little'))
   Expected:
       [<lu ID=14744 name=a little bit.adv>, <lu ID=14733 name=a little.n>, ...]
   Got:
       [<lu ID=14744 name=a little bit.adv>, <lu ID=14743 name=a little.adv>, ...]

-----------------------------------------------------------------------------
447 tests run in 188.482 seconds. 
4 FAILED, 29 skipped (414 tests passed)
ERROR: InvocationError: '/Users/minion/git-stuff/nltk/.tox/py36/bin/python runtests.py'
```

**Comment by alvations** [comment]
Bumping issue. Any brave soul?

**Comment by hyh92323** [comment]
Having the same issue. Did you figure it out?

**Comment by alvations** [comment]
@nschneid Regarding PEP479, it'll actually clean up the code if we get rid of `StopIteration` on generators and use:

```
from __future__ import generator_stop
```

**Comment by nschneid** [comment]
> ```
> from __future__ import generator_stop
> ```

Won't this break 2.7 compatibility? https://docs.python.org/3/library/__future__.html

**Comment by alvations** [comment]
Argh, it looks like a no-going-back PEP. 

Looks like even [Jinja goes py3.x only, dropping py2.7 support](https://www.palletsprojects.com/blog/jinja-29-released/), they have a motivation when it comes to unicode templates though. 

Maybe they'll backport it to Python2.7. Lets wait to resolve the warnings. Clearing the CI for 3.6 would be a good first step.

**Comment by stevenbird** [comment]
So, from the CI server, it looks like we do have a clean bill of health for both 2.7 and 3.6, right?

**Comment by alvations** [comment]
Yes, 2.7 and 3.6 work fine now on CI =)
