### ISSUE TITLE
Something wrong with your https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml

### ISSUE THREAD

**Issue by Zaazik** [nltk/nltk#1686]
[In xml online validator](http://www.xmlvalidation.com)  tell:
```
An error has been found! 
Click on  to jump to the error. In the document, you can point at  with your mouse to see the error message. 
Errors in file xml-schema: 
	23:	144	Attribute name "unzipped_size" associated with an element type "package" must be followed by the ' = ' character.
```
When i trying download `stopwords` in python3 
```
import nltk
nltk.download('stopwords')
```
Got error 
```
>>> import nltk
>>> nltk.download('stopwords')

Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/nltk/downloader.py", line 664, in download
    for msg in self.incr_download(info_or_id, download_dir, force):
  File "/usr/local/lib/python3.5/dist-packages/nltk/downloader.py", line 534, in incr_download
    try: info = self._info_or_id(info_or_id)
  File "/usr/local/lib/python3.5/dist-packages/nltk/downloader.py", line 508, in _info_or_id
    return self.info(info_or_id)
  File "/usr/local/lib/python3.5/dist-packages/nltk/downloader.py", line 875, in info
    self._update_index()
  File "/usr/local/lib/python3.5/dist-packages/nltk/downloader.py", line 825, in _update_index
    ElementTree.parse(compat.urlopen(self._url)).getroot())
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1184, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 596, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 23, column 143
```
In your [xml ](https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml)
`<package checksum="6f9c042774b96366c93fd0f9a9adb697" id="dolch" name="Dolch Word List" size="2116" subdir="corpora" unzip="1" unzipped_size"1917" url="https://en.wikipedia.org/wiki/Dolch_word_list" />`

**unzipped_size"1917"** must be unzipped_size="1917" 
**MISSING EQUALS SIGN**

**Comment by svfat** [comment]
Same error. Is it possible to download previous version?

**Comment by Zaazik** [comment]
@svfat  I'm catch that error on 3.2.1 ver, and upgrade to 3.2.2 and got same error

**Comment by alvations** [comment]
Sorry about it code was broke on the nltk_data side. nltk/nltk_data#70 patched it.

**Comment by maksymx** [comment]
@alvations thanks for rapid fix

**Comment by Zaazik** [comment]
@alvations tnx now its working .
**Upcoming holidays**
