### ISSUE TITLE
Getting Parse error on nltk.download('all')

### ISSUE THREAD

**Issue by ajnovice** [nltk/nltk#1688]
>>> import nltk
>>> nltk.download('all')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hi-161/Pictures/unix/local/lib/python2.7/site-packages/nltk/downloader.py", line 664, in download
    for msg in self.incr_download(info_or_id, download_dir, force):
  File "/home/hi-161/Pictures/unix/local/lib/python2.7/site-packages/nltk/downloader.py", line 534, in incr_download
    try: info = self._info_or_id(info_or_id)
  File "/home/hi-161/Pictures/unix/local/lib/python2.7/site-packages/nltk/downloader.py", line 508, in _info_or_id
    return self.info(info_or_id)
  File "/home/hi-161/Pictures/unix/local/lib/python2.7/site-packages/nltk/downloader.py", line 875, in info
    self._update_index()
  File "/home/hi-161/Pictures/unix/local/lib/python2.7/site-packages/nltk/downloader.py", line 825, in _update_index
    ElementTree.parse(compat.urlopen(self._url)).getroot())
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 23, column 143

**Comment by alvations** [comment]
Sorry about it code was broke on the `nltk_data` side. nltk/nltk_data#70 patched it.
