### ISSUE TITLE
OpenOnDemandZipFile fail to open punkt.zip on python3.x

### ISSUE THREAD

**Issue by joybinchen** [nltk/nltk#1696]
An exception raises when excuting an simple tutorial in nltk_book as the following command.
`$ python3 -c 'from nltk import word_tokenize; text = word_tokenize("And now for something completely different")'`

I think the problem is caused by the decorator @py3_data on ZipFilePathPointer.\_\_init\_\_ and OpenOnDemandZipFile.\_\_init\_\_. This decorator will append '/PY3' to the first arg, which is a a zip filepath as str, like  "\~/nltk_data/tokenizers/punkt.zip", but "~/nltk_data/tokenizers/punkt.zip/PY3" can't be opened as a zipfile.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/git/nltk/nltk/tokenize/__init__.py", line 109, in word_tokenize
    return [token for sent in sent_tokenize(text, language)
  File "/git/nltk/nltk/tokenize/__init__.py", line 93, in sent_tokenize
    tokenizer = load('tokenizers/punkt/{0}.pickle'.format(language))
  File "/git/nltk/nltk/data.py", line 808, in load
    opened_resource = _open(resource_url)
  File "/git/nltk/nltk/data.py", line 926, in _open
    return find(path_, path + ['']).open()
  File "/git/nltk/nltk/data.py", line 648, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource 'tokenizers/punkt/PY3/english.pickle' not found.
  Please use the NLTK Downloader to obtain the resource:  >>>
  nltk.download()
  Searched in:
    - '/home/joybin/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - ''
**********************************************************************
```

**Comment by alvations** [comment]
@joybinchen Just to double check, which specific Python version are you using? What is your output for 

```
python3 -c "import sys; print (sys.version)"
```

Also, did you download the `punkt` tokenizer? I.e. 

```
python -m nltk.downloader punkt
```

**Comment by joybinchen** [comment]
@alvations I'm using python3.5 on ubuntu 17.04. I'm sure I have downloaded all zip file under ~/nltk_data. I can run the case without any Exception when ~/nltk_data/tokenizers/punkt.zip is unpacked. 

```
$ python3 -c "import sys; print (sys.version)"
3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118]
```

```
$ python -m nltk.downloader punkt
/usr/lib/python3.5/runpy.py:125: RuntimeWarning: 'nltk.downloader' found in sys.modules after import of package 'nltk', but prior to execution of 'nltk.downloader'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
[nltk_data] Downloading package punkt to /home/joybin/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
```

**Comment by alvations** [comment]
What is your nltk version?

```
python3 -c "import nltk; print(nltk.__version__)
```

Also, try:

```
pip3 install -U nltk
```

**Comment by joybinchen** [comment]
It's the git master branch latest code.
```
python3 -c "import nltk; print(nltk.__version__); print(nltk)"
3.2.2
<module 'nltk' from '/git/nltk/nltk/__init__.py'>

```

**Comment by alvations** [comment]
Thanks @joybinchen for the details! Someone should look into this =)

I'll be a little busy til the end of the month.

**Comment by alvations** [comment]
@stevenbird Is there a difference on when downloading `nltk_data` in Python2 and Python3? How is the /PY3/ subpath created? Is it when downloading or unpickling? 


I've tried to find the `nltk_data/tokenizers/PY3/punkt.zip` but it doesn't exist after removing and downloading. It resides in `nltk_data/tokenizers/punkt.zip` instead.

```
~/git-stuff/nltk$ cd
~$ cd nltk_data/
~/nltk_data$ rm -rf tokenizers/punkt*
~/nltk_data$ python3

>>> import nltk
>>> nltk.download('punkt')
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/liling.tan/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
True
>>> import os
>>> os.path.exists('~/nltk_data/tokenizers/PY3/')
False
>>> exit()

~/nltk_data$ cd tokenizers/
~/nltk_data/tokenizers$ ls
punkt/     punkt.zip
```

**Comment by alvations** [comment]
This issue should be cleared in 2.7, 3.5 and 3.6.1 
CI tests clears this too. 

```
$ python3 -m nltk.downloader punkt
/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py:125: RuntimeWarning: 'nltk.downloader' found in sys.modules after import of package 'nltk', but prior to execution of 'nltk.downloader'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/liling.tan/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

~/nltk_data$ python3
Python 3.6.1 (default, Apr  4 2017, 09:40:21) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from nltk import sent_tokenize
>>> sent_tokenize('This is a foo. Bar sentence from the loo.')
['This is a foo.', 'Bar sentence from the loo.']
````

Are there anyone else having similar issues?

One issue down, preparing for #1659  =)

**Comment by stevenbird** [comment]
@alvations fyi in compat.py:

```
# The following datasets have a /PY3 subdirectory containing
# a full copy of the data which has been re-encoded or repickled.
DATA_UPDATES = [("chunkers", "maxent_ne_chunker"),
                ("help", "tagsets"),
                ("taggers", "maxent_treebank_pos_tagger"),
                ("tokenizers", "punkt")]
```

From memory these extra subdirectories were created manually.
