### ISSUE TITLE
nltk download 2.x failing on misconfigured www.nltk.org/nltk_data/

### ISSUE THREAD

**Issue by babbottscott** [nltk/nltk#1715]
panlex_lite package has been removed from the Packages list, but is still present in the third_party collection.  This is causing downloader to break with:
```python -m nltk.downloader -d /usr/lib/nltk_data all
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/nltk/downloader.py", line 2225, in <module>
    halt_on_error=options.halt_on_error)
  File "/usr/lib/python2.7/site-packages/nltk/downloader.py", line 653, in download
    for msg in self.incr_download(info_or_id, download_dir, force):
  File "/usr/lib/python2.7/site-packages/nltk/downloader.py", line 524, in incr_download
    try: info = self._info_or_id(info_or_id)
  File "/usr/lib/python2.7/site-packages/nltk/downloader.py", line 498, in _info_or_id
    return self.info(info_or_id)
  File "/usr/lib/python2.7/site-packages/nltk/downloader.py", line 861, in info
    self._update_index()
  File "/usr/lib/python2.7/site-packages/nltk/downloader.py", line 843, in _update_index
    packages[child.id] = child
AttributeError: 'str' object has no attribute 'id'
```
I've monkey patched https://github.com/nltk/nltk/blob/2.0.4/nltk/downloader.py#L840-L843 with
```
                if isinstance(child, Collection):
                    queue.extend(child.children)
                elif isinstance(child, Package):
                    packages[child.id] = child
                else:
                    pass
```
But I believe the real fix is to correct the published index.  Thank you.

**Comment by babbottscott** [comment]
Closing, and opening in the right repo..
