### ISSUE TITLE
LazyCorpusLoader doesn't play well with Zipfile in Python >3.5

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#1717]
c.f. #1716 

```python
~/git-stuff/nltk$ python
Python 2.7.13 (default, Dec 18 2016, 07:03:39) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from nltk.corpus import panlex_lite
>>> panlex_lite
<PanLexLiteCorpusReader in u'.../corpora/panlex_lite' (not loaded yet)>
>>> exit()

~/git-stuff/nltk$ python3
Python 3.5.2 (default, Oct 11 2016, 04:59:56) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from nltk.corpus import panlex_lite
>>> panlex_lite
<PanLexLiteCorpusReader in '.../corpora/panlex_lite' (not loaded yet)>
>>> panlex_lite.__getattrs__
corpora/panlex_lite
corpora.zip/corpora/panlex_lite
corpora/panlex_lite.zip/panlex_lite
corpora/panlex_lite.zip/panlex_lite/
Traceback (most recent call last):
  File "/Users/liling.tan/git-stuff/nltk/nltk/corpus/util.py", line 80, in __find
    try: root = nltk.data.find('{}/{}'.format(self.subdir, zip_name))
  File "/Users/liling.tan/git-stuff/nltk/nltk/data.py", line 649, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource 'corpora/panlex_lite.zip/panlex_lite/' not found.
  Please use the NLTK Downloader to obtain the resource:  >>>
  nltk.download()
  Searched in:
    - '/Users/liling.tan/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/liling.tan/git-stuff/nltk/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/liling.tan/git-stuff/nltk/nltk/corpus/util.py", line 86, in __load
    root = self.__find()
  File "/Users/liling.tan/git-stuff/nltk/nltk/corpus/util.py", line 81, in __find
    except LookupError: raise e
  File "/Users/liling.tan/git-stuff/nltk/nltk/corpus/util.py", line 78, in __find
    root = nltk.data.find('{}/{}'.format(self.subdir, self.__name))
  File "/Users/liling.tan/git-stuff/nltk/nltk/data.py", line 649, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource 'corpora/panlex_lite' not found.  Please use the NLTK
  Downloader to obtain the resource:  >>> nltk.download()
  Searched in:
    - '/Users/liling.tan/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
```

**Comment by alvations** [comment]
To accomodate the test, the easy fix would just be to comment out `panlex_lite` at https://github.com/nltk/nltk/blob/develop/nltk/corpus/__init__.py#L166 

But the lazy loading modules is a deeper problem and it should be fixed since it's causing more pain in python3.6
