### ISSUE TITLE
ImportError: cannot import name 'format_exception_only'

### ISSUE THREAD

**Issue by July541** [nltk/nltk#1752]
An error occurred when I import nltk.
Please tell me what I should do, thanks.

``` python
>>> import nltk
Traceback (most recent call last):
  File "/usr/lib/python3.5/subprocess.py", line 441, in <module>
    import threading
  File "/usr/lib/python3.5/threading.py", line 7, in <module>
    from traceback import format_exc as _format_exc
  File "/usr/lib/python3.5/traceback.py", line 5, in <module>
    import linecache
  File "/usr/lib/python3.5/linecache.py", line 11, in <module>
    import tokenize
  File "/home/july/PythonProjects/test/tokenize.py", line 3, in <module>
    from nltk.tokenize import regexp_tokenize, wordpunct_tokenize, blankline_tokenize
  File "/usr/local/lib/python3.5/dist-packages/nltk/tokenize/__init__.py", line 67, in <module>
    from nltk.tokenize.mwe      import MWETokenizer
  File "/usr/local/lib/python3.5/dist-packages/nltk/tokenize/mwe.py", line 31, in <module>
    from nltk.util import Trie
  File "/usr/local/lib/python3.5/dist-packages/nltk/util.py", line 15, in <module>
    import pydoc
  File "/usr/lib/python3.5/pydoc.py", line 76, in <module>
    from traceback import format_exception_only
ImportError: cannot import name 'format_exception_only'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/nltk/__init__.py", line 89, in <module>
    from nltk.internals import config_java
  File "/usr/local/lib/python3.5/dist-packages/nltk/internals.py", line 11, in <module>
    import subprocess
  File "/usr/lib/python3.5/subprocess.py", line 443, in <module>
    import dummy_threading as threading
  File "/usr/lib/python3.5/dummy_threading.py", line 45, in <module>
    import threading
  File "/usr/lib/python3.5/threading.py", line 7, in <module>
    from traceback import format_exc as _format_exc
  File "/usr/lib/python3.5/traceback.py", line 5, in <module>
    import linecache
  File "/usr/lib/python3.5/linecache.py", line 11, in <module>
    import tokenize
  File "/home/july/PythonProjects/test/tokenize.py", line 3, in <module>
    from nltk.tokenize import regexp_tokenize, wordpunct_tokenize, blankline_tokenize
  File "/usr/local/lib/python3.5/dist-packages/nltk/tokenize/__init__.py", line 67, in <module>
    from nltk.tokenize.mwe      import MWETokenizer
  File "/usr/local/lib/python3.5/dist-packages/nltk/tokenize/mwe.py", line 31, in <module>
    from nltk.util import Trie
  File "/usr/local/lib/python3.5/dist-packages/nltk/util.py", line 15, in <module>
    import pydoc
  File "/usr/lib/python3.5/pydoc.py", line 76, in <module>
    from traceback import format_exception_only
ImportError: cannot import name 'format_exception_only'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3.5/subprocess.py", line 441, in <module>
    import threading
  File "/usr/lib/python3.5/threading.py", line 7, in <module>
    from traceback import format_exc as _format_exc
ImportError: cannot import name 'format_exc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 62, in apport_excepthook
    import re, traceback
  File "/usr/lib/python3.5/traceback.py", line 5, in <module>
    import linecache
  File "/usr/lib/python3.5/linecache.py", line 11, in <module>
    import tokenize
  File "/home/july/PythonProjects/test/tokenize.py", line 3, in <module>
    from nltk.tokenize import regexp_tokenize, wordpunct_tokenize, blankline_tokenize
  File "/usr/local/lib/python3.5/dist-packages/nltk/__init__.py", line 89, in <module>
    from nltk.internals import config_java
  File "/usr/local/lib/python3.5/dist-packages/nltk/internals.py", line 11, in <module>
    import subprocess
  File "/usr/lib/python3.5/subprocess.py", line 443, in <module>
    import dummy_threading as threading
  File "/usr/lib/python3.5/dummy_threading.py", line 45, in <module>
    import threading
  File "/usr/lib/python3.5/threading.py", line 7, in <module>
    from traceback import format_exc as _format_exc
ImportError: cannot import name 'format_exc'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3.5/subprocess.py", line 441, in <module>
    import threading
  File "/usr/lib/python3.5/threading.py", line 7, in <module>
    from traceback import format_exc as _format_exc
  File "/usr/lib/python3.5/traceback.py", line 5, in <module>
    import linecache
  File "/usr/lib/python3.5/linecache.py", line 11, in <module>
    import tokenize
  File "/home/july/PythonProjects/test/tokenize.py", line 3, in <module>
    from nltk.tokenize import regexp_tokenize, wordpunct_tokenize, blankline_tokenize
  File "/usr/local/lib/python3.5/dist-packages/nltk/tokenize/__init__.py", line 67, in <module>
    from nltk.tokenize.mwe      import MWETokenizer
  File "/usr/local/lib/python3.5/dist-packages/nltk/tokenize/mwe.py", line 31, in <module>
    from nltk.util import Trie
  File "/usr/local/lib/python3.5/dist-packages/nltk/util.py", line 15, in <module>
    import pydoc
  File "/usr/lib/python3.5/pydoc.py", line 76, in <module>
    from traceback import format_exception_only
ImportError: cannot import name 'format_exception_only'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/nltk/__init__.py", line 89, in <module>
    from nltk.internals import config_java
  File "/usr/local/lib/python3.5/dist-packages/nltk/internals.py", line 11, in <module>
    import subprocess
  File "/usr/lib/python3.5/subprocess.py", line 443, in <module>
    import dummy_threading as threading
  File "/usr/lib/python3.5/dummy_threading.py", line 45, in <module>
    import threading
  File "/usr/lib/python3.5/threading.py", line 7, in <module>
    from traceback import format_exc as _format_exc
  File "/usr/lib/python3.5/traceback.py", line 5, in <module>
    import linecache
  File "/usr/lib/python3.5/linecache.py", line 11, in <module>
    import tokenize
  File "/home/july/PythonProjects/test/tokenize.py", line 3, in <module>
    from nltk.tokenize import regexp_tokenize, wordpunct_tokenize, blankline_tokenize
  File "/usr/local/lib/python3.5/dist-packages/nltk/tokenize/__init__.py", line 67, in <module>
    from nltk.tokenize.mwe      import MWETokenizer
  File "/usr/local/lib/python3.5/dist-packages/nltk/tokenize/mwe.py", line 31, in <module>
    from nltk.util import Trie
  File "/usr/local/lib/python3.5/dist-packages/nltk/util.py", line 15, in <module>
    import pydoc
  File "/usr/lib/python3.5/pydoc.py", line 76, in <module>
    from traceback import format_exception_only
ImportError: cannot import name 'format_exception_only'

```

**Comment by July541** [comment]
It can work after I restart terminal. I don't know why.

**Comment by July541** [comment]
I made a mistake, sorry.
If anyone use `from nltk.tokenize import sent_tokenize` in ide with an error, you may can try run it in console.

**Comment by Prudenceyyx** [comment]
>  File "/home/july/PythonProjects/test/tokenize.py", line 3, in <module>
>     from nltk.tokenize import regexp_tokenize, wordpunct_tokenize, blankline_tokenize

There happen to be another script with the same name Python is looking for. Python got confused about the script from package and your own script because it start searching from the folder where you are.
So just change your own script to another name.

**Comment by randidwiputra** [comment]
My script name is tokenize.py too and error when running. Thanks dude

**Comment by temuujinya** [comment]
> > File "/home/july/PythonProjects/test/tokenize.py", line 3, in 
> > from nltk.tokenize import regexp_tokenize, wordpunct_tokenize, blankline_tokenize
> 
> There happen to be another script with the same name Python is looking for. Python got confused about the script from package and your own script because it start searching from the folder where you are.
> So just change your own script to another name.

saved my life omg, after just changed my python script file name
