### ISSUE TITLE
MWE tokenizer doesnt support pickling

### ISSUE THREAD

**Issue by rmdort** [nltk/nltk#1761]
You can reproduce this as follows on python 2.7.11

````
from nltk.tokenize import MWETokenizer
import pickle

tokenizer = MWETokenizer([('a', 'little'), ('a', 'little', 'bit'), ('a', 'lot')])

with open('tokenizer.pkl', 'wb') as f:
    pickle.dump(tokenizer, f)

with open('tokenizer.pkl', 'rb') as f:
    t = pickle.load(f)

````

Error that i am getting is

````
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-47-205693e12b16> in <module>()
      1 with open('tokenizer.pkl', 'rb') as f:
----> 2     t = pickle.load(f)

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.pyc in load(file)
   1382 
   1383 def load(file):
-> 1384     return Unpickler(file).load()
   1385 
   1386 def loads(str):

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.pyc in load(self)
    862             while 1:
    863                 key = read(1)
--> 864                 dispatch[key](self)
    865         except _Stop, stopinst:
    866             return stopinst.value

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.pyc in load_reduce(self)
   1137         args = stack.pop()
   1138         func = stack[-1]
-> 1139         value = func(*args)
   1140         stack[-1] = value
   1141     dispatch[REDUCE] = load_reduce

/Users/vinay/Sites/nltk_mwe/.env/lib/python2.7/site-packages/nltk/collections.pyc in __init__(self, strings)
    611         defaultdict.__init__(self, Trie)
    612         if strings:
--> 613             for string in strings:
    614                 self.insert(string)
    615 

TypeError: 'type' object is not iterable
````

**Comment by Dobatymo** [comment]
The problem is with the `Trie` data structure in `nltk.util`.

```python
from collections import defaultdict
import pickle

class Trie(defaultdict):
    def __init__(self, strings=None):
        defaultdict.__init__(self, Trie)
        assert not isinstance(strings, type)

trie = Trie([1])

print("pickle")
s = pickle.dumps(trie)
print("unpickle")
trie = pickle.loads(s)
```
```
pickle
unpickle
Traceback (most recent call last):
  File "mwe.py", line 14, in <module>
    trie = pickle.loads(s)
  File "mwe.py", line 7, in __init__
    assert not isinstance(strings, type)
AssertionError
```

Tested 2.7 and 3.5, both show same behavior.
