### ISSUE TITLE
Documentation of how and what of NLTK pre-trained models

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#1783]
There are several pre-trained models that NLTK provides and it is unclear
 
 - what the models are trained on 
 - how the models are trained

These pre-trained models include:

 - `sent_tokenize`: Punkt sentence tokenizers trained on _____ using  `nltk.tokenize.punkt.PunktSentenceTokenizer` with ____ settings/parameters 

 - `pos_tag`: @honnibal 's perceptron POS tagger trained on ____  using `nltk.tag.perceptron.PerceptronTagger` with ____ settings/parameters 

 - `ne_tag`: Named entity tagger trained on ____ (is it ACE? If so, which ACE?) using `nltk.classify.maxent.MaxentClassifier` with ____ settings/parameters?

It would be great if anyone knows about the ____ information above and help answer this issue. And it'll be awesome if it gets documented somewhere so that we avoid another wave of https://news.ycombinator.com/item?id=10173669 and https://explosion.ai/blog/dead-code-should-be-buried ;P

**Comment by honnibal** [comment]
`pos_tag`: Trained on Sections 00-18 of the Wall Street Journal sections of OntoNotes 5. From memory, evaluation figures refer to Sections 22-24 (the standard test set for WSJ).

Data: https://catalog.ldc.upenn.edu/ldc2013t19
Algorithm: https://explosion.ai/blog/part-of-speech-pos-tagger-in-python

It might be nice to train on the Universal Dependencies data.

If you're describing performance, it might be worth mentioning somewhere that the tagging algorithm used is still an OK choice for English, but won't do very well for languages like Russian or Arabic. Neural network methods can do much better for morphologically rich languages, if the network has good subword features.

**Comment by alvations** [comment]
I noticed that other than the `maxent_ne_chunker` used by `nltk.ne_chunk`. 

There are 2 other chunkers in `nltk_data`:

 - treebank.chunker.pickle.gz: Seems to come from a [really old commit]( https://github.com/nltk/nltk/commit/5e54d5345d4ae6387bd640e5363994e70b753135) without much documentation
 - muc6.chunk.tagger.pickle.gz: Also from a [really old commit](https://github.com/nltk/nltk/commit/aca17ef93d2746e25d44bff3b1f0d9436089e271)

It'll be good to understand what they are and whether they are still relevant to the current NLTK code based. 

If they are still relevant, we should somehow document what they're trained on and how they trained. Otherwise, I think it's better to remove them from `nltk_data`

@jfrazee It'll be great if you could help to tell us more about these chunkers =)

**Comment by alvations** [comment]
There's an expository post on the  `ne_chunk` models on http://mattshomepage.com/articles/2016/May/23/nltk_nec/ . 

The pickled object is an  `NEChunkParser`:

```
>>> nltk.data.load('chunkers/maxent_ne_chunker/english_ace_binary.pickle')
<nltk.chunk.named_entity.NEChunkParser object at 0x7f92fe245290>
```

But it'll be great if anyone knows how the `maxent_ne_chunker` were created confirms which corpus and how the model was trained (i.e. what features/parameters, etc.)

Also, is it trained on [ACE 2004](https://catalog.ldc.upenn.edu/LDC2005T09)?

**Comment by jfrazee** [comment]
@alvations I'd be really surprised if the Treebank and MUC6 chunker models still work, considering that pickling is so tightly coupled to the class definitions, and that at the time it would have been like python 2.4 or 2.6. They should be pickles of either the HMM and MEMM classes or the NEChunkParser, possibly along with a feature extractor. It's possible the extractor might have just been a lambda or it could have been a class from some long abandoned code in contrib. Sorry if that's not super helpful.

They were basic BIO style taggers, trained on the standard training sections of PTB and MUC6.

The hard part of creating these in the first place was really getting the HMM and MEMM code so the models pickle correctly, so presuming the current NLTK codebase produces objects that serialize ok, I don't think there's much (anything?) lost by just declaring bankruptcy on these models and re-training on newer datasets and keeping better records.

As this sort of demonstrates, serialized objects (in any language) are an awful model serialization format, but, yeah, we all do it.

**Comment by alvations** [comment]
@jfrazee Thanks for the answer! Unpickling the MUC6 and Treebank chunkers is not possible in Python2.7 =(

```
Python 2.7.13 (default, Dec 18 2016, 07:03:39) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pickle
>>> pickle.load('muc6.chunk.tagger.pickle')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 847, in __init__
    self.readline = file.readline
AttributeError: 'str' object has no attribute 'readline'
```

@stevenbird I think it's safe to remove them from `nltk_data`.

**Comment by alvations** [comment]
From #428,  we should also remove `hmm_treebank_pos_tagger` model too.

**Comment by Catadanna** [comment]
Has anyone information on pre-trained nltk chunkers in English? NLTK version 3.2.4 and of course Python 3.
