### ISSUE TITLE
'EnglishStemmer' has no attribute 'stematize'

### ISSUE THREAD

**Issue by alessandrojcm** [nltk/nltk#1801]
So I'm trying to use the `SnowballStemmer` and I'm getting this error. From the Python 3.6.2 REPL:

```python
>>>from nltk.stem import SnowballStemmer
>>>stemmer = SnowballStemmer('english')

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/virtualenvpath/python3.6/site-packages/nltk/stem/snowball.py", line 93, in __init__
    self.stem = self.stemmer.stematize
AttributeError: 'EnglishStemmer' object has no attribute 'stematize'
```

I've tried with spanish, german and danish at it throws the same error with the corresponding stemmer class.

This is taken right from the NLTK Docs page. Is this a bug or I am missing something?

**Comment by alessandrojcm** [comment]
Well, I recreated the virtualenv and it worked; that's weird. Anyway, sorry for bothering.
