### ISSUE TITLE
nltk.download('stop_words') broken: ParseError: not well-formed

### ISSUE THREAD

**Issue by walkingpendulum** [nltk/nltk#1832]
Hi!

```bash 
$ python
Python 2.7.9 (default, Jun 29 2016, 13:08:31)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk; nltk.download('stop_words')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/nltk/downloader.py", line 665, in download
    for msg in self.incr_download(info_or_id, download_dir, force):
  File "/usr/lib/python2.7/dist-packages/nltk/downloader.py", line 535, in incr_download
    try: info = self._info_or_id(info_or_id)
  File "/usr/lib/python2.7/dist-packages/nltk/downloader.py", line 509, in _info_or_id
    return self.info(info_or_id)
  File "/usr/lib/python2.7/dist-packages/nltk/downloader.py", line 873, in info
    self._update_index()
  File "/usr/lib/python2.7/dist-packages/nltk/downloader.py", line 826, in _update_index
    ElementTree.parse(compat.urlopen(self._url)).getroot())
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
```

Versions bug submitted: 3.0.0, 3.2.4

**Comment by alvations** [comment]
@walkingpendulum Did you get the same error when you do `nltk.download('stopwords')`?

That should be the correct name to download the stopwords, i.e. without the underscore.

Nevertheless, the XML should be well-formed even when the name is wrong, you should see this instead.

```
>>> import nltk
>>> nltk.download('stopwords')
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/liling.tan/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
True

>>> nltk.download('stop_words')
[nltk_data] Error loading stop_words: Package 'stop_words' not found
[nltk_data]     in index
False
```


**Could you do try this and tell us whether you get an error?**

```
>>> from xml.etree import ElementTree
>>> import requests
>>> index_xml = requests.get('https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml').content
>>> ElementTree.fromstring(index_xml)
<Element 'nltk_data' at 0x10df2e548>
```

If the above throws an error, could you tell us the output of this:

```
>>> import requests
>>> index_xml = requests.get('https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml').content
>>> print(index_xml)
```

**Comment by walkingpendulum** [comment]
@alvations thank you for fast reply!

```python
In [1]: from xml.etree import ElementTree

In [2]: import requests

In [3]: index_xml = requests.get('https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml').content

In [4]: ElementTree.fromstring(index_xml)
Out[4]: <Element 'nltk_data' at 0x7fe65e226d90>

In [5]: import nltk; nltk.download('stopwords')
  File "<string>", line unknown
ParseError: not well-formed (invalid token): line 1, column 0
```

**Comment by walkingpendulum** [comment]
Today everything works fine. Don't know what was this ¯\_(ツ)_/¯

**Comment by tdekelver** [comment]
Hi, I'm having the same issue today, and it was always working before this and I did not change anything to my environment. What should I do? I tried both via the command line or via the code

```python -m nltk.downloader stopwords
C:\ProgramData\Internal\Anaconda3\envs\SAM3.7\lib\runpy.py:125: RuntimeWarning: 'nltk.downloader' found in sys.modules after import 
of package 'nltk', but prior to execution of 'nltk.downloader'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Traceback (most recent call last):
  File "C:\ProgramData\Internal\Anaconda3\envs\SAM3.7\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Internal\Anaconda3\envs\SAM3.7\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Internal\Anaconda3\envs\SAM3.7\lib\site-packages\nltk\downloader.py", line 2538, in <module>    
    halt_on_error=options.halt_on_error,
  File "C:\ProgramData\Internal\Anaconda3\envs\SAM3.7\lib\site-packages\nltk\downloader.py", line 779, in download     
    for msg in self.incr_download(info_or_id, download_dir, force):
  File "C:\ProgramData\Internal\Anaconda3\envs\SAM3.7\lib\site-packages\nltk\downloader.py", line 629, in incr_download
    info = self._info_or_id(info_or_id)
  File "C:\ProgramData\Internal\Anaconda3\envs\SAM3.7\lib\site-packages\nltk\downloader.py", line 602, in _info_or_id  
    return self.info(info_or_id)
  File "C:\ProgramData\Internal\Anaconda3\envs\SAM3.7\lib\site-packages\nltk\downloader.py", line 1011, in info
    self._update_index()
  File "C:\ProgramData\Internal\Anaconda3\envs\SAM3.7\lib\site-packages\nltk\downloader.py", line 954, in _update_index
    ElementTree.parse(urlopen(self._url)).getroot()
  File "C:\ProgramData\Internal\Anaconda3\envs\SAM3.7\lib\xml\etree\ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "C:\ProgramData\Internal\Anaconda3\envs\SAM3.7\lib\xml\etree\ElementTree.py", line 598, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: mismatched tag: line 18, column 2```

**Comment by tomaarsen** [comment]
@tdekelver Hello!

I'm unable to reproduce this, sadly:
```python
> python -m nltk.downloader stopwords
...: RuntimeWarning: 'nltk.downloader' found in sys.modules after import of package 'nltk', but prior to execution of 'nltk.downloader'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
[nltk_data] Downloading package stopwords to
[nltk_data]     [sic]\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
```

Perhaps you can let us know which command you used, which NLTK version you're using, and what Python version you're on (presumably 3.7?)
By the way, the RuntimeWarning can safely be ignored.

**Comment by tdekelver** [comment]
@tomaarsen Hi !

Thanks for the reply. Here you can find the info asked:

This is on a Windows pc:
```
Python 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
>>> nltk.__version__
'3.5'
>>> nltk.download('stopwords')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Internal\Anaconda3\envs\SAM3.7\lib\site-packages\nltk\downloader.py", line 779, in download
    for msg in self.incr_download(info_or_id, download_dir, force):
    info = self._info_or_id(info_or_id)
  File "C:\ProgramData\Internal\Anaconda3\envs\SAM3.7\lib\site-packages\nltk\downloader.py", line 602, in _info_or_id
    return self.info(info_or_id)
  File "C:\ProgramData\Internal\Anaconda3\envs\SAM3.7\lib\site-packages\nltk\downloader.py", line 1011, in info
    self._update_index()
  File "C:\ProgramData\Internal\Anaconda3\envs\SAM3.7\lib\site-packages\nltk\downloader.py", line 954, in _update_index
    ElementTree.parse(urlopen(self._url)).getroot()
  File "C:\ProgramData\Internal\Anaconda3\envs\SAM3.7\lib\xml\etree\ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "C:\ProgramData\Internal\Anaconda3\envs\SAM3.7\lib\xml\etree\ElementTree.py", line 598, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: mismatched tag: line 18, column 2
```

Weirdly on a linux virtual machine with the same nltk version (other python version) I don't have the issue:
![image](https://user-images.githubusercontent.com/33689424/149284249-94dc3064-91a0-40b3-a6b3-1115187b4b28.png)

**Comment by tomaarsen** [comment]
@tdekelver That is indeed odd. 
I've tried to reproduce your issue, but couldn't, sadly:
```python
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
>>> nltk.__version__
'3.5'
>>> nltk.download("stopwords")
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Tom\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
True
>>>
```

To give you a bit more information on the topic: NLTK Downloads the data from https://github.com/nltk/nltk_data, where the data can be accessed via GitHub Pages. The "main" file for this is https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml, which contains info on all of the data that can be downloaded. It seems that your Windows version is unable to parse this file after it is `urlopen`-ed. However, if I manually visit that index.xml link, and validate the XML, then there are no issues reported.
However, considering that this file seems to be fine (otherwise it would also break for others), perhaps the result of `urlopen(self._url)` is not correct in these lines:
https://github.com/nltk/nltk/blob/3f74ac55681667d7ef78b664557487145f51eb02/nltk/downloader.py#L950-L954

This code was written 14 years ago. To give you an idea, this is before Python 3.0 even released. That would explain why it doesn't follow the "modern" strategy of checking whether the file was even downloaded successfully. I suspect that `urlopen(self._url)` is not working correctly on your Windows devide.

Perhaps you can verify this by running the following lines:
```python
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib.request import urlopen
>>> response = urlopen("https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml")
>>> response.status
200
>>> response.read()[:100]
b'<?xml version="1.0"?>\n<?xml-stylesheet href="index.xsl" type="text/xsl"?>\n<nltk_data>\n  <packages>\n '
```

**Comment by tdekelver** [comment]
Hi @tomaarsen,

Thanks for the explanation. This indeed clarified the issue:
```
Python 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib.request import urlopen
>>> response = urlopen("https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml")
>>> response.status
200
>>> response.read()[:570]
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\n\n<!--//////////////////////////////////////////////////////////////////////////\n//\n//\tCopyright (c) 1996 - 2017, Forcepoint LLC. All Rights Reserved.\n//\tSee Copyright.txt for copyright information.\n//\n///////////////////////////////////////////////////////////////////////////-->\n\n<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\n<title>Access to this site is blocked</title>
```

As you can see we get an error message saying that the access to this site is blocked in our company policy. Weirdly this was not the case before and is the case now, and on the linux machine it was not behind the same company policy which is why it worked correctly.

Thanks for the help,
Kind regards,
Thomas

**Comment by tomaarsen** [comment]
Wonderful! Mystery solved. 
nltk_data downloads are generally just one-time use things, so you might be able to transfer `stopwords.zip` to `C:\Users\...\AppData\Roaming\nltk_data\corpora\stopwords.zip` in some way, and then unzip it to create a `C:\Users\...\AppData\Roaming\nltk_data\corpora\stopwords` folder. NLTK should then be able to recognise it.

Hope this helped.
