### ISSUE TITLE
Missing corpus reader for PIL

### ISSUE THREAD

**Issue by alvations** [nltk/nltk#1851]
The PIL data was added quite some time ago from https://github.com/nltk/nltk/commit/ef144a94479de5536fc860c00f4f14e0a62787e4 but there's no corpus reader for it. 

Reported on https://stackoverflow.com/q/46650761/610569 

Simply using the XMLCorpusReader is not enough too:

```
>>> from nltk.corpus.reader import XMLCorpusReader
>>> from nltk.corpus.util import LazyCorpusLoader
>>> LazyCorpusLoader('pil',  XMLCorpusReader, r'(?!\.).*\.sgml')
<XMLCorpusReader in '.../corpora/pil' (not loaded yet)>

>>> pil.raw()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/nltk/corpus/reader/xmldocs.py", line 84, in raw
    return concat([self.open(f).read() for f in fileids])
  File "/usr/local/lib/python3.5/dist-packages/nltk/corpus/reader/xmldocs.py", line 84, in <listcomp>
    return concat([self.open(f).read() for f in fileids])
  File "/usr/local/lib/python3.5/dist-packages/nltk/data.py", line 1110, in read
    chars = self._read(size)
  File "/usr/local/lib/python3.5/dist-packages/nltk/data.py", line 1380, in _read
    chars, bytes_decoded = self._incr_decode(bytes)
  File "/usr/local/lib/python3.5/dist-packages/nltk/data.py", line 1411, in _incr_decode
    return self.decode(bytes, 'strict')
  File "/usr/lib/python3.5/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 9209: invalid start byte

>>> pil.words()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/nltk/corpus/reader/xmldocs.py", line 66, in words
    elt = self.xml(fileid)
  File "/usr/local/lib/python3.5/dist-packages/nltk/corpus/reader/xmldocs.py", line 47, in xml
    raise TypeError('Expected a single file identifier string')
TypeError: Expected a single file identifier string

```

**Comment by almaleksia** [comment]
@alvations I looked into this issue - there are several problems.  First two errors  you reported  look easy to fix:  
1) looks like encoding is detected incorrecly for this corpus by xml parser, can be solved by  passing encoding to parser explicitly.
2) can be fixed by supporting multiple files

But I tried to parse single file and got this:
`>>> pil.words('Zovirax_Cream.sgml')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tomcat/venv-p3/lib/python3.6/site-packages/nltk/corpus/reader/xmldocs.py", line 66, in words
    elt = self.xml(fileid)
  File "/home/tomcat/venv-p3/lib/python3.6/site-packages/nltk/corpus/reader/xmldocs.py", line 49, in xml
    elt = ElementTree.parse(self.abspath(fileid).open()).getroot()
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 3, column 38
`
There are some messy attributes in the file that I managed to parse only with bs4. Probably I overlooked something but currently nltk does not depend on bs4 and I'm not sure if it's acceptable to introduce this dependency.

So solving this issue seems not so trivial at the end :)  
Would you suggest something?
