### ISSUE TITLE
Test failures in wordnet.doctest

### ISSUE THREAD

**Issue by jacksonllee** [nltk/nltk#1853]
From the latest https://github.com/nltk/nltk/commit/0477ceb2a3ab9f4c0abc0f800a827c92e8d48623 of the `develop` branch, I ran tests locally and got three failures from `wordnet.doctest`:

```
1) FAIL: Doctest: wordnet.doctest
----------------------------------------------------------------------
   Traceback (most recent call last):
    /usr/lib/python3.5/doctest.py line 2190 in runTest
      raise self.failureException(self.format_failure(new.getvalue()))
   AssertionError: Failed doctest test for wordnet.doctest
     File "<path-to-nltk>/nltk/nltk/test/wordnet.doctest", line 0
   
   ----------------------------------------------------------------------
   File "<path-to-nltk>/nltk/nltk/test/wordnet.doctest", line 50, in wordnet.doctest
   Failed example:
       sorted(wn.langs()) # doctest: +NORMALIZE_WHITESPACE
   Expected:
       ['als', 'arb', 'bul', 'cat', 'cmn', 'dan', 'ell', 'eng', 'eus', 'fas', 'fin', 'fra', 'glg', 'heb', 'hrv', 'ind', 
       'ita', 'jpn', 'nno', 'nob', 'pol', 'por', 'qcn', 'slv', 'spa', 'swe', 'tha', 'zsm']
   Got:
       ['als', 'arb', 'cat', 'cmn', 'dan', 'eng', 'eng', 'eus', 'fas', 'fin', 'fra', 'fre', 'glg', 'heb', 'ind', 'ita', 'jpn', 'nno', 'nob', 'pol', 'por', 'spa', 'tha', 'zsm']
   ----------------------------------------------------------------------
   File "<path-to-nltk>/nltk/nltk/test/wordnet.doctest", line 64, in wordnet.doctest
   Failed example:
       wn.lemmas('cane', lang='ita') # doctest: +NORMALIZE_WHITESPACE
   Expected:
       [Lemma('dog.n.01.cane'), Lemma('cramp.n.02.cane'), Lemma('hammer.n.01.cane'), Lemma('bad_person.n.01.cane'), 
       Lemma('incompetent.n.01.cane')]
   Got:
       [Lemma('dog.n.01.cane'), Lemma('hammer.n.01.cane'), Lemma('cramp.n.02.cane'), Lemma('bad_person.n.01.cane'), Lemma('incompetent.n.01.cane')]
   ----------------------------------------------------------------------
   File "<path-to-nltk>/nltk/nltk/test/wordnet.doctest", line 79, in wordnet.doctest
   Failed example:
       len(wordnet.all_lemma_names(pos='n', lang='jpn'))
   Expected:
       64797
   Got:
       66027
```

The exact same three failures were observed with `tox -e py27` and `tox -e py35` (shown above is from py35).

Two peculiarities:
1. Inconsistency between nltk/nltk and nltk/nltk.github.com: The third failure for `len(wordnet.all_lemma_names(pos='n', lang='jpn'))` shows that [`wordnet.doctest` says 64797](https://github.com/nltk/nltk/blob/0477ceb2a3ab9f4c0abc0f800a827c92e8d48623/nltk/test/wordnet.doctest#L80), but the test got 66027, which is exactly what the NLTK how-to page says from [the underlying HTML](https://github.com/nltk/nltk.github.com/blob/fbd8429d14f9e681b0877c7a3d64e31d6144367b/howto/wordnet.html#L423). This makes me think there's reason to believe what I've observed is real, but...
2. Curiously, these test failures are _not_ observed on the Jenkin CI builds, e.g., in [this recent run](https://nltk.ci.cloudbees.com/job/pull_request_tests/442/TOXENV=py35-jenkins,jdk=jdk8latestOnlineInstall/console) associated with #1848 that I'm working on.

Because of these, I've hesitated to submit a PR to fix what seems to be straightforward, in case there's more story behind and I've missed something.

**Comment by alvations** [comment]
Also, equality of list should be checked rather than the string representation:

```
~/git-stuff/nltk$ python -m doctest nltk/corpus/reader/wordnet.py
**********************************************************************
File "nltk/corpus/reader/wordnet.py", line 527, in wordnet.Synset.closure
Failed example:
    list(dog.closure(hyp))
Expected:
    [Synset('canine.n.02'), Synset('domestic_animal.n.01'),
    Synset('carnivore.n.01'), Synset('animal.n.01'),
    Synset('placental.n.01'), Synset('organism.n.01'),
    Synset('mammal.n.01'), Synset('living_thing.n.01'),
    Synset('vertebrate.n.01'), Synset('whole.n.02'),
    Synset('chordate.n.01'), Synset('object.n.01'),
    Synset('physical_entity.n.01'), Synset('entity.n.01')]
Got:
    [Synset('canine.n.02'), Synset('domestic_animal.n.01'), Synset('carnivore.n.01'), Synset('animal.n.01'), Synset('placental.n.01'), Synset('organism.n.01'), Synset('mammal.n.01'), Synset('living_thing.n.01'), Synset('vertebrate.n.01'), Synset('whole.n.02'), Synset('chordate.n.01'), Synset('object.n.01'), Synset('physical_entity.n.01'), Synset('entity.n.01')]
**********************************************************************
1 items had failures:
   1 of   4 in wordnet.Synset.closure
***Test Failed*** 1 failures.
```

And 

```
~/git-stuff/nltk$ python -m doctest nltk/test/wordnet.doctest 
**********************************************************************
File "nltk/test/wordnet.doctest", line 50, in wordnet.doctest
Failed example:
    sorted(wn.langs()) # doctest: +NORMALIZE_WHITESPACE
Expected:
    ['als', 'arb', 'bul', 'cat', 'cmn', 'dan', 'ell', 'eng', 'eus', 'fas', 'fin', 'fra', 'glg', 'heb', 'hrv', 'ind', 
    'ita', 'jpn', 'nno', 'nob', 'pol', 'por', 'qcn', 'slv', 'spa', 'swe', 'tha', 'zsm']
Got:
    [u'als', u'arb', u'bul', u'cat', u'cmn', u'dan', u'ell', u'eng', u'eus', u'fas', u'fin', u'fra', u'glg', u'heb', u'hrv', u'ind', u'ita', u'jpn', u'nno', u'nob', u'pol', u'por', u'qcn', u'slv', u'spa', u'swe', u'tha', u'zsm']
**********************************************************************
File "nltk/test/wordnet.doctest", line 62, in wordnet.doctest
Failed example:
    wn.synset('dog.n.01').lemma_names('ita')
Expected:
    ['cane', 'Canis_familiaris']
Got:
    [u'cane', u'Canis_familiaris']
**********************************************************************
File "nltk/test/wordnet.doctest", line 140, in wordnet.doctest
Failed example:
    for lemma in wn.synset('eat.v.03').lemmas():
        print(lemma, lemma.count())
Expected:
    Lemma('feed.v.06.feed') 3
    Lemma('feed.v.06.eat') 4
Got:
    (Lemma('feed.v.06.feed'), 3)
    (Lemma('feed.v.06.eat'), 4)
**********************************************************************
File "nltk/test/wordnet.doctest", line 145, in wordnet.doctest
Failed example:
    for lemma in wn.lemmas('eat', 'v'):
        print(lemma, lemma.count())
Expected:
    Lemma('eat.v.01.eat') 61
    Lemma('eat.v.02.eat') 13
    Lemma('feed.v.06.eat') 4
    Lemma('eat.v.04.eat') 0
    Lemma('consume.v.05.eat') 0
    Lemma('corrode.v.01.eat') 0
Got:
    (Lemma('eat.v.01.eat'), 61)
    (Lemma('eat.v.02.eat'), 13)
    (Lemma('feed.v.06.eat'), 4)
    (Lemma('eat.v.04.eat'), 0)
    (Lemma('consume.v.05.eat'), 0)
    (Lemma('corrode.v.01.eat'), 0)
**********************************************************************
File "nltk/test/wordnet.doctest", line 173, in wordnet.doctest
Failed example:
    for lemma in wn.synset('think.v.01').lemmas():
        print(lemma, lemma.frame_ids())
        print(" | ".join(lemma.frame_strings()))
Expected:
    Lemma('think.v.01.think') [5, 9]
    Something think something Adjective/Noun | Somebody think somebody
    Lemma('think.v.01.believe') [5, 9]
    Something believe something Adjective/Noun | Somebody believe somebody
    Lemma('think.v.01.consider') [5, 9]
    Something consider something Adjective/Noun | Somebody consider somebody
    Lemma('think.v.01.conceive') [5, 9]
    Something conceive something Adjective/Noun | Somebody conceive somebody
Got:
    (Lemma('think.v.01.think'), [5, 9])
    Something think something Adjective/Noun | Somebody think somebody
    (Lemma('think.v.01.believe'), [5, 9])
    Something believe something Adjective/Noun | Somebody believe somebody
    (Lemma('think.v.01.consider'), [5, 9])
    Something consider something Adjective/Noun | Somebody consider somebody
    (Lemma('think.v.01.conceive'), [5, 9])
    Something conceive something Adjective/Noun | Somebody conceive somebody
**********************************************************************
File "nltk/test/wordnet.doctest", line 187, in wordnet.doctest
Failed example:
    for lemma in wn.synset('stretch.v.02').lemmas():
        print(lemma, lemma.frame_ids())
        print(" | ".join(lemma.frame_strings()))
Expected:
    Lemma('stretch.v.02.stretch') [8, 2]
    Somebody stretch something | Somebody stretch
    Lemma('stretch.v.02.extend') [8]
    Somebody extend something
Got:
    (Lemma('stretch.v.02.stretch'), [8, 2])
    Somebody stretch something | Somebody stretch
    (Lemma('stretch.v.02.extend'), [8])
    Somebody extend something
/Users/liling.tan/Library/Python/2.7/lib/python/site-packages/unidecode/__init__.py:46: RuntimeWarning: Argument <type 'str'> is not an unicode object. Passing an encoded string will likely have unexpected results.
  _warn_if_not_unicode(string)
**********************************************************************
File "nltk/test/wordnet.doctest", line 368, in wordnet.doctest
Failed example:
    for synset in islice(wn.all_synsets('n'), 5):
        print(synset, synset.hypernyms())
Expected:
    Synset('entity.n.01') []
    Synset('physical_entity.n.01') [Synset('entity.n.01')]
    Synset('abstraction.n.06') [Synset('entity.n.01')]
    Synset('thing.n.12') [Synset('physical_entity.n.01')]
    Synset('object.n.01') [Synset('physical_entity.n.01')]
Got:
    (Synset('entity.n.01'), [])
    (Synset('physical_entity.n.01'), [Synset('entity.n.01')])
    (Synset('abstraction.n.06'), [Synset('entity.n.01')])
    (Synset('thing.n.12'), [Synset('physical_entity.n.01')])
    (Synset('object.n.01'), [Synset('physical_entity.n.01')])
**********************************************************************
File "nltk/test/wordnet.doctest", line 549, in wordnet.doctest
Failed example:
    WordNetLemmatizer().lemmatize("eggs", pos="n")
Expected:
    'egg'
Got:
    u'egg'
**********************************************************************
File "nltk/test/wordnet.doctest", line 551, in wordnet.doctest
Failed example:
    WordNetLemmatizer().lemmatize("legs", pos="n")
Expected:
    'leg'
Got:
    u'leg'
**********************************************************************
1 items had failures:
   9 of 160 in wordnet.doctest
***Test Failed*** 9 failures.
```

**Comment by alvations** [comment]
As for the 1st two failures in the doctest failure due to `# doctest: +NORMALIZE_WHITESPACE` flag not being picked up. No worries for those failure. 

BTW, which version of `tox` did you use?

----

Regarding failure 3, the current https://github.com/nltk/nltk/commit/c0a373066e1477bd201acb071be171e8cc0ca673 `nltk_data` returns 64797 Japanese synsets lemma. The howto is a little outdated from 2 years ago, 15 Aug 2015.

Most probably the change happens when the OMW was updated on [21 Sep 2015](https://github.com/nltk/nltk_data/pull/34#issue-107465141) =)

@stevenbird how are the howtos generated? Could we regenerate them based on the doctests we currently have?

**Comment by dannysepler** [comment]
hey all! this feels almost certainly fixed now. please do re-open if you still think this is breaking
