### ISSUE TITLE
[Question] Add custom Regex to improve date recognition for tokenizer and POS tagger

### ISSUE THREAD

**Issue by k0pernicus** [nltk/nltk#1860]
I am trying to recognizing a simple kind of date ("XX/XX/XXXX") in my Python3 code.
For that, I would like to create a regex, and to add a tag for this one: "DATE" (for example). 

This is the code I wrote:
```
# Recognize month/day/year
patterns = [(r'\d{2}/\d{2}/\d{4}', 'DATE')]
# Build a tagger
reg_tagger = nltk.RegexpTagger(patterns)
default_tagger = nltk.data.load("taggers/maxent_treebank_pos_tagger/english.pickle")
# Build a tagger that add reg_tagger in an existing tagger (MaxEnt)
tagger = nltk.UnigramTagger(model=reg_tagger, backoff=default_tagger)
# Tag the words in each sentence
tags = [tagger.tag(_s) for _s in sentences]
```

Unfortunately, I got this error:
```
>>> python3.6 scripts.py examples/090003ea802cef84.txt
Traceback (most recent call last):
  File "scripts.py", line 202, in <module>
    tags = get_tags_from_sentences(sentences)
  File "scripts.py", line 50, in get_tags_from_sentences
    tags = [tagger.tag(_s) for _s in sentences]
  File "scripts.py", line 50, in <listcomp>
    tags = [tagger.tag(_s) for _s in sentences]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nltk/tag/sequential.py", line 63, in tag
    tags.append(self.tag_one(tokens, i, tags))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nltk/tag/sequential.py", line 83, in tag_one
    tag = tagger.choose_tag(tokens, index, history)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nltk/tag/sequential.py", line 142, in choose_tag
    return self._context_to_tag.get(context)
AttributeError: 'RegexpTagger' object has no attribute 'get'
```

So, my question is: is it possible to add a custom regex (for my case, to recognize dates) in a default tagger, please?

Thanks a lot

**Comment by alvations** [comment]
I'm not sure whether there's a way to combine an n-gram tagger with the regexp tagger through the `backoff` in NLTK, usually the backoff is an ngram backoff tagger or a dictionary of key-value pairs.

But here's a dirty hack, given that I think the default `pos_tag` will tag the date pattern as `CD`:

```python
from nltk import RegexpTagger
from nltk import word_tokenize, pos_tag

patterns = [(r'\d{2}/\d{2}/\d{4}', 'DATE')]
reg_tagger = RegexpTagger(patterns)

sent = 'This is a sentence with dates like 23/12/1923 and 05/11/2018'


def rule_based_tag(sent):
    reg_out = reg_tagger.tag(word_tokenize(sent))
    tag_out = pos_tag(word_tokenize(sent))
    return [(token, rtag) if rtag == 'DATE' and ttag == 'CD' else (token, ttag) for (token, rtag), (_, ttag) in zip(reg_out, tag_out)]


rule_based_tag(sent)
```

[out]:

```
[('This', 'DT'),
 ('is', 'VBZ'),
 ('a', 'DT'),
 ('sentence', 'NN'),
 ('with', 'IN'),
 ('dates', 'NNS'),
 ('like', 'IN'),
 ('23/12/1923', 'DATE'),
 ('and', 'CC'),
 ('05/11/2018', 'DATE')]
```

Drop the `and ttag == 'CD'` condition if you want less constraint and if you want to always trust the regex tagger.

I hope it helps.

**Comment by k0pernicus** [comment]
Hello @alvations,
Thank you for your help!

Your solution works well.
I implemented an other one with consists in tagging `/` characters with `SLASH`, and create a simple rule like this:
```
DATE:
         {<CD><SLASH><CD><SLASH><CD>}
         {<CD><SLASH><CD>}
```

So, now, I can recognize patterns like month/day/year, or month/year only.

**Comment by k0pernicus** [comment]
Hello @alvations,

Actually, I rewrote my parser and I did like you, using a RegexpTokenizer.
Unfortunately, I found NLTK has a strange behaviour using the following regex:

```
from nltk import RegexpTagger
from nltk import word_tokenize, pos_tag

# 'https?://\w+(?:\.\w+)+' -> Parsing an http/https URL like this http://hello.com, or http://hello.world.com, or...
patterns = [(r'\d{2}/\d{2}/\d{4}', 'DATE'), (r'https?://\w+(?:\.\w+)+', 'URL')]
reg_tagger = RegexpTagger(patterns)

sent = 'This is a sentence with dates like 23/12/1923 and 05/11/2013, and an URL like https://hello.world.com'


def rule_based_tag(sent):
    reg_out = reg_tagger.tag(word_tokenize(sent))
    tag_out = pos_tag(word_tokenize(sent))
    return [(token, rtag) if rtag == 'DATE' and ttag == 'CD' else (token, ttag) for (token, rtag), (_, ttag) in zip(reg_out, tag_out)]


rule_based_tag(sent)
```

Output:

```
[('This', 'DT'), ('is', 'VBZ'), ('a', 'DT'), ('sentence', 'NN'), ('with', 'IN'), ('dates', 'NNS'), ('like', 'IN'), ('23/12/1923', 'DATE'), ('and', 'CC'), ('05/11/2013', 'DATE'), (',', ','), ('and', 'CC'), ('an', 'DT'), ('URL', 'NNP'), ('like', 'IN'), ('https', 'NN'), (':', ':'), ('//hello.world.com', 'NN')]
```

Did I made a mistake in writing the regex for an URL?

Thanks a lot

**Comment by alvations** [comment]
That's because the regexes in `word_tokenize` didn't handle URLs correctly. 

```
>>> from nltk import word_tokenize
>>> sent = 'This is a sentence with dates like 23/12/1923 and 05/11/2013, and an URL like https://hello.world.com'
>>> word_tokenize(sent)
['This', 'is', 'a', 'sentence', 'with', 'dates', 'like', '23/12/1923', 'and', '05/11/2013', ',', 'and', 'an', 'URL', 'like', 'https', ':', '//hello.world.com']
>>> word_tokenize(sent, preserve_line=True)
['This', 'is', 'a', 'sentence', 'with', 'dates', 'like', '23/12/1923', 'and', '05/11/2013', ',', 'and', 'an', 'URL', 'like', 'https', ':', '//hello.world.com']
```

Try another tokenizer:

```
>>> from nltk.tokenize import ToktokTokenizer
>>> sent = 'This is a sentence with dates like 23/12/1923 and 05/11/2013, and an URL like https://hello.world.com'
>>> toktok = ToktokTokenizer()
>>> toktok.tokenize(sent)
[u'This', u'is', u'a', u'sentence', u'with', u'dates', u'like', u'23/12/1923', u'and', u'05/11/2013', u',', u'and', u'an', u'URL', u'like', u'https://hello.world.com']
```

Note that the `ToktokTokenizer` might come with other caveats. 

But I agree that the default treebank tokenizer should handle URL (even though the original sed version was created before web text is popular.

**Comment by k0pernicus** [comment]
Thanks a lot @alvations.

**Comment by alvations** [comment]
@k0pernicus you're welcomed. Did the answer resolved your issue/question? 

I've logged the concerned with URL and tokenization on a long standing issue at  #1860.

**Comment by k0pernicus** [comment]
Thanks @alvations 
I think it's ok now - but I didn't think NLTK was so "difficult" to use for real-world text; for examples:
```
THIS IS A TITLE OF A DOCUMENT

THIS DOCUMENT BEGINS WITH UPPERCASE and after that it's lowercase.
THE DOCUMENT BELONGS TO X CIE and bla blabla...
```
If the beginning of a sentence contains an entity ("X Cie."), it will become "x cie.", and "X" is not an entity anymore when I will tokenize it. I have many issues like that actually for "real world text".
But I am going off the point actually :-)

**Comment by k0pernicus** [comment]
Hi @alvations ,
I opened it a long time ago and, after some checks, there is no reason this issue has to stay open...

Will close it for now - feel free to reopen it for whatever reason.

Thanks again for the help 😃
