### ISSUE TITLE
Fail to install nltk==2.0.5

### ISSUE THREAD

**Issue by robsonpeixoto** [nltk/nltk#1879]
```
$ docker run --rm -it python:2.7.8 bash
# pip install  nltk==2.0.5
Downloading/unpacking nltk==2.0.5
  Downloading nltk-2.0.5.tar.gz (954kB): 954kB downloaded
  Running setup.py (path:/tmp/pip_build_root/nltk/setup.py) egg_info for package nltk
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/nltk/setup.py", line 23, in <module>
        distribute_setup.use_setuptools()
      File "distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "distribute_setup.py", line 124, in _do_download
        to_dir, download_delay)
      File "distribute_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "/usr/local/lib/python2.7/urllib2.py", line 127, in urlopen
        return _opener.open(url, data, timeout)
      File "/usr/local/lib/python2.7/urllib2.py", line 410, in open
        response = meth(req, response)
      File "/usr/local/lib/python2.7/urllib2.py", line 523, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/local/lib/python2.7/urllib2.py", line 448, in error
        return self._call_chain(*args)
      File "/usr/local/lib/python2.7/urllib2.py", line 382, in _call_chain
        result = func(*args)
      File "/usr/local/lib/python2.7/urllib2.py", line 531, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    urllib2.HTTPError: HTTP Error 403: SSL is required
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/nltk/setup.py", line 23, in <module>

    distribute_setup.use_setuptools()

  File "distribute_setup.py", line 145, in use_setuptools

    return _do_download(version, download_base, to_dir, download_delay)

  File "distribute_setup.py", line 124, in _do_download

    to_dir, download_delay)

  File "distribute_setup.py", line 193, in download_setuptools

    src = urlopen(url)

  File "/usr/local/lib/python2.7/urllib2.py", line 127, in urlopen

    return _opener.open(url, data, timeout)

  File "/usr/local/lib/python2.7/urllib2.py", line 410, in open

    response = meth(req, response)

  File "/usr/local/lib/python2.7/urllib2.py", line 523, in http_response

    'http', request, response, code, msg, hdrs)

  File "/usr/local/lib/python2.7/urllib2.py", line 448, in error

    return self._call_chain(*args)

  File "/usr/local/lib/python2.7/urllib2.py", line 382, in _call_chain

    result = func(*args)

  File "/usr/local/lib/python2.7/urllib2.py", line 531, in http_error_default

    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

urllib2.HTTPError: HTTP Error 403: SSL is required

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/nltk
Storing debug log for failure in /root/.pip/pip.log
```

**Comment by stevenbird** [comment]
Please upgrade to current version of NLTK

**Comment by 10B-B11** [comment]
same issue here.
Can anyone tell me how to fix it?

**Comment by robsonpeixoto** [comment]
@caiyajing9210 https://stackoverflow.com/questions/46977498/urllib2-httperror-http-error-403-ssl-is-required-when-installing-nltk-2-0-5#answer-46982580

**Comment by alvations** [comment]
@caiyajing9210 @robsonpeixoto you should be using the latest version of NLTK v3.2.5. 

Is there any reason why you are looking to install v2.0.5?

**Comment by robsonpeixoto** [comment]
@alvations It's a very old code that our team do not have time to migrate to nltk 3.x and check if everything will keep working.
But migration to 3.x is in our plan.

**Comment by deepakmishra** [comment]
If nltk's new version was backward compatible, there would not have been so many problems. Method signatures have changed. For example, batch_ne_chunk doesn't exist.; it is changed to ne_chunk. node attribute has changed to label. We have no choice but to use 2.0.5.

**Comment by alvations** [comment]
For this you could use the version from this patch 54ec4662be59238d957d7fc2662bb1871cb739f0:

```
pip install -U https://github.com/nltk/nltk/archive/2.0.5a.zip 
```

**Comment by alvations** [comment]
As for backwards compatibility, I think it's good for research related packages to be updated and move ahead, be it for API considerations or module extensions/enhancement. 

Moreover, v.2.0.5 is really too old for any good usage of NLTK =)

**Comment by panamantis** [comment]
newspaper uses 2.0.5 and SSL is required to install it

**Comment by dreamk73** [comment]
I just ran pip install newspaper on conda python 2.7 and still got this same error. Solved it by running:

pip install git+https://github.com/codelucas/newspaper.git@python-2-head

**Comment by pythoninthegrass** [comment]
https://github.com/idank/explainshell/issues/261#issuecomment-922116577
