### ISSUE TITLE
Isuess with "No such file or directory: "

### ISSUE THREAD

**Issue by HydrangeAria** [nltk/nltk#1912]
I just started learning nltk and tried to followed the book.
 I don't know why but it keep showing No such file or directory: 
Could anyone explain to me why this happens and how to fix it?
Thank you very much!

```python
from nltk.corpus import BracketParseCorpusReader
corpus_root=r"C:\corpora\penntreebank\parsed\mrg\wsj"
file_pattern=r".*/wsj_.*\.mrg"
ptb=BracketParseCorpusReader(corpus_root,file_pattern)
Traceback (most recent call last):
  File "C:\Users\Angel\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-97-f0f78aef5a32>", line 1, in <module>
    ptb=BracketParseCorpusReader(corpus_root,file_pattern)
  File "C:\Users\Angel\Anaconda3\lib\site-packages\nltk\corpus\reader\bracket_parse.py", line 49, in __init__
    CorpusReader.__init__(self, root, fileids, encoding)
  File "C:\Users\Angel\Anaconda3\lib\site-packages\nltk\corpus\reader\api.py", line 84, in __init__
    root = FileSystemPathPointer(root)
  File "C:\Users\Angel\Anaconda3\lib\site-packages\nltk\compat.py", line 221, in _decorator
    return init_func(*args, **kwargs)
  File "C:\Users\Angel\Anaconda3\lib\site-packages\nltk\data.py", line 303, in __init__
    raise IOError('No such file or directory: %r' % _path)
OSError: No such file or directory: 'C:\\corpora\\penntreebank\\parsed\\mrg\\wsj'
```

```python
from nltk.corpus import PlaintextCorpusReader
corpus_root='/usr/share/dict'
wordlists=PlaintextCorpusReader(corpus_root,'.*')
Traceback (most recent call last):
  File "C:\Users\Angel\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-92-913eb73fb808>", line 1, in <module>
    wordlists=PlaintextCorpusReader(corpus_root,'.*')
  File "C:\Users\Angel\Anaconda3\lib\site-packages\nltk\corpus\reader\plaintext.py", line 62, in __init__
    CorpusReader.__init__(self, root, fileids, encoding)
  File "C:\Users\Angel\Anaconda3\lib\site-packages\nltk\corpus\reader\api.py", line 84, in __init__
    root = FileSystemPathPointer(root)
  File "C:\Users\Angel\Anaconda3\lib\site-packages\nltk\compat.py", line 221, in _decorator
    return init_func(*args, **kwargs)
  File "C:\Users\Angel\Anaconda3\lib\site-packages\nltk\data.py", line 303, in __init__
    raise IOError('No such file or directory: %r' % _path)
OSError: No such file or directory: 'C:\\usr\\share\\dict'
```

**Comment by stevenbird** [comment]
Not an appropriate NLTK issue, sorry.
