### ISSUE TITLE
RecursionError in PorterStemmer._is_consonant

### ISSUE THREAD

**Issue by altescy** [nltk/nltk#1971]
RecursionError occurs in [`PorterStemmer._is_consonant`](https://github.com/nltk/nltk/blob/5a63a62cfc2bdd9d35d863d1c583942e3e6baf6b/nltk/stem/porter.py#L126) when trying to stem a word containing 'yyyyyyy....'.
If the length of 'yyyyyyy....' is larger than the maximum recursion depth, PorterStemmer cannot stem the word.

```python
>> from nltk.stem import PorterStemmer
>>> stemmer = PorterStemmer()
>>> stemmer.stem('y'*10000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/nltk/stem/porter.py", line 667, in stem
    stem = self._step1c(stem)
  File "/home/ubuntu/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/nltk/stem/porter.py", line 421, in _step1c
    else original_condition
  File "/home/ubuntu/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/nltk/stem/porter.py", line 268, in _apply_rule_list
    if condition is None or condition(stem):
  File "/home/ubuntu/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/nltk/stem/porter.py", line 411, in nltk_condition
    return len(stem) > 1 and self._is_consonant(stem, len(stem) - 1)
  File "/home/ubuntu/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/nltk/stem/porter.py", line 144, in _is_consonant
    return (not self._is_consonant(word, i - 1))
  File "/home/ubuntu/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/nltk/stem/porter.py", line 144, in _is_consonant
    return (not self._is_consonant(word, i - 1))
  File "/home/ubuntu/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/nltk/stem/porter.py", line 144, in _is_consonant
    return (not self._is_consonant(word, i - 1))
  [Previous line repeated 990 more times]
  File "/home/ubuntu/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/nltk/stem/porter.py", line 140, in _is_consonant
    if word[i] == 'y':
RecursionError: maximum recursion depth exceeded in comparison
>>>
```

**Comment by alvations** [comment]
@altescy That is some extreme examples you have found! =)

A normal word shouldn't have > 990 characters, unless it's languages without explicit word boundaries (for those, after tokenization, it shouldn't have 990 characters).

```
>>> from nltk.stem import PorterStemmer
>>> porter = PorterStemmer()
>>> word = 'y'* 100
>>> word
'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy'
>>> porter.stem(word)
'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyi'
>>> word = 'y'* 10000
>>> porter.stem(word)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nltk/stem/porter.py", line 667, in stem
    stem = self._step1c(stem)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nltk/stem/porter.py", line 421, in _step1c
    else original_condition
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nltk/stem/porter.py", line 268, in _apply_rule_list
    if condition is None or condition(stem):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nltk/stem/porter.py", line 411, in nltk_condition
    return len(stem) > 1 and self._is_consonant(stem, len(stem) - 1)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nltk/stem/porter.py", line 144, in _is_consonant
    return (not self._is_consonant(word, i - 1))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nltk/stem/porter.py", line 144, in _is_consonant
    return (not self._is_consonant(word, i - 1))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nltk/stem/porter.py", line 144, in _is_consonant
    return (not self._is_consonant(word, i - 1))
  [Previous line repeated 990 more times]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nltk/stem/porter.py", line 140, in _is_consonant
    if word[i] == 'y':
RecursionError: maximum recursion depth exceeded in comparison
```

The stress test if we increase the number of character seems to break at 996:

```
>>> word = 'y'* 995
>>> porter.stem(word) # This works.
>>> word = 'y'* 996
>>> porter.stem(word)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nltk/stem/porter.py", line 144, in _is_consonant
    return (not self._is_consonant(word, i - 1))
  [Previous line repeated 990 more times]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nltk/stem/porter.py", line 140, in _is_consonant
    if word[i] == 'y':
RecursionError: maximum recursion depth exceeded in comparison
>>> 
```

I'm not sure what to fix here though.  Raise a custom more informative error?  Won't fix?

**Comment by altescy** [comment]
I think it is not very important to fix because it is a very rare case.

However, this error is completely unexpected to me.
It is important to know the special token pattern that causes deep recursion.

I'll be careful of the token length and the special pattern when using the stemmer:)

**Comment by alvations** [comment]
Ah, that's because of this rule at https://github.com/nltk/nltk/blob/develop/nltk/stem/porter.py#L140
As long as the token ends with >990 `y` the `RecursionError` will kick in. 

If we do it with other characters, it'll work fine, e.g. 

```python
>>> from nltk.stem import PorterStemmer
>>> porter = PorterStemmer()
>>> word = 'x'* 100000
>>> porter.stem(word) # This works fine.
```

It's because of the recursion when `self._is_consonant` calls itself inside the function.

```python
   def _is_consonant(self, word, i):
        """Returns True if word[i] is a consonant, False otherwise
        
        A consonant is defined in the paper as follows:
        
            A consonant in a word is a letter other than A, E, I, O or
            U, and other than Y preceded by a consonant. (The fact that
            the term `consonant' is defined to some extent in terms of
            itself does not make it ambiguous.) So in TOY the consonants
            are T and Y, and in SYZYGY they are S, Z and G. If a letter
            is not a consonant it is a vowel.
        """
        if word[i] in self.vowels:
            return False
        if word[i] == 'y':
            if i == 0:
                return True
            else:
                return (not self._is_consonant(word, i - 1))
        return True
```

----

P/S: There's a way to set a higher limit globally (`sys.setrecursionlimit(10000)`) but I think users shouldn't do that.

**Comment by batterseapower** [comment]
I also hit this case when stemming a lot of text from the internet. I think the obvious solution is to rewrite the algorithm so that it uses a loop rather than recursion. It should just be a case of replacing the body with:

```
result = False
while i >= 0:
    if word[i] in self.vowels:
        return result
    elif word[i] == 'y':
        result = not result
    else:
        return not result
    
    i -= 1

return result
```

Simple test:
```
def _is_consonant(word, i):
    if word[i] in 'aeiou':
        return False
    if word[i] == 'y':
        if i == 0:
            return True
        else:
            return (not _is_consonant(word, i - 1))
    return True

def _is_consonant_alt(word, i):
    result = False
    while i >= 0:
        if word[i] in 'aeiou':
            return result
        elif word[i] == 'y':
            result = not result
        else:
            return not result

        i -= 1

    return result

assert all([
    _is_consonant('a', 0) == _is_consonant_alt('a', 0),
    _is_consonant('n', 0) == _is_consonant_alt('n', 0),
    _is_consonant('ay', 0) == _is_consonant_alt('ay', 0),
    _is_consonant('ayy', 0) == _is_consonant_alt('ayy', 0),
    _is_consonant('ny', 0) == _is_consonant_alt('ny', 0),
    _is_consonant('nyy', 0) == _is_consonant_alt('nyy', 0),
])
```

**Comment by tomaarsen** [comment]
I'm open to a PR on this, preferably with some tests for the new `is_consonant`.

**Comment by alvations** [comment]
Thanks @tomaarsen @batterseapower @altescy for the inputs! Fixed this via 7808692d451b962711005d954859bb83aabcf8fa while patching some security DoS issues.
