### ISSUE TITLE
ValueError: unknown locale: UTF-8

### ISSUE THREAD

**Issue by Euphorbium** [nltk/nltk#1987]
when importing `nltk==3.2.5` I am getting locale unknown error. Traceback is long, but I don't think it matters. the issue is in:

```
    /Users/euphorbium/miniconda3/lib/python3.5/locale.py in _parse_localename(localename)
    484     elif code == 'C':
    485         return None, None
--> 486     raise ValueError('unknown locale: %s' % localename)
```

Python 3.5.2 :: Continuum Analytics, Inc.  Running on mac osx

**Comment by alvations** [comment]
I'm afraid you'll have to post more of the traceback to understand what's happening.

**Comment by Euphorbium** [comment]
```
>>> import nltk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/euphorbium/miniconda3/lib/python3.5/site-packages/nltk/__init__.py", line 128, in <module>
    from nltk.chunk import *
  File "/Users/euphorbium/miniconda3/lib/python3.5/site-packages/nltk/chunk/__init__.py", line 157, in <module>
    from nltk.chunk.api import ChunkParserI
  File "/Users/euphorbium/miniconda3/lib/python3.5/site-packages/nltk/chunk/api.py", line 15, in <module>
    from nltk.chunk.util import ChunkScore
  File "/Users/euphorbium/miniconda3/lib/python3.5/site-packages/nltk/chunk/util.py", line 13, in <module>
    from nltk.tag.mapping import map_tag
  File "/Users/euphorbium/miniconda3/lib/python3.5/site-packages/nltk/tag/__init__.py", line 70, in <module>
    from nltk.tag.sequential    import (SequentialBackoffTagger, ContextTagger,
  File "/Users/euphorbium/miniconda3/lib/python3.5/site-packages/nltk/tag/sequential.py", line 26, in <module>
    from nltk.classify import NaiveBayesClassifier
  File "/Users/euphorbium/miniconda3/lib/python3.5/site-packages/nltk/classify/__init__.py", line 98, in <module>
    from nltk.classify.textcat import TextCat
  File "/Users/euphorbium/miniconda3/lib/python3.5/site-packages/nltk/classify/textcat.py", line 47, in <module>
    import regex as re
  File "/Users/euphorbium/miniconda3/lib/python3.5/site-packages/regex.py", line 683, in <module>
    _pattern_type = type(_compile("", 0, {}))
  File "/Users/euphorbium/miniconda3/lib/python3.5/site-packages/regex.py", line 436, in _compile
    pattern_locale = _getlocale()[1]
  File "/Users/euphorbium/miniconda3/lib/python3.5/locale.py", line 577, in getlocale
    return _parse_localename(localename)
  File "/Users/euphorbium/miniconda3/lib/python3.5/locale.py", line 486, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8

```

**Comment by alvations** [comment]
@Euphorbium Ah, your locale isn't set by default on your system.

Try this in terminal:

```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

Then try `import nltk` in Python again. Did that resolve your issue?

**Comment by Euphorbium** [comment]
Yes, this solves the problem. But UTF-8 seems like a valid locale, I don't know what set it up like this for me.

**Comment by ankitsharma07** [comment]
Problem resolved
