### ISSUE TITLE
TrigramCollocationFinder nbest method exception

### ISSUE THREAD

**Issue by ghost** [nltk/nltk#2032]
While trying to determine trigrams using the TrigramCollocation finder an exception was received with following details:
from nltk.collocations import TrigramCollocationFinder
from nltk.metrics import TrigramAssocMeasures

wordList = ['borrower', 'borrower', 'borrower', 'borrower', 'borrower', 'borrower', 'page']

tcf = TrigramCollocationFinder.from_words(wordList)
tcf.apply_freq_filter(3)
for word1, word2, word3 in tcf.nbest(TrigramAssocMeasures.likelihood_ratio, 8):
    print ( (word1,word2,word3))

Exception Traceback:
Traceback (most recent call last):
  File "D:/Apps/Python/HelloPython/WorExploreTest.py", line 19, in <module>
    for word1, word2, word3 in tcf.nbest(TrigramAssocMeasures.likelihood_ratio, 8):
  File "D:\Apps\Python\HelloPython\venv\lib\site-packages\nltk\collocations.py", line 125, in nbest
    return [p for p, s in self.score_ngrams(score_fn)[:n]]
  File "D:\Apps\Python\HelloPython\venv\lib\site-packages\nltk\collocations.py", line 121, in score_ngrams
    return sorted(self._score_ngrams(score_fn), key=lambda t: (-t[1], t[0]))
  File "D:\Apps\Python\HelloPython\venv\lib\site-packages\nltk\collocations.py", line 113, in _score_ngrams
    score = self.score_ngram(score_fn, *tup)
  File "D:\Apps\Python\HelloPython\venv\lib\site-packages\nltk\collocations.py", line 255, in score_ngram
    n_all)
  File "D:\Apps\Python\HelloPython\venv\lib\site-packages\nltk\metrics\association.py", line 143, in likelihood_ratio
    for obs, exp in zip(cont, cls._expected_values(cont))))
  File "D:\Apps\Python\HelloPython\venv\lib\site-packages\nltk\metrics\association.py", line 143, in <genexpr>
    for obs, exp in zip(cont, cls._expected_values(cont))))
ValueError: math domain error

Any assistance would be highly appreciated.
Thanks a lot

**Comment by stevenbird** [comment]
Do you need at least 3 distinct words for `TrigramCollocationFinder` to work?

**Comment by jnothman** [comment]
That's not the problem.

IIRC, we've previously had similar issues.

The basic issue is that for simplicity of calculation, we rely on sufficient statistics that are counts of {1,2,3}-grams, and then use approximations such as:
* number of 3-grams == number of 2-grams == number of 1-grams
* number of n-grams of form (any word, target word 2, target word 3) = number of 2-grams of form (target word 2, target word 3)

Obviously, these kinds of approximations do not work for small numbers of words altogether. Without enough data, they result in negative numbers when calculating things like number of (any word but target word 1, any word but target word 2, any word but target word 3).

If you received this error with a larger, more substantial dataset, then maybe we need to consider if our implementation is incorrect, or the assumptions can be improved.

Otherwise, we should probably raise a more informative error, and a pull request doing so (i.e. checking that the output of `_contingency` is all nonnegative) is welcome.

**Comment by ghost** [comment]
Till now I have not seen the error come up for larger dataset.

Thanks

**Comment by stevenbird** [comment]
@AyBeeNLP: would you like to respond to @jnothman's suggestion to submit a PR that raises a more informative error?

**Comment by ghost** [comment]
I agree with @jnothman
