### ISSUE TITLE
doctests might fail if some third-party packages are not installed

### ISSUE THREAD

**Issue by slattarini** [nltk/nltk#216]
Example of such spurious failures:

```
Testing nltk/test/classify.doctest...
  [Line 106] from sklearn.naive_bayes import BernoulliNB
***************************************************************************
File "/devel/stefano/src/nelsearch/nltk/nltk/test/classify.doctest", line 106, in nltk/test/classify.doctest
Failed example:                                                                                                  
    from sklearn.naive_bayes import BernoulliNB                                                                  
Exception raised:                                                                                                
    Traceback (most recent call last):                                                                           
      File "/usr/lib/python2.6/doctest.py", line 1253, in __run
        compileflags, 1) in test.globs
      File "<doctest nltk/test/classify.doctest[15]>", line 1, in <module>
    ImportError: No module named sklearn.naive_bayes
  [Line 107] from sklearn.svm import SVC
```

```
File "/devel/stefano/src/nelsearch/nltk/nltk/test/classify.doctest", line 125, in nltk/test/classify.doctest
Failed example:
    import nltk.classify.svm
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1253, in __run
        compileflags, 1) in test.globs
      File "<doctest nltk/test/classify.doctest[23]>", line 1, in <module>
      File "/devel/stefano/src/nelsearch/nltk/nltk/classify/svm.py", line 28, in <module>
        raise LookupError("\n\n===========================================================================\n  NLTK was unable to import SVMlight!\n\n  For more information, see <https://bitbucket.org/wcauchois/pysvmlight>\n===========================================================================")
    LookupError: 

    ===========================================================================
      NLTK was unable to import SVMlight!

      For more information, see <https://bitbucket.org/wcauchois/pysvmlight>
    ===========================================================================
```

Personally, I've solved part of these problems installing some of the required package.  Still, I think the tests should be skipped instead of failing, when some third-party non-core prerequisite is missing (but I'm not sure how easy this is to attain within the doctest framework).

**Comment by kmike** [comment]
This is resolved in "2and3" branch using nose doctest fixtures (tests with unmet requirements are skipped).
