### ISSUE TITLE
classify.doctest: NameError issue

### ISSUE THREAD

**Issue by slattarini** [nltk/nltk#217]
I'm seeing this failure in 'classify.doctest':

```
Testing nltk/test/classify.doctest...
  [Line 148] test_maxent(nltk.classify.MaxentClassifier.ALGORITHMS)

***************************************************************************
File "/devel/stefano/src/nelsearch/nltk/nltk/test/classify.doctest", line 148, in nltk/test/classify.doctest
Failed example:                                                                                                  
    test_maxent(nltk.classify.MaxentClassifier.ALGORITHMS) 
    # doctest: +ELLIPSIS
Expected:
    [Found megam: ...]
                     test[0]        test[1]        test[2]        test[3]
                    p(x)  p(y)     p(x)  p(y)     p(x)  p(y)     p(x)  p(y) 
    -----------------------------------------------------------------------                                      
         LBFGSB     0.16  0.84     0.46  0.54     0.41  0.59     0.76  0.24
            GIS     0.16  0.84     0.46  0.54     0.41  0.59     0.76  0.24
            IIS     0.16  0.84     0.46  0.54     0.41  0.59     0.76  0.24
    Nelder-Mead     0.16  0.84     0.46  0.54     0.41  0.59     0.76  0.24
             CG     0.16  0.84     0.46  0.54     0.41  0.59     0.76  0.24
           BFGS     0.16  0.84     0.46  0.54     0.41  0.59     0.76  0.24
          MEGAM     0.16  0.84     0.46  0.54     0.41  0.59     0.76  0.24
         Powell     0.16  0.84     0.46  0.54     0.41  0.59     0.76  0.24
Got:
                     test[0]        test[1]        test[2]        test[3]
                    p(x)  p(y)     p(x)  p(y)     p(x)  p(y)     p(x)  p(y)
    ----------------------------------------------------------------------- 
         LBFGSB     0.16  0.84     0.46  0.54     0.41  0.59     0.76  0.24
            GIS     0.16  0.84     0.46  0.54     0.41  0.59     0.76  0.24
            IIS     0.16  0.84     0.46  0.54     0.41  0.59     0.76  0.24
    Nelder-Mead     0.16  0.84     0.46  0.54     0.41  0.59     0.76  0.24
             CG     0.16  0.84     0.46  0.54     0.41  0.59     0.76  0.24
           BFGS     0.16  0.84     0.46  0.54     0.41  0.59     0.76  0.24
          MEGAM Error: NameError("global name 'name' is not defined",)
           TADM Error: NameError("global name 'name' is not defined",)               
         Powell     0.16  0.84     0.46  0.54     0.41  0.59     0.76  0.24
```

And this similar failure in the module doctring for 'nltk.classify.megam':

```
  [Line 20] megam.config_megam() # pass path to megam if not found in...

***************************************************************************
File "/devel/stefano/src/nelsearch/nltk/nltk/classify/megam.py", line 20, in nltk.classify.megam
Failed example:                                                                                                  
    megam.config_megam() # pass path to megam if not found in PATH                                               
Exception raised:                                                                                                
    Traceback (most recent call last):                                                                           
      File "/usr/lib/python2.6/doctest.py", line 1253, in __run
        compileflags, 1) in test.globs
      File "<doctest nltk.classify.megam[1]>", line 1, in <module>
        megam.config_megam() # pass path to megam if not found in PATH
      File "/devel/stefano/src/nelsearch/nltk/nltk/classify/megam.py", line 61, in config_megam
        url='http://www.cs.utah.edu/~hal/megam/')
      File "/devel/stefano/src/nelsearch/nltk/nltk/internals.py", line 526, in find_binary
        url, verbose)
      File "/devel/stefano/src/nelsearch/nltk/nltk/internals.py", line 501, in find_file
        "configuration paramaters" % name)
    NameError: global name 'name' is not defined
  1 example(s) failed!
```

**Comment by slattarini** [comment]
The problem is due to a bug in the 'find_file' function in nltk.internals module.  The diff to fix that is below.  With that apply, I still have a failure, but a reasonable one (even if a SKIP would IMO be much better in such a situation):

```
  ===========================================================================
    NLTK was unable to find the megam file!
    Use software specific configuration paramaters or set the MEGAM environment variable.

      For more information, on megam, see:
        <http://www.cs.utah.edu/~hal/megam/>
    ===========================================================================
  1 example(s) failed!
```

I've setup a pull request for the fix (I hope, it's the first time I try to do so).  In case I've messed up something with that, here's the basic diff:

``` diff
diff --git a/nltk/internals.py b/nltk/internals.py
index 4cc27dc..4ae8ac2 100644
--- a/nltk/internals.py
+++ b/nltk/internals.py
@@ -490,7 +490,7 @@ def find_file(filename, env_vars=(), searchpath=(),
                 stdout, stderr = p.communicate()
                 path = stdout.strip()
                 if path.endswith(alternative) and os.path.exists(path):
-                    if verbose: print '[Found %s: %s]' % (name, path)
+                    if verbose: print '[Found %s: %s]' % (filename, path)
                     return path
             except KeyboardInterrupt, SystemExit:
                 raise
@@ -498,14 +498,14 @@ def find_file(filename, env_vars=(), searchpath=(),
                 pass

     msg = ("NLTK was unable to find the %s file!" "\nUse software specific "
-           "configuration paramaters" % name)
+           "configuration paramaters" % filename)
     if env_vars: msg += ' or set the %s environment variable' % env_vars[0]
     msg += '.'
     if searchpath:
         msg += '\n\n  Searched in:'
         msg += ''.join('\n    - %s' % d for d in searchpath)
     if url: msg += ('\n\n  For more information, on %s, see:\n    <%s>' %
-                    (name, url))
+                    (filename, url))
     div = '='*75
     raise LookupError('\n\n%s\n%s\n%s' % (div, msg, div))
```

**Comment by slattarini** [comment]
My pull request have been merged two weeks ago already, so I'm closing this report.

Thanks,
 Stefano
