### ISSUE TITLE
HTTPError when trying to use CoreNLPParser with multiprocessing

### ISSUE THREAD

**Issue by RuABraun** [nltk/nltk#2178]
I'm using `from nltk.parse.corenlp import CoreNLPParser` for POS. To try and speed it up I thought I'd try and use multiprocessing. So I create the parser `parser = CoreNLPParser(url='http://localhost:9000', tagtype='pos')` and use `multiprocessing.Pool.map` where I pass a list of files and a `partial` of a function which processes each file (with the `parser` in the `partial`).

Unfortunately after running for a bit (maybe 30min using ~20 threads), it always crashes with

```
  File "/usr/local/lib/python3.5/dist-packages/nltk/parse/corenlp.py", line 382, in tag
    return self.tag_sents([sentence])[0]
  File "/usr/local/lib/python3.5/dist-packages/nltk/parse/corenlp.py", line 361, in tag_sents
    return [sentences[0] for sentences in self.raw_tag_sents(sentences)]
  File "/usr/local/lib/python3.5/dist-packages/nltk/parse/corenlp.py", line 361, in <listcomp>
    return [sentences[0] for sentences in self.raw_tag_sents(sentences)]
  File "/usr/local/lib/python3.5/dist-packages/nltk/parse/corenlp.py", line 401, in raw_tag_sents
    tagged_data = self.api_call(sentence, properties=default_properties)
  File "/usr/local/lib/python3.5/dist-packages/nltk/parse/corenlp.py", line 257, in api_call
    response.raise_for_status()
  File "/home/seni/.local/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:9000/?properties=%7B%22outputFormat%22%3A+%22json%22%2C+%22ssplit.isOneSentence%22%3A+%22true%22%2C+%22annotators%22%3A+%22tokenize%2Cssplit%2Cpos%22%7D

```

What could be going wrong?

**Comment by dimazest** [comment]
Check the console output of the CoreNLP server. It might be an exception on
that side, as it returns the 400 error code.

**Comment by RuABraun** [comment]
```
java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:65)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
        at sun.net.httpserver.Request$WriteStream.write(Request.java:391)
        at sun.net.httpserver.FixedLengthOutputStream.write(FixedLengthOutputStream.java:78)
        at java.io.FilterOutputStream.write(FilterOutputStream.java:97)
        at sun.net.httpserver.PlaceholderOutputStream.write(ExchangeImpl.java:439)
        at edu.stanford.nlp.pipeline.StanfordCoreNLPServer$CoreNLPHandler.handle(StanfordCoreNLPServer.java:883)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

I start the server by calling:
```
java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -preload pos -status_port 9000 -port 9000 -timeout 15000
```
maybe I'm missing an important flag?

**Comment by dimazest** [comment]
Maybe, the load is to high to the server. Would decreasing the number of
concurrent requests help? Or increasing the timeout on the server? Or
givinng more memory to the Java virtual machine?

Also, I would have as many threads in your script as you have cpu cores (or
one less, so you still could use your machine without delays).

**Comment by RuABraun** [comment]
Still crashes when just using 5 processes (I have 16 cores) and setting Xmx to 26G, just takes longer to get there.

Java anyways always starts up 32 processes when I run above command, maybe I should reduce that number, is that possible (google doesn't return any results)?

**Comment by alvations** [comment]
What is the longest sentence length in your dataset?

**Comment by RuABraun** [comment]
When running linearly it worked fine to do it in 10 000 word chunks. I tried reducing it further to 5000 but that made no difference.

EDIT: Okay that seems to have been it, I reduced it to 1000 for 10 processes and it's gotten further then ever before. I'll close if it finishes.
