### ISSUE TITLE
NLTK download method fails with error

### ISSUE THREAD

**Issue by server2245** [nltk/nltk#2191]
Please advise.

My code is 

```
import nltk
import ssl
print('The nltk version is {}.'.format(nltk.__version__))
ssl._create_default_https_context = ssl._create_unverified_context
nltk.download('all')

```
The nltk version is 3.3.
Traceback (most recent call last):
  File "r.py", line 7, in <module>
    nltk.download('all')
  File "/usr/lib/python2.7/site-packages/nltk-3.3-py2.7.egg/nltk/downloader.py", line 672, in download
    for msg in self.incr_download(info_or_id, download_dir, force):
  File "/usr/lib/python2.7/site-packages/nltk-3.3-py2.7.egg/nltk/downloader.py", line 540, in incr_download
    try: info = self._info_or_id(info_or_id)
  File "/usr/lib/python2.7/site-packages/nltk-3.3-py2.7.egg/nltk/downloader.py", line 514, in _info_or_id
    return self.info(info_or_id)
  File "/usr/lib/python2.7/site-packages/nltk-3.3-py2.7.egg/nltk/downloader.py", line 885, in info
    self._update_index()
  File "/usr/lib/python2.7/site-packages/nltk-3.3-py2.7.egg/nltk/downloader.py", line 833, in _update_index
    ElementTree.parse(urlopen(self._url)).getroot())
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 9, column 50

**Comment by purificant** [comment]
Unable to reproduce the above issue with nltk 3.3, python 2.7.15 on linux.

May I suggest the following:
1. Verify that you are able to access https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml from your system https://github.com/nltk/nltk/blob/1bdc1bb60867bf81db7f370a12cd21e729391777/nltk/downloader.py#L464
2. Verify that you are able to access the download url in code:
```python
>>> import nltk
>>> d = nltk.downloader.Downloader()
>>> d.index()
<Element u"<?xml version='1.0' encoding='...</nltk_data>">
```
3. Try a more recent python version, such as 3.6 for nltk 3.3 or 3.7 for nltk 3.4

**Comment by server2245** [comment]
I have Python 2.7.5

**Comment by purificant** [comment]
> I have Python 2.7.5

This is likely your issue. This legacy python version was released on [May 15, 2013](https://www.python.org/download/releases/2.7.5/) and has since been superseded by multiple bugfix versions. Consider upgrading from legacy python to 3.6+

**Comment by alvations** [comment]
@server2245 are you still having the issue on the NLTK downloads? If not could we close this issue?
