### ISSUE TITLE
Dozens of test failures from unchanged develop branch

### ISSUE THREAD

**Issue by NQNStudios** [nltk/nltk#2195]
I followed the instructions in `CONTRIBUTING.md` to setup up a development environment, and run the tests with `tox -e py36 > test_output.txt`. (Running python 3.6.6.)

Here are the full contents of test_output.txt:

[test_output.txt](https://github.com/nltk/nltk/files/2634537/test_output.txt)

Observations:
* Several deprecation warnings.
* Some resources, i.e. omw, must not have been installed when I called `python3 -m nltk.downloader tests`

Is this possibly related to the documentation being outdated as mentioned in #1853? Did I miss a step in the setup?

**Comment by purificant** [comment]
@NQNStudios Having had a quick look at your test output log, most of the failures that I can see are due to missing nltk data. Try `python -m nltk.downloader all`, that should download the missing data and make all tests green.

**Comment by NQNStudios** [comment]
That fixed most of the problems.
```
GLOB sdist-make: /home/nat/nltk/setup.py
py36 inst-nodeps: /home/nat/nltk/.tox/.tmp/package/1/nltk-3.4.zip
py36 installed: certifi==2018.11.29,chardet==3.0.4,colorama==0.4.1,coverage==4.5.2,idna==2.7,nltk==3.4,nose==1.3.7,numpy==1.15.4,oauthlib==2.1.0,pyparsing==2.3.0,python-crfsuite==0.9.6,rednose==1.3.0,requests==2.20.1,requests-oauthlib==1.0.0,scikit-learn==0.20.1,scipy==1.1.0,singledispatch==3.4.0.3,six==1.11.0,termstyle==0.1.11,text-unidecode==1.2,twython==3.7.0,urllib3==1.24.1
py36 run-test-pre: PYTHONHASHSEED='2805722241'
py36 runtests: commands[0] | pip install scipy scikit-learn
Requirement already satisfied: scipy in /home/nat/nltk/.tox/py36/lib/python3.6/site-packages (1.1.0)
Requirement already satisfied: scikit-learn in /home/nat/nltk/.tox/py36/lib/python3.6/site-packages (0.20.1)
Requirement already satisfied: numpy>=1.8.2 in /home/nat/nltk/.tox/py36/lib/python3.6/site-packages (from scipy) (1.15.4)
py36 runtests: commands[1] | python runtests.py
-........................................................-...................
.........-.....-.................-........-..................................
..-/home/nat/nltk/nltk/tokenize/stanford_segmenter.py:308: DeprecationWarning: 
The StanfordTokenizer will be deprecated in version 3.2.5.
Please use nltk.parse.corenlp.CoreNLPTokenizer instead.'
  seg = StanfordSegmenter()
-..................................................................-....-.
..F-.....-.-..-......-..-....................................................
.............................................................................
.............................................................................
...............-..-..--....................--------..........................
.........-....................----...........................................
./home/nat/nltk/nltk/test/unit/test_tokenize.py:51: DeprecationWarning: 
The StanfordTokenizer will be deprecated in version 3.2.5.
Please use nltk.parse.corenlp.CoreNLPTokenizer instead.'
  seg = StanfordSegmenter()
-/home/nat/nltk/nltk/test/unit/test_tokenize.py:77: DeprecationWarning: 
The StanfordTokenizer will be deprecated in version 3.2.5.
Please use nltk.parse.corenlp.CoreNLPTokenizer instead.'
  seg = StanfordSegmenter()
-..............................
======================================================================
1) FAIL: Doctest: data.doctest
----------------------------------------------------------------------
   Traceback (most recent call last):
    /usr/lib/python3.6/doctest.py line 2199 in runTest
      raise self.failureException(self.format_failure(new.getvalue()))
   AssertionError: Failed doctest test for data.doctest
     File "/home/nat/nltk/nltk/test/data.doctest", line 0
   
   ----------------------------------------------------------------------
   File "/home/nat/nltk/nltk/test/data.doctest", line 284, in data.doctest
   Failed example:
       for i, url in enumerate(urls):
           nltk.data.retrieve(url, 'toy-%d.cfg' % i) # doctest: +ELLIPSIS
   Exception raised:
       Traceback (most recent call last):
         File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
           encode_chunked=req.has_header('Transfer-encoding'))
         File "/usr/lib/python3.6/http/client.py", line 1239, in request
           self._send_request(method, url, body, headers, encode_chunked)
         File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
           self.endheaders(body, encode_chunked=encode_chunked)
         File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
           self._send_output(message_body, encode_chunked=encode_chunked)
         File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
           self.send(msg)
         File "/usr/lib/python3.6/http/client.py", line 964, in send
           self.connect()
         File "/usr/lib/python3.6/http/client.py", line 1392, in connect
           super().connect()
         File "/usr/lib/python3.6/http/client.py", line 936, in connect
           (self.host,self.port), self.timeout, self.source_address)
         File "/usr/lib/python3.6/socket.py", line 704, in create_connection
           for res in getaddrinfo(host, port, 0, SOCK_STREAM):
         File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
           for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
       socket.gaierror: [Errno -2] Name or service not known
   
       During handling of the above exception, another exception occurred:
   
       Traceback (most recent call last):
         File "/usr/lib/python3.6/doctest.py", line 1330, in __run
           compileflags, 1), test.globs)
         File "<doctest data.doctest[52]>", line 2, in <module>
           nltk.data.retrieve(url, 'toy-%d.cfg' % i) # doctest: +ELLIPSIS
         File "/home/nat/nltk/nltk/data.py", line 727, in retrieve
           infile = _open(resource_url)
         File "/home/nat/nltk/nltk/data.py", line 998, in _open
           return urlopen(resource_url)
         File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
           return opener.open(url, data, timeout)
         File "/usr/lib/python3.6/urllib/request.py", line 526, in open
           response = self._open(req, data)
         File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
           '_open', req)
         File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
           result = func(*args)
         File "/usr/lib/python3.6/urllib/request.py", line 1361, in https_open
           context=self._context, check_hostname=self._check_hostname)
         File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
           raise URLError(err)
       urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

-----------------------------------------------------------------------------
649 tests run in 265.737 seconds. 
1 FAILED, 35 skipped (613 tests passed)
ERROR: InvocationError for command '/home/nat/nltk/.tox/py36/bin/python runtests.py' (exited with code 1)
_____________________________________________________________________________________________________ summary _____________________________________________________________________________________________________
ERROR:   py36: commands failed
```

**Comment by NQNStudios** [comment]
That last failure seems to be on me for having a spotty internet connection. I tried `tox -e py36 data.doctest` and got a success, then disconnected from the network and got a failure. Thanks for the help!
