### ISSUE TITLE
problems configuring NLTK 3.4 to use Stanford segmenter

### ISSUE THREAD

**Issue by zhang402115** [nltk/nltk#2258]
win10 64bit+python3.6 64bit
I find this instruction website and followed: http://www.nltk.org/api/nltk.tokenize.html?highlight=segmenter#module-nltk.tokenize.stanford_segmenter//
With enviroment varable set,still the program is a failure.

# -*- coding:utf-8 -*-
import nltk, re, pprint,os,codecs
java_path = r"C:\Program Files\Java\jre1.8.0_202\bin\java.exe"
os.environ['JAVAHOME'] = java_path

from nltk.tokenize.stanford_segmenter import StanfordSegmenter
seg = StanfordSegmenter()
seg.default_config('zh')
sent = u'这是斯坦福中文分词器测试'
print(seg.segment(sent))

Result:
Traceback (most recent call last):
Invoked on Tue Mar 26 10:24:04 CST 2019 with arguments: -loadClassifier D:\BaiduNetdiskDownload\stanford-jar\data\pku.gz -keepAllWhitespaces false -textFile C:\Users\ADMINI~1\AppData\Local\Temp\tmpxzs78r0w -serDictionary D:\BaiduNetdiskDownload\stanford-jar\data\dict-chris6.ser.gz -sighanCorporaDict D:\BaiduNetdiskDownload\stanford-segmenter-2018-10-16\stanford-segmenter-2018-10-16\data\./data/ -sighanPostProcessing true -inputEncoding UTF-8
  File "D:/System/My Documents/HikStorageData/Download/test2 lenovo.py", line 10, in <module>
serDictionary=D:\BaiduNetdiskDownload\stanford-jar\data\dict-chris6.ser.gz
    print(seg.segment(sent))
loadClassifier=D:\BaiduNetdiskDownload\stanford-jar\data\pku.gz
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\nltk\tokenize\stanford_segmenter.py", line 236, in segment
sighanCorporaDict=D:\BaiduNetdiskDownload\stanford-segmenter-2018-10-16\stanford-segmenter-2018-10-16\data\./data/
    return self.segment_sents([tokens])
inputEncoding=UTF-8
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\nltk\tokenize\stanford_segmenter.py", line 274, in segment_sents
keepAllWhitespaces=false
    stdout = self._execute(cmd)
textFile=C:\Users\ADMINI~1\AppData\Local\Temp\tmpxzs78r0w
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\nltk\tokenize\stanford_segmenter.py", line 294, in _execute
sighanPostProcessing=true
    cmd, classpath=self._stanford_jar, stdout=PIPE, stderr=PIPE
Loading classifier from D:\BaiduNetdiskDownload\stanford-jar\data\pku.gz ... done [10.2 sec].
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\nltk\internals.py", line 145, in java
    raise OSError('Java command failed : ' + str(cmd))
OSError: Java command failed : ['C:\\Program Files\\Java\\jre1.8.0_202\\bin\\java.exe', '-mx2g', '-cp', 'D:\\BaiduNetdiskDownload\\stanford-segmenter-2018-10-16\\stanford-segmenter-2018-10-16\\stanford-segmenter.jar', 'edu.stanford.nlp.ie.crf.CRFClassifier', '-loadClassifier', 'D:\\BaiduNetdiskDownload\\stanford-jar\\data\\pku.gz', '-keepAllWhitespaces', 'false', '-textFile', 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\tmpxzs78r0w', '-serDictionary', 'D:\\BaiduNetdiskDownload\\stanford-jar\\data\\dict-chris6.ser.gz', '-sighanCorporaDict', 'D:\\BaiduNetdiskDownload\\stanford-segmenter-2018-10-16\\stanford-segmenter-2018-10-16\\data\\./data/', '-sighanPostProcessing', 'true', '-inputEncoding', 'UTF-8']
Loading Chinese dictionaries from 1 file:
  D:\BaiduNetdiskDownload\stanford-jar\data\dict-chris6.ser.gz
Done. Unique words in ChineseDictionary is: 423200.
Loading unnormalized dictionary from D:\BaiduNetdiskDownload\stanford-segmenter-2018-10-16\stanford-segmenter-2018-10-16\data\./data//dict/pku.non
Exception in thread "main" edu.stanford.nlp.io.RuntimeIOException: java.io.IOException: Unable to open "D:\BaiduNetdiskDownload\stanford-segmenter-2018-10-16\stanford-segmenter-2018-10-16\data\./data//dict/pku.non" as class path, filename or URL
	at edu.stanford.nlp.wordseg.CorpusDictionary.readDict(CorpusDictionary.java:80)
	at edu.stanford.nlp.wordseg.CorpusDictionary.<init>(CorpusDictionary.java:40)
	at edu.stanford.nlp.wordseg.CorpusDictionary.<init>(CorpusDictionary.java:35)
	at edu.stanford.nlp.wordseg.NonDict2.<init>(NonDict2.java:32)
	at edu.stanford.nlp.wordseg.Gale2007ChineseSegmenterFeatureFactory.featuresCpC(Gale2007ChineseSegmenterFeatureFactory.java:482)
	at edu.stanford.nlp.wordseg.Gale2007ChineseSegmenterFeatureFactory.getCliqueFeatures(Gale2007ChineseSegmenterFeatureFactory.java:88)
	at edu.stanford.nlp.ie.crf.CRFClassifier.makeDatum(CRFClassifier.java:992)
	at edu.stanford.nlp.ie.crf.CRFClassifier.documentToDataAndLabels(CRFClassifier.java:452)
	at edu.stanford.nlp.ie.crf.CRFClassifier.getSequenceModel(CRFClassifier.java:1185)
	at edu.stanford.nlp.ie.crf.CRFClassifier.classifyMaxEnt(CRFClassifier.java:1218)
	at edu.stanford.nlp.ie.crf.CRFClassifier.classify(CRFClassifier.java:1128)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier$2.process(AbstractSequenceClassifier.java:1172)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier$2.process(AbstractSequenceClassifier.java:1169)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.classifyAndWriteAnswers(AbstractSequenceClassifier.java:1200)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.classifyAndWriteAnswers(AbstractSequenceClassifier.java:1133)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.classifyAndWriteAnswers(AbstractSequenceClassifier.java:1087)
	at edu.stanford.nlp.ie.crf.CRFClassifier.main(CRFClassifier.java:3067)
Caused by: java.io.IOException: Unable to open "D:\BaiduNetdiskDownload\stanford-segmenter-2018-10-16\stanford-segmenter-2018-10-16\data\./data//dict/pku.non" as class path, filename or URL
	at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:480)
	at edu.stanford.nlp.wordseg.CorpusDictionary.readDict(CorpusDictionary.java:54)
	... 16 more

Process finished with exit code 1

Any help would be appreciated facing this obstacle, thank you!

**Comment by alvations** [comment]
@zhang402115 please use this to access the Stanford CoreNLP https://github.com/nltk/nltk/wiki/Stanford-CoreNLP-API-in-NLTK

**Comment by zhang402115** [comment]
@alvations Thank you for the reminding. I know about that webpage, though a little superstitious that an independent segmenter just for chinese could be more acccurate, thus exerted lots of efforts on it :)

**Comment by alvations** [comment]
The wrapper should technically call the same segmenter for Chinese. 

P/S: The old Stanford interfaces should be somehow deprecated...

**Comment by zhang402115** [comment]
@alvations Thank you!

**Comment by zhang402115** [comment]
@alvations i just confirmed, the comprehensive corenlp functions as well as the independent segmenter
