### ISSUE TITLE
ImportError: Module use of python35.dll conflicts with this version of Python.

### ISSUE THREAD

**Issue by MrDredD** [nltk/nltk#2279]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2018.2.5\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Anaconda\envs\NLP\lib\site-packages\nltk\__init__.py", line 137, in <module>
    from nltk.stem import *
  File "C:\Program Files\JetBrains\PyCharm 2018.2.5\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Anaconda\envs\NLP\lib\site-packages\nltk\stem\__init__.py", line 29, in <module>
    from nltk.stem.snowball import SnowballStemmer
  File "C:\Program Files\JetBrains\PyCharm 2018.2.5\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Anaconda\envs\NLP\lib\site-packages\nltk\stem\snowball.py", line 32, in <module>
    from nltk.corpus import stopwords
  File "C:\Program Files\JetBrains\PyCharm 2018.2.5\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Anaconda\envs\NLP\lib\site-packages\nltk\corpus\__init__.py", line 66, in <module>
    from nltk.corpus.reader import *
  File "C:\Program Files\JetBrains\PyCharm 2018.2.5\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Anaconda\envs\NLP\lib\site-packages\nltk\corpus\reader\__init__.py", line 105, in <module>
    from nltk.corpus.reader.panlex_lite import *
  File "C:\Program Files\JetBrains\PyCharm 2018.2.5\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Anaconda\envs\NLP\lib\site-packages\nltk\corpus\reader\panlex_lite.py", line 15, in <module>
    import sqlite3
  File "C:\Program Files\JetBrains\PyCharm 2018.2.5\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Anaconda\envs\NLP\lib\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "C:\Program Files\JetBrains\PyCharm 2018.2.5\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Anaconda\envs\NLP\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
  File "C:\Program Files\JetBrains\PyCharm 2018.2.5\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: Module use of python35.dll conflicts with this version of Python.

**Comment by MrDredD** [comment]
Solved: manually installed the current version

**Comment by JEFritsch** [comment]
Hi,
I get the same error message. How do I install the current version manually. 
Sorry, only beginning to learn.
Thanks!
