### ISSUE TITLE
nltk.pos_tag_sents throwing exception 

### ISSUE THREAD

**Issue by devna13** [nltk/nltk#2305]
I'm new to Phyton and I have a script im trying to run and its failing on this line: 

` sent_tag = nltk.pos_tag_sents(sent)`

even when I ass the lang param still getting same error :
          
`sent_tag = nltk.pos_tag_sents(sent, lang='eng')`

```
(base) C:\Windows\system32>conda -V
conda 4.6.14

(base) C:\Windows\system32>py --version
Python 3.7.3
```

any thoughts?

```
Traceback (most recent call last):
  File "C:\Users\na\AppData\Local\Continuum\anaconda3\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\na\code\philter_ucsf-master\philter.py", line 431, in filter_task
    sent_tag = nltk.pos_tag_sents(sent)
  File "C:\Users\na\AppData\Local\Continuum\anaconda3\lib\site-packages\nltk\tag\__init__.py", line 180, in pos_tag_sents
    return [_pos_tag(sent, tagset, tagger) for sent in sentences]
  File "C:\Users\na\AppData\Local\Continuum\anaconda3\lib\site-packages\nltk\tag\__init__.py", line 180, in <listcomp>
    return [_pos_tag(sent, tagset, tagger) for sent in sentences]
  File "C:\Users\na\AppData\Local\Continuum\anaconda3\lib\site-packages\nltk\tag\__init__.py", line 115, in _pos_tag
    "Currently, NLTK pos_tag only supports English and Russian "
NotImplementedError: Currently, NLTK pos_tag only supports English and Russian (i.e. lang='eng' or lang='rus')


```

Thanks

**Comment by devna13** [comment]
seems i was missing some stuff 
updating nltk resolved the issue 

conda install -c anaconda nltk
