### ISSUE TITLE
Importing nltk (v3.4.2) fails because of unmanaged dependency on Numpy

### ISSUE THREAD

**Issue by a3lem** [nltk/nltk#2312]
Hi

So, this cropped up today thanks to my lazy self forgetting to pin the nltk version in a couple of Dockerfiles (don't try this at home, kids). I can confirm that, as of version 3.4.2 (release 3.4.1 works), importing nltk is no longer possible without numpy being installed (or without installing the optional `[machine_learning]` extras, where the numpy dependency is specified). The culprit is an implicit dependency chain somewhere in the top-level \_\_init\_\_.py. As the stacktrace below suggests, the statement `from nltk.chunk import *` would probably be the place to start looking.

Here are the steps to reproduce the issue: 

1. 
```
$ pip install nltk
Collecting nltk                       
packages (from nltk) (1.12.0)                                                       
Installing collected packages: nltk                                      
Successfully installed nltk-3.4.2  
```
2. 

```
# tested with python3.6 and python3.7
$ python3 -c "import nltk"
```
This gives the following stacktrace:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lemontheme/.virtualenvs/nltk/lib/python3.7/site-packages/nltk/__init__.py", line 143, in <module>                                                                 
    from nltk.chunk import *
  File "/home/lemontheme/.virtualenvs/nltk/lib/python3.7/site-packages/nltk/chunk/__init__.py", line 157, in <module>                                                           
    from nltk.chunk.api import ChunkParserI
  File "/home/lemontheme/.virtualenvs/nltk/lib/python3.7/site-packages/nltk/chunk/api.py", line 13, in <module>                                                                 
    from nltk.parse import ParserI
  File "/home/lemontheme/.virtualenvs/nltk/lib/python3.7/site-packages/nltk/parse/__init__.py", line 102, in <module>                                                           
    from nltk.parse.corenlp import CoreNLPParser, CoreNLPDependencyParser
  File "/home/lemontheme/.virtualenvs/nltk/lib/python3.7/site-packages/nltk/parse/corenlp.py", line 19, in <module>                                                             
    from nltk.tag.api import TaggerI
  File "/home/lemontheme/.virtualenvs/nltk/lib/python3.7/site-packages/nltk/tag/__init__.py", line 92, in <module>                                                              
    from nltk.tag.perceptron import PerceptronTagger
  File "/home/lemontheme/.virtualenvs/nltk/lib/python3.7/site-packages/nltk/tag/perceptron.py", line 24, in <module>                                                            
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

Current solution -- in case anyone else is having the same problem -- is to pin nltk to 3.4.1, e.g. `pip install nltk==3.4.1`.

**Comment by stsewd** [comment]
We at Read the Docs are having the same issue, using this package https://github.com/agjohnson/django-textclassifier/blob/v1.0/setup.py, which doesn't have the dependencies pinned.
