### ISSUE TITLE
nltk.download() logs out on OS X

### ISSUE THREAD

**Issue by mi-kon** [nltk/nltk#2357]
Hello,

I have a macbook running OS X 10.14.6, Python 3.7.3, conda 4.7.5 .

When I try run interactive installer from NLTK python package, following the steps from: http://www.nltk.org/data.html in my terminal, after

`>> nltk.download()`

Instead of opening NLTK Downloader in a new window, I get logged out (ok, i assume something related to GUI crashes at this point). `nltk.download_shell()`works instead, as it will not try to open GUI installer, but I still want to figure out why GUI won't work for me. Any suggestions would be appreciated!

**Comment by alvations** [comment]
Personally, I would advise against using the GUI for NLTK download. 

But to explain the problem, it's most probably because of `tkinter`. On Mac OS, maybe this works, assuming that you have homebrew installed https://brew.sh/

```
xcode-select --install

brew uninstall python3
brew install python3 --use-brewed-tk

brew uninstall python
brew install python --use-brewed-tk
```

From https://stackoverflow.com/questions/36760839/why-my-python-installed-via-home-brew-not-include-tkinter/48737927 

If the above works and the GUI pops up properly afterwards, please do tell us so that we can document it and future users can do the same.

**Comment by shanest** [comment]
I'm having this issue as well.  And it appears to be with anything that uses the GUI, e.g. `ntlk.Tree.draw()`, which makes sense.  I'm using Python 3.7 installed via Anaconda; `tkinter` seems to be installed fine (can be imported, etc) in my environment.  Any ideas?

**Comment by costezki** [comment]
Here is an additional stack trace in case it may help.
OS: Ubuntu 19.04

```
Python 3.7.3 (default, Oct  7 2019, 12:56:13) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.10.2 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 7.10.2
Python 3.7.3 (default, Oct  7 2019, 12:56:13) 
[GCC 8.3.0] on linux
import nltk
nltk.downloader.download_gui()
Traceback (most recent call last):
  File "/home/lps/work/workspace-charm/mln-sandbox1/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-b403f4b651ae>", line 1, in <module>
    nltk.downloader.download_gui()
  File "/home/lps/work/workspace-charm/mln-sandbox1/venv/lib/python3.7/site-packages/nltk/downloader.py", line 2488, in download_gui
    DownloaderGUI(_downloader).mainloop()
  File "/home/lps/work/workspace-charm/mln-sandbox1/venv/lib/python3.7/site-packages/nltk/downloader.py", line 1407, in __init__
    top = self.top = Tk()
NameError: name 'Tk' is not defined

```

**Comment by gdmanandamohon** [comment]
Well, I faced same problem, and solved using a parameter of the download function. Hope it will help. `nltk.download('words')`

**Comment by jimparrillo** [comment]
I had this problem and found the solution at [http://www.nltk.org/data.html](url):

Run the command `python -m nltk.downloader all` if you want to download all the data...

Or run the command `python -m nltk.downloader popular` if you want to download the most popular data sets.

To ensure installation run command `sudo python -m nltk.downloader -d /usr/local/share/nltk_data all`.

**Comment by elliedai0323** [comment]
I used nltk.download('punkt') and it worked
