### ISSUE TITLE
Issue with synset_from_sense_key function to access adjective satellites

### ISSUE THREAD

**Issue by Izorar** [nltk/nltk#2442]
I tried to use the synset_from_sense_key function and here is the error:

File "/home/izorar/anaconda3/lib/python3.7/site-packages/nltk/corpus/reader/wordnet.py", line 1356, in synset raise WordNetError(message % lemma)

WordNetError: adjective satellite requested but only plain adjective found for lemma 'first'

Any idea on how to fix the error?

**Comment by jnothman** [comment]
Please provide a fully reproducible code snippet, with imports, etc.

**Comment by alvations** [comment]
@Izorar Which synset/lemma are you look at? Please do post a code snippet as advised by @jnothman so that we can help you better.

**Comment by Izorar** [comment]
@jnothman @alvations. See the snippet and the error message:
```
 import nltk
 from nltk import stem
 from nltk.corpus import wordnet as wn
 sense=wn.synset_from_sense_key("first%5:00:00:ordinal:00")
 sense2=synset_from_sense_key("more%5:00:00:added:00")
 print(sense, sense2)
```
Here is the error message
```
Traceback (most recent call last):
  File "/home/izorar/Documents/adjsat.py", line 4, in <module>
    sense=wn.synset_from_sense_key("first%5:00:00:ordinal:00")
  File "/home/izorar/.local/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1562, in synset_from_sense_key
    return self.synset(synset_id)
  File "/home/izorar/.local/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1356, in synset
    raise WordNetError(message % lemma)
nltk.corpus.reader.wordnet.WordNetError: adjective satellite requested but only plain adjective found for lemma 'first'
```

Thanks
