### ISSUE TITLE
import nltk eror, No module named '_sqlite3'

### ISSUE THREAD

**Issue by 007fred50** [nltk/nltk#2521]
I'm in ubuntu 16.04

here what i do:
```
sudo apt-get install sqlite-devel
sudo apt-get install libsqlite3-dev
sudo pip3 install pysqlite
```

I try to import nltk library.

line (1): import nltk
```
Traceback (most recent call last):
  File "chat.py", line 1, in <module>
    import nltk
  File "/usr/local/lib/python3.7/site-packages/nltk/__init__.py", line 150, in <module>
    from nltk.translate import *
  File "/usr/local/lib/python3.7/site-packages/nltk/translate/__init__.py", line 23, in <module>
    from nltk.translate.meteor_score import meteor_score as meteor
  File "/usr/local/lib/python3.7/site-packages/nltk/translate/meteor_score.py", line 10, in <module>
    from nltk.stem.porter import PorterStemmer
  File "/usr/local/lib/python3.7/site-packages/nltk/stem/__init__.py", line 29, in <module>
    from nltk.stem.snowball import SnowballStemmer
  File "/usr/local/lib/python3.7/site-packages/nltk/stem/snowball.py", line 32, in <module>
    from nltk.corpus import stopwords
  File "/usr/local/lib/python3.7/site-packages/nltk/corpus/__init__.py", line 66, in <module>
    from nltk.corpus.reader import *
  File "/usr/local/lib/python3.7/site-packages/nltk/corpus/reader/__init__.py", line 105, in <module>
    from nltk.corpus.reader.panlex_lite import *
  File "/usr/local/lib/python3.7/site-packages/nltk/corpus/reader/panlex_lite.py", line 15, in <module>
    import sqlite3
  File "/usr/local/lib/python3.7/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.7/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

canyou help me with this?

Thanks for your time !

**Comment by 007fred50** [comment]
I downgrade my python too 3.6 and it works!

**Comment by margegaj24** [comment]
I upgraded to python3.8 and it works!

**Comment by ivan-marroquin** [comment]
Hi @tomaarsen 

I have ubuntu 18.04.5 with Python 3.6.5 ans nltk 3.6.5. I experience the same issue. What solution do you propose?

Thanks for all,

Ivan

**Comment by tomaarsen** [comment]
@ivan-marroquin 
This issue has been encountered by many, and hence has a few potential solutions online. For example: https://stackoverflow.com/questions/43993890/modulenotfounderror-no-module-named-sqlite3

If this doesn't help, other solutions can be found by searching for e.g. `Ubuntu 18 ModuleNotFoundError: No module named '_sqlite3'` with your browser of choice.
