### ISSUE TITLE
AttributeError: 'StringTokenizer' object has no attribute '_string'

### ISSUE THREAD

**Issue by Cristinutaa** [nltk/nltk#2526]
I was trying to tokenize a doc using nltk.tokenize.api.StringTokenizer. (I've managed to tokenize it with word_tokenizer, so no need for solutions)

Is this normal behaviour?
```python
text1
Out[5]: "event information speakers alison shafer customer success manager, millward brown digital sarah friedman customer success manager, millward brown digital for retail brands, the holiday season is already kicking into gear. from various traffic patterns, to keyword searches and conversion rates, having a holistic understanding of your strengths, weaknesses, and how your competitors fare is crucial to optimizing and improving your digital strategy. with compete pro, you can do just that this holiday season. during this webinar we’ll use retail as an example to walk through the search market share feature and its benefits in monitoring keywords that spark consumer interest to you and your competitors. we'll also help you understand industry conversion rates, and how compete pro can help you monitor referral and incoming/outgoing traffic sources driving engagement on your site. in doing so, you can accurately benchmark and analyze your effectiveness this holiday season."
tokenizer = nltk.tokenize.api.StringTokenizer()
tokenizer.tokenize(text1)

Traceback (most recent call last):
  File "C:\Users\Cristina\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-838af32942bb>", line 1, in <module>
    tokenizer.tokenize(text1)
  File "C:\Users\Cristina\Anaconda3\lib\site-packages\nltk\tokenize\api.py", line 74, in tokenize
    return s.split(self._string)
AttributeError: 'StringTokenizer' object has no attribute '_string'
```

**Comment by fievelk** [comment]
As far as I can understand from the docstring, the `StringTokenizer` class is not supposed to be used directly, but only as a parent class. 

In fact, you can find other classes that inherit from `StringTokenizer` and define the `_string` variable which is causing your exception:
https://github.com/nltk/nltk/blob/d13078e0441cd46f46b41a9db70dbde0ffacd4fe/nltk/tokenize/simple.py#L42
https://github.com/nltk/nltk/blob/d13078e0441cd46f46b41a9db70dbde0ffacd4fe/nltk/tokenize/simple.py#L56
https://github.com/nltk/nltk/blob/d13078e0441cd46f46b41a9db70dbde0ffacd4fe/nltk/tokenize/simple.py#L68

I think it would be better to make this explicit. For example, we could make the `StringTokenizer` class abstract and "force" child classes to define the `_string` property.
