### ISSUE TITLE
nltk.grammar.demo() produces AttributeError

### ISSUE THREAD

**Issue by oubiwann** [nltk/nltk#262]
NLTK version: 2.0.1
NLTK corpora installed: all
Python version: 2.7.3
OS: Mac 10.6.8

When running the demo, an AttributeError is raised. Before the error is raised, some output is produced:
- nonterminals
- a grammar with 14 productions
- a PCFG production and grammar

When the demo for inducing a PCFG grammar is attempted, the following traceback is produced:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nltk/grammar.py", line 1470, in demo
    pcfg_demo()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nltk/grammar.py", line 1401, in pcfg_demo
    for item in treebank.items[:2]:
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nltk/corpus/util.py", line 71, in **getattr**
    return getattr(self, attr)
AttributeError: 'BracketParseCorpusReader' object has no attribute 'items'

**Comment by oubiwann** [comment]
Looks like this didn't get closed when the pull request was merged.

Closing now -- thanks Peter Ljunglöf!
