### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by alyhalo** [nltk/nltk#2758]
Hello!

I have an error `TypeError: expected string or bytes-like object` after running this code in google colaboratory:

```
from nltk import tokenize
text_data =  tokenize.sent_tokenize(data_list)
```

`data_list` is the list by type, contains textual strings and was getting like this:

```
df = pd.read_csv(io.BytesIO('data.csv', header=None)
data_list = df['text'].tolist()
```

What is the problem and how can I solve it?

**Comment by tomaarsen** [comment]
`nltk`'s `sent_tokenize` takes as input a *str*, and then outputs a *list of strings*. **It splits the (single!) input string into a list of sentences.**

For example:
```python
>>> from nltk import tokenize
>>> text = "Hello. These are sentences. Yup."
>>> tokenize.sent_tokenize(text)
['Hello.', 'These are sentences.', 'Yup.']
```

The issue you are experiencing can be reproduced by passing a list instead of a string:
```python
>>> from nltk import tokenize
>>> data = ["Hello. These are sentences. Yup.", "This is yet another one. This too"]
>>> tokenize.sent_tokenize(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\GitHub\nltk\nltk\tokenize\__init__.py", line 108, in sent_tokenize    
    return tokenizer.tokenize(text)
  File "C:\GitHub\nltk\nltk\tokenize\punkt.py", line 1274, in tokenize
    return list(self.sentences_from_text(text, realign_boundaries))
  File "C:\GitHub\nltk\nltk\tokenize\punkt.py", line 1328, in sentences_from_text
    return [text[s:e] for s, e in self.span_tokenize(text, realign_boundaries)]  
  File "C:\GitHub\nltk\nltk\tokenize\punkt.py", line 1328, in <listcomp>
    return [text[s:e] for s, e in self.span_tokenize(text, realign_boundaries)]  
  File "C:\GitHub\nltk\nltk\tokenize\punkt.py", line 1318, in span_tokenize      
    for sl in slices:
  File "C:\GitHub\nltk\nltk\tokenize\punkt.py", line 1359, in _realign_boundaries
    for sl1, sl2 in _pair_iter(slices):
  File "C:\GitHub\nltk\nltk\tokenize\punkt.py", line 316, in _pair_iter
    prev = next(it)
  File "C:\GitHub\nltk\nltk\tokenize\punkt.py", line 1332, in _slices_from_text
    for match in self._lang_vars.period_context_re().finditer(text):
TypeError: expected string or bytes-like object
```

Given that you already have a list of strings, perhaps `sent_tokenize` does not have the functionality you desire. It all depends on what you're trying to build.

- Tom Aarsen
