### ISSUE TITLE
is_writable function produces the wrong boolean output when run on AWS Lambda with EFS storage attached

### ISSUE THREAD

**Issue by dnk8n** [nltk/nltk#2919]
[The function in question](https://github.com/nltk/nltk/blob/59aa3fb88c04d6151f2409b31dcfe0f332b0c9ca/nltk/internals.py#L1102)

I need to debug further, but I am 100% sure the drive is writable, as I was able to create folders (e.g. `Path(os.environ['NLTK_DATA']).mkdir(parents=True, exist_ok=True)`)

This being returned as False causes environment variable NLTK_DATA not to function. I think you should trust users to know that they are using NLTK_DATA for good reason and in the case where `path == os.environ['NLTK_DATA']`, skip the iswritable check. If in fact it is unwritable, the user would be able to be told that the environment variable (potentially with a typo) is not writable.

I will now attempt to log the same checks of is_writable to provide more info on what is failing.

**Comment by dnk8n** [comment]
Can confirm that the lambda function would have returned an error (e.g. NLTK_DATA=/cache/nltk) if the supplied nltk_data directory was read-only.

It would have been of the following format:

```
Traceback (most recent call last):
  File "/var/lang/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/cache/nltk'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/lang/lib/python3.9/pathlib.py", line 1327, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/var/lang/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
OSError: [Errno 30] Read-only file system: '/cache'
```

**Comment by dnk8n** [comment]
The results of the following:

```python
import os
import stat
statdata = os.stat(os.environ['NLTK_DATA'])
perm = stat.S_IMODE(statdata.st_mode)
# is it world-writable?
if perm & 0o002:
    print("It is world-writable")
else:
    print("It is NOT world-writable")
# do we own it?
if statdata.st_uid == os.getuid() and (perm & 0o200):
    print("We do own it")
else:
    print("We do NOT own it")
# are we in a group that can write to it?
if (statdata.st_gid in [os.getgid()] + os.getgroups()) and (perm & 0o020):
    print("We are in a group that can write to it")
else:
    print("We are NOT in a group that can write to it")
```

are:

```
  | 2021-12-20T01:12:02.903+07:00 | It is NOT world-writable
  | 2021-12-20T01:12:02.903+07:00 | We do NOT own it
  | 2021-12-20T01:12:02.903+07:00 | We are NOT in a group that can write to it
```

**Comment by dnk8n** [comment]
I have a feeling this code would fail on any NFS type filesystem too

**Comment by dnk8n** [comment]
Anyone here with a similar issue. The workaround I am going to try is to change `NLTK_DATA=/tmp/nltk_data`. I only really need Amazon EFS for the library that is calling ntlk (allenNLP).

**Comment by dnk8n** [comment]
That would have worked if NLTK data required was < 512MB, however it is not.

I get the following:
`[ERROR] OSError: [Errno 28] No space left on device Traceback (most recent call last)`

**Comment by dnk8n** [comment]
I am going to have to investigate monkeypatching to get this to work.

For what reason can you not use try / except in this case? It is a much more portable solution to try write a file. If it fails handle exception, if it passes then delete temporary file.

I am happy to submit a PR but only if the maintainer agrees that this is the way to go.

**Comment by tomaarsen** [comment]
> That would have worked if NLTK data required was < 512MB, however it is not.
> 
> I get the following: `[ERROR] OSError: [Errno 28] No space left on device Traceback (most recent call last)`

`nltk_data` is about 3.37GB in size if all packages are installed. However, it's possible to only install the required sections. If, by chance, you have installed all of `nltk_data` (i.e. with `import nltk; nltk.download("all")` or `python -m nltk.downloader all`), then reducing this to merely the sections that are required, then you might be able to make some progress here.
That said, I'm assuming allenNLP already downloads the minimal `nltk_data` for its purposes.

Perhaps https://docs.python.org/3/library/os.html#os.access would be an appropriate replacement of the current system, but it is possible that the current function is specifically written because of the second note on that documentation:
> I/O operations may fail even when access() indicates that they would succeed, particularly for operations on network filesystems which may have permissions semantics beyond the usual POSIX permission-bit model. 

Alternatively, writing and deleting an empty file could also work.

**Comment by dnk8n** [comment]
I don't have control here. NLTK is called through another library, AllenNLP.

Anyway, I found a way. I call the module which results in the downloads during build time of the docker image and use NLTK_DATA variable to reference the now populated read-only directory at lambda invocation time. This way, the downloader does not need to be called and we work around the problem.

FYI, the size of what ends up being downloaded for NLTK in this case is 155M!

I think in looking up that answer, I just figured out that it was AllenNLP writing to /tmp, not NLTK. I solved the problem of AllenNLP's use of /tmp by setting `TMPDIR=/mnt/efs/tmp`... that way AllenNLP won't use the 512MB limited resources available on /tmp, and instead use the EFS mount.

And with this in place it should be safe to got back to NLTK_DATA=/tmp/nltk_data (which would mean that the image doesn't need to be prebuilt as mentioned before).

**Comment by tomaarsen** [comment]
Wonderful! Glad to hear you got it working.
That said, my understanding is that there is still a bug in `is_writable` on AWS Lambda with EFS storage? Or do you not expect this to be a problem? 

I believe the usage of `is_writable` will defer to downloading to `~/nltk_data` if `is_writable` is bugged to exclusively return False on certain systems, which might not commonly be a problem.

**Comment by dnk8n** [comment]
Yeah despite my workaround, the NLTK library would still fail to make use of EFS with the checks in their current form. And in Lambda's case ${HOME} or ~/ is read-only so `~/nltk_data` is not suitable.
