### ISSUE TITLE
Pre commit hook fails

### ISSUE THREAD

**Issue by Madnex** [nltk/nltk#3027]
I have setup my development environment as described here: [Setting up a Development Environment](https://github.com/nltk/nltk/blob/develop/CONTRIBUTING.md#setting-up-a-development-environment). This is working so far and I could make changes and tests were running fine. However, when I want to make a commit I get the following error:

<details>
<summary>Commit Logs</summary>

<pre><code>08:24:09.076: [nltk] git -c core.quotepath=false -c log.showSignature=false add --ignore-errors -A -f -- nltk/stem/snowball.py nltk/translate/ibm5.py nltk/tokenize/casual.py
08:24:09.471: [nltk] git -c core.quotepath=false -c log.showSignature=false commit -F C:\Users\madnex\AppData\Local\Temp\git-commit-msg-.txt --
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\madnex\\.cache\\pre-commit\\repoxdo4288b\\py_env-default\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    Traceback (most recent call last):
      File "C:\Users\madnex\Anaconda3\envs\nltk\lib\runpy.py", line 196, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "C:\Users\madnex\Anaconda3\envs\nltk\lib\runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "C:\Users\madnex\.cache\pre-commit\repoxdo4288b\py_env-default\lib\site-packages\pip\__main__.py", line 29, in <module>
        from pip._internal.cli.main import main as _main
      File "C:\Users\madnex\.cache\pre-commit\repoxdo4288b\py_env-default\lib\site-packages\pip\_internal\cli\main.py", line 9, in <module>
        from pip._internal.cli.autocompletion import autocomplete
      File "C:\Users\madnex\.cache\pre-commit\repoxdo4288b\py_env-default\lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
        from pip._internal.cli.main_parser import create_main_parser
      File "C:\Users\madnex\.cache\pre-commit\repoxdo4288b\py_env-default\lib\site-packages\pip\_internal\cli\main_parser.py", line 8, in <module>
        from pip._internal.cli import cmdoptions
      File "C:\Users\madnex\.cache\pre-commit\repoxdo4288b\py_env-default\lib\site-packages\pip\_internal\cli\cmdoptions.py", line 24, in <module>
        from pip._internal.cli.parser import ConfigOptionParser
      File "C:\Users\madnex\.cache\pre-commit\repoxdo4288b\py_env-default\lib\site-packages\pip\_internal\cli\parser.py", line 12, in <module>
        from pip._internal.configuration import Configuration, ConfigurationError
      File "C:\Users\madnex\.cache\pre-commit\repoxdo4288b\py_env-default\lib\site-packages\pip\_internal\configuration.py", line 24, in <module>
        from pip._internal.utils import appdirs
      File "C:\Users\madnex\.cache\pre-commit\repoxdo4288b\py_env-default\lib\site-packages\pip\_internal\utils\appdirs.py", line 13, in <module>
        from pip._vendor import platformdirs as _appdirs
      File "C:\Users\madnex\.cache\pre-commit\repoxdo4288b\py_env-default\lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 42, in <module>
        PlatformDirs = _set_platform_dir_class()  #: Currently active platform
      File "C:\Users\madnex\.cache\pre-commit\repoxdo4288b\py_env-default\lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 21, in _set_platform_dir_class
        from pip._vendor.platformdirs.windows import Windows as Result
      File "C:\Users\madnex\.cache\pre-commit\repoxdo4288b\py_env-default\lib\site-packages\pip\_vendor\platformdirs\windows.py", line 3, in <module>
        import ctypes
      File "C:\Users\madnex\Anaconda3\envs\nltk\lib\ctypes\__init__.py", line 8, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: DLL load failed while importing _ctypes: The specified module could not be found.
Check the log at C:\Users\madnex\.cache\pre-commit\pre-commit.log
</code></pre>

</details>

I am using a conda environment with python 3.10.4 on a Windows 10 machine. So far I couldn't find any helpful info for this issue on the web. Any help would be appreciated :)

**Comment by tomaarsen** [comment]
Hello!

This seems to be an issue with `pre-commit` combined with `conda`. I've found a handful of other users with similar issues, e.g.:
* https://github.com/pre-commit/pre-commit/issues/1329
* https://github.com/JuliaPy/PyCall.jl/issues/963
* https://github.com/conda-forge/python-feedstock/issues/539
* https://github.com/materials-marketplace/standard-app-api/issues/6

In particular this comment *may* be helpful.
https://github.com/materials-marketplace/standard-app-api/issues/6#issuecomment-1144726898

I can't find a "direct fix", but hopefully you can find a solution in any of the links. Otherwise, it seems like it may work for Python 3.9.

**Comment by nlnjnj** [comment]
have the same issue with python 3.10.4 on a Windows 10，I fixed the issue by reinstalling python from the conda-forge channel.

```
conda config --add channels conda-forge
conda install python=3.10
```

**Comment by Madnex** [comment]
Thank you both for your help! 

This worked for me as well :)
> have the same issue with python 3.10.4 on a Windows 10，I fixed the issue by reinstalling python from the conda-forge channel.
> 
> ```
> conda config --add channels conda-forge
> conda install python=3.10
> ```

**Comment by tomaarsen** [comment]
Glad to hear it, I'll close this, then!
