### ISSUE TITLE
3.7: pep517 build fails

### ISSUE THREAD

**Issue by kloczek** [nltk/nltk#3032]
Looks like pep517 based build fails
```console
+ /usr/bin/sphinx-build -n -T -b man web build/sphinx/man
Running Sphinx v5.1.1
Generating HOWTO pages...
Generated 58 HOWTO pages.
Team data loaded!
Current team HTML page written!
Former team HTML page written!
making output directory... done
/home/tkloczko/rpmbuild/BUILD/nltk-3.7/nltk/app/__init__.py:29: UserWarning: nltk.app package not loaded (please install Tkinter library).
  warnings.warn("nltk.app package not loaded (please install Tkinter library).")
/home/tkloczko/rpmbuild/BUILD/nltk-3.7/nltk/draw/__init__.py:15: UserWarning: nltk.draw package not loaded (please install Tkinter library).
  warnings.warn("nltk.draw package not loaded (please install Tkinter library).")
*** Introductory Examples for the NLTK Book ***
Loading text1, ..., text9 and sent1, ..., sent9
Type the name of the text or sentence to view it.
Type: 'texts()' or 'sents()' to list the materials.

Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/nltk-3.7/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/home/tkloczko/rpmbuild/BUILD/nltk-3.7/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource gutenberg not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('gutenberg')

  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/gutenberg.zip/gutenberg/

  Searched in:
    - '/home/tkloczko/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/events.py", line 94, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/tkloczko/rpmbuild/BUILD/nltk-3.7/web/conf.py", line 43, in run_apidoc
    better_apidoc.main(
  File "/usr/lib/python3.8/site-packages/better_apidoc.py", line 758, in main
    modules = recurse_tree(rootpath, excludes, opts)
  File "/usr/lib/python3.8/site-packages/better_apidoc.py", line 615, in recurse_tree
    create_package_file(root, root_package, subpackage,
  File "/usr/lib/python3.8/site-packages/better_apidoc.py", line 496, in create_package_file
    mod_ns = _get_mod_ns(
  File "/usr/lib/python3.8/site-packages/better_apidoc.py", line 359, in _get_mod_ns
    mod = importlib.import_module(fullname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/tkloczko/rpmbuild/BUILD/nltk-3.7/nltk/book.py", line 27, in <module>
    text1 = Text(gutenberg.words("melville-moby_dick.txt"))
  File "/home/tkloczko/rpmbuild/BUILD/nltk-3.7/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/home/tkloczko/rpmbuild/BUILD/nltk-3.7/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/home/tkloczko/rpmbuild/BUILD/nltk-3.7/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/home/tkloczko/rpmbuild/BUILD/nltk-3.7/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource gutenberg not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('gutenberg')

  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/gutenberg

  Searched in:
    - '/home/tkloczko/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 261, in __init__
    self._init_builder()
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 334, in _init_builder
    self.events.emit('builder-inited')
  File "/usr/lib/python3.8/site-packages/sphinx/events.py", line 105, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function run_apidoc at 0x7f6a3a3e03a0> for event 'builder-inited' threw an exception (exception:
**********************************************************************
  Resource gutenberg not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('gutenberg')

  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/gutenberg

  Searched in:
    - '/home/tkloczko/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
)

Extension error:
Handler <function run_apidoc at 0x7f6a3a3e03a0> for event 'builder-inited' threw an exception (exception:
**********************************************************************
  Resource gutenberg not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('gutenberg')

  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/gutenberg

  Searched in:
    - '/home/tkloczko/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
)
```

**Comment by tomaarsen** [comment]
I know from #2992 that you are interested in building NLTK. Is your goal with the current traceback to build a local version of the website? The website requires certain NLTK resources to be installed, e.g. like `python -m nltk.downloader all`. 
If you are only trying to get NLTK built, then the website should not be necessary. Are you running the sphinx-build command manually, or is it automatically ran as a part of your build process? For completeness, I cannot reproduce your commands from #2992.

**Comment by kloczek** [comment]
> I know from #2992 that you are interested in building NLTK. Is your goal with the current traceback to build a local version of the website? The website requires certain NLTK resources to be installed, e.g. like `python -m nltk.downloader all`.

To be honest I'm only interested NLTK in context of packaging it as rpm pakage 😋 
In case of documentation I'm trying to add documentaion in form of roff outpt (man page),

Will drop you exact sequence of commnds in https://github.com/nltk/nltk/issues/2992

Did you try to reporoduce pep517 build procedure fail? 🤔

**Comment by tomaarsen** [comment]
I did.
Windows:
```
C:\GitHub\nltk> python -sBm build -w --no-isolation
C:\GitHub\nltk\.env39\Scripts\python.exe: No module named build.__main__; 'build' is a package and cannot be directly executed
```
WSL 2 - Ubuntu 20.04:
```
/mnt/c/GitHub/nltk$ python3 -sBm build -w --no-isolation
/usr/bin/python3: No module named build.__main__; 'build' is a package and cannot be directly executed
```

**Comment by kloczek** [comment]
Just plaese install `build` module from pypi.
https://pypi.org/project/build/

**Comment by tomaarsen** [comment]
Will do; didn't realise it was an external package.

**Comment by tomaarsen** [comment]
Our sphinx-build setup uses `sphinxcontrib.apidoc`, which uses `sphinx.ext.autodoc`. This extension will import all modules, even ones that are excluded. That way, all files that have side-effects when imported will have those side effects triggered. 
The only file for which we explicitly have side-effects is [nltk/book.py](https://github.com/nltk/nltk/blob/develop/nltk/book.py). I don't want to change the functionality here, as this file is used in the NLTK book. With other words, I don't want to protect this file behind a `if __name__ == "__main__":`.

That leaves me at a crossroads. On one side, building the documentation will run the `nltk/book.py`, and I don't want to remove the side-effects of `nltk/book.py`. This means that building the documentation simply requires those resources to be installed. 

As for https://github.com/nltk/nltk/issues/2992, I don't think it's weird to assume that additional resources must be downloaded before a test suite can be executed. It's simply one of the test suite requirements, in the same way that e.g. `pytest` is a requirement for the test suite.

**Comment by kloczek** [comment]
> As for https://github.com/nltk/nltk/issues/2992, I don't think it's weird to assume that additional resources must be downloaded before a test suite can be executed. It's simply one of the test suite requirements, in the same way that e.g. pytest is a requirement for the test suite.

`build` is not needed however it would be nice if pep517 based build would be working.
You can reproduce my testing procedure by install after (setuptools) build `nltk` in <install/prefix> (for example in /tmp/nltk-ptest) and than add proper base path in $PYTHONPATH in executed pytest env.

**Comment by kloczek** [comment]
I'm closing this ticket as I've manage to fix build procedure which now consist from:
- downloading https://github.com/nltk/nltk_data/archive/gh-pages/python-nltk-data.tar.gz
- unpack downloaded archove in nltk tree
- execute:
```console
mkdir nltk_data
mv nltk_data-gh-pages/packages/* nltk_data/
```
Use `NLTK_DATA=$PWD/nltk_data` on building and testing.
