### ISSUE TITLE
Error: Could not find or load main class edu.stanford.nlp.pipeline.StanfordCoreNLPServer

### ISSUE THREAD

**Issue by ehsong** [nltk/nltk#3052]
Hello, I am trying to use the Chinese example but I keep getting the following error. I tried executing the following in terminal after setting the directory to the folder where stanford-corenlp is installed:
```
java -Xmx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer \
-serverProperties StanfordCoreNLP-chinese.properties \
-preload tokenize,ssplit,pos,lemma,ner,parse \
-status_port 9001  -port 9001 -timeout 15000
```

But I get the following error:
```
[main] INFO CoreNLP - --- StanfordCoreNLPServer#main() called ---
Exception in thread "main" edu.stanford.nlp.io.RuntimeIOException: argsToProperties could not read properties file: StanfordCoreNLP-chinese.properties
	at edu.stanford.nlp.util.StringUtils.argsToProperties(StringUtils.java:1060)
	at edu.stanford.nlp.util.StringUtils.argsToProperties(StringUtils.java:973)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.<init>(StanfordCoreNLPServer.java:183)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.launchServer(StanfordCoreNLPServer.java:1590)
	at edu.stanford.nlp.pipeline.StanfordCoreNLPServer.main(StanfordCoreNLPServer.java:1644)
Caused by: java.io.IOException: Unable to open "StanfordCoreNLP-chinese.properties" as class path, filename or URL
	at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:501)
	at edu.stanford.nlp.io.IOUtils.readerFromString(IOUtils.java:634)
	at edu.stanford.nlp.util.StringUtils.argsToProperties(StringUtils.java:1051)
	... 4 more
[Thread-0] INFO CoreNLP - CoreNLP Server is shutting down.

```
Because I cannot execute the above, StanfordCoreNLP does not work for Chinese:

```
with CoreNLPServer() as server:
    parser = CoreNLPParser(server.url)

    # sentence = "This is my sentence, which I'd like to get parsed."
    sentence = '这是斯坦福中文分词器测试'
    tokenized = list(parser.tokenize(sentence))
    print(tokenized)

['这是斯坦福中文分词器测试']
```

**Comment by tomaarsen** [comment]
Make sure that you're running that `java` command from the right folder. See https://github.com/smilli/py-corenlp/issues/11 for more information. (Based on your edit, I see that you now are). I also want to refer you to the following pages of documentation:
* https://stanfordnlp.github.io/CoreNLP/download.html
* https://stanfordnlp.github.io/CoreNLP/human-languages.html
* https://stanfordnlp.github.io/CoreNLP/corenlp-server.html

Note also that if you run the server with `java` directly, then you do not need to *also* start it with NLTK: `CoreNLPServer` simply sets up an English variant of the CoreNLP server, which you do not need if you're also running it directly yourself.


```python
parser = CoreNLPParser(server.url)
sentence = '这是斯坦福中文分词器测试'
tokenized = list(parser.tokenize(sentence))
print(tokenized)
```

---

As for your most recent edit, it seems that you don't have the chinese model. The [documentation](https://stanfordnlp.github.io/CoreNLP/download.html) of CoreNLP states "Other languages: For working with another (human) language, you need additional model files."

**Comment by ehsong** [comment]
I solved the issue! In case if anyone is confused like me, you need to do the following:

1. Install stanford-corenlp
2. Separately download the Chinese properties .jar file from here https://stanfordnlp.github.io/CoreNLP/download.html and store it in the stanford-corenlp folder
3. Execute the example code of this repository
