### ISSUE TITLE
NLTK's `stopwords` requires the stopwords to be first downloaded via the NLTK Data installer. This is a one-time setup, after which you will be able to freely use `from nltk.corpus import stopwords`.

### ISSUE THREAD

**Issue by Killpit** [nltk/nltk#3107]
NLTK's `stopwords` requires the stopwords to be first downloaded via the NLTK Data installer. This is a one-time setup, after which you will be able to freely use `from nltk.corpus import stopwords`.

To download the stopwords, open the Python interpreter with `python` in your terminal of choice, and type:
```python
>>> import nltk
>>> nltk.download("stopwords")
```

Afterwards, you're good to go!

_Originally posted by @tomaarsen in https://github.com/nltk/nltk/issues/3063#issuecomment-1280529826_

**Comment by Killpit** [comment]
Even though I'm following the instructions of nltk library, I'm still having the same problem

**Comment by tomaarsen** [comment]
What kind of issues are you experiencing exactly? What happens after you call `nltk.download("stopwords")`? Are you experiencing the error from #3092? If so, please look in that issue, there is some advice which has helped others.

**Comment by Killpit** [comment]
`import numpy as np
import pandas as pd
from sklearn.feature_extraction import text
from sklearn.metrics.pairwise import cosine_similarity

data = pd.read_csv("/Users/atatekeli/PycharmProjects/NetflixRecm/netflixData.csv")
print(data.head())
print(data.info)
print(data.isnull().sum())

data = data[["Title", "Description", "Content Type", "Genres"]]
print(data.head())

data = data.dropna()

import nltk
import re
nltk.download('stopwords')
stemmer = nltk.SnowballStemmer("english")
from nltk.corpus import stopwords
import string
stopword=set(stopwords.words('english'))

def clean(text):
    text = str(text).lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)
    text = [word for word in text.split(' ') if word not in stopword]
    text=" ".join(text)
    text = [stemmer.stem(word) for word in text.split(' ')]
    text=" ".join(text)
    return text
data["Title"] = data["Title"].apply(clean)

print(data.Title.sample(10))`

**Comment by Killpit** [comment]
And this is the error message

[nltk_data] Error loading stopwords: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1129)>
Traceback (most recent call last):
  File "/Users/atatekeli/PycharmProjects/NetflixRecm/venv/lib/python3.9/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
  File "/Users/atatekeli/PycharmProjects/NetflixRecm/venv/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords.zip/stopwords/

  Searched in:
    - '/Users/atatekeli/nltk_data'
    - '/Users/atatekeli/PycharmProjects/NetflixRecm/venv/nltk_data'
    - '/Users/atatekeli/PycharmProjects/NetflixRecm/venv/share/nltk_data'
    - '/Users/atatekeli/PycharmProjects/NetflixRecm/venv/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/atatekeli/PycharmProjects/NetflixRecm/netflix_recm.py", line 22, in <module>
    stopword=set(stopwords.words('english'))
  File "/Users/atatekeli/PycharmProjects/NetflixRecm/venv/lib/python3.9/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/atatekeli/PycharmProjects/NetflixRecm/venv/lib/python3.9/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/Users/atatekeli/PycharmProjects/NetflixRecm/venv/lib/python3.9/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/Users/atatekeli/PycharmProjects/NetflixRecm/venv/lib/python3.9/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - '/Users/atatekeli/nltk_data'
    - '/Users/atatekeli/PycharmProjects/NetflixRecm/venv/nltk_data'
    - '/Users/atatekeli/PycharmProjects/NetflixRecm/venv/share/nltk_data'
    - '/Users/atatekeli/PycharmProjects/NetflixRecm/venv/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


Process finished with exit code 1

**Comment by tomaarsen** [comment]
This seems to be the problem:

```
[nltk_data] Error loading stopwords: <urlopen error [SSL:
[nltk_data] CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data] unable to get local issuer certificate (_ssl.c:1129)>
```

I haven't seen this before. Perhaps the help from this comment (or other comments in the thread) will resolve your issue:
https://stackoverflow.com/a/45018725/17936326. Presumably you are using Python 3.6? There are certainly some useful tips in that thread I think.

**Comment by simbadmorehod** [comment]
I have it worse, I downloaded but I think because of the permissions PyCharm can not find the file in the home directory, in general a very strange decision to do so,

**Comment by slpminn** [comment]
I am getting the same error on my localhost on a mac m3 with the following code:

import nltk
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.downloader import Downloader
try:
nltk.download('punkt')
except Exception as e:
print(f"Error downloading punkt resource: {e}")

text = """This is an example text. It has multiple sentences.
Let's see how NLTK tokenizes them. NLTK also provides functionalities
for other types of text processing tasks."""

print("Original text:")
print(text)

try:
sentences = nltk.sent_tokenize(text)
print("\nSentences after tokenization:")
for sentence in sentences:
print(sentence)
except Exception as e:
print(f"Error during sentence tokenization: {e}")

**Comment by zmvmarina** [comment]
I have the same issue with my m2 mac and python 12
Only this worked for me: https://stackoverflow.com/questions/41348621/ssl-error-downloading-nltk-data/42890688#42890688

**Comment by slpminn** [comment]
Hi @zmvmarina,

Thanks.  I found that article earlier, but I did not have time to implement.  But now I did, and it did worked for me too.

Thanks a bunch.

**Comment by saireethi6** [comment]
what worked for me was to check the internet connection (I was using mobile hotspot as my wi-fi was messing with me) and also to run the following in the system terminal and NOT my IDE (PyCharm) terminal.

`>>> import nltk`
`>>> nltk.download('stopwords')`

Hope that helps!

**Comment by Iis-75-contrived705** [comment]
> Hi [@zmvmarina](https://github.com/zmvmarina),
> 
> Thanks. I found that article earlier, but I did not have time to implement. But now I did, and it did worked for me too.
> 
> Thanks a bunch.





https://melpreview3.github.io/xd9QKYugUSW5vUscPzieNiFvOc2FxSaPudZorqcnZRffKC4pu/

**Comment by ekaf** [comment]
So we can assume this is solved?
