### ISSUE TITLE
nltk.parse.MaltParser instantiation fails if malt .jar not found on hardcoded path list

### ISSUE THREAD

**Issue by klabble** [nltk/nltk#311]
Although MaltParser.config_malt accepts a "bin" parameter to specify the malt .jar file location, MaltParser.**init** does not itself have this parameter, so there is no way for the code that instantiates a MaltParser object to pass in this path.

The list of paths that config_malt checks are not applicable on a Windows system.  It would be nice if a "bin" parameter could be added to MaltParser.**init** and passed down to config_malt.

```
>>> import nltk
>>> nltk.parse.MaltParser()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\python27\lib\site-packages\nltk\parse\malt.py", line 34, in __init__
    self.config_malt()
  File "c:\python27\lib\site-packages\nltk\parse\malt.py", line 85, in config_malt
    verbose=verbose)
  File "c:\python27\lib\site-packages\nltk\internals.py", line 528, in find_binary
    url, verbose)
  File "c:\python27\lib\site-packages\nltk\internals.py", line 512, in find_file
    raise LookupError('\n\n%s\n%s\n%s' % (div, msg, div))
```

**Comment by alvations** [comment]
Closing this because MaltParser API has been revamped and should be stable now, see #943 and  #944
