### ISSUE TITLE
 AttributeError: module 'numpy' has no attribute 'int'.

### ISSUE THREAD

**Issue by Abonia1** [nltk/nltk#3170]
Hello,
Python version: 3.8.8
NumPy version: 1.24.3
NLTK version: 3.8.1

I have update the numpy and nltk but can't fix gthe below issue:

AttributeError Traceback (most recent call last)
in
----> 1 import nltk

~/opt/anaconda3/lib/python3.8/site-packages/nltk/init.py in
144 ###########################################################
145
--> 146 from nltk.chunk import *
147 from nltk.classify import *
148 from nltk.inference import *

~/opt/anaconda3/lib/python3.8/site-packages/nltk/chunk/init.py in
153 """
154
--> 155 from nltk.chunk.api import ChunkParserI
156 from nltk.chunk.regexp import RegexpChunkParser, RegexpParser
157 from nltk.chunk.util import (

~/opt/anaconda3/lib/python3.8/site-packages/nltk/chunk/api.py in
11 ##//////////////////////////////////////////////////////
12
---> 13 from nltk.chunk.util import ChunkScore
14 from nltk.internals import deprecated
15 from nltk.parse import ParserI
...

AttributeError: module 'numpy' has no attribute 'int'.
np.int was a deprecated alias for the builtin int. To avoid this error in existing code, use int by itself. Doing this will not modify any behavior and is safe. When replacing np.int, you may wish to use e.g. np.int64 or np.int32 to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

Thanks in advance

**Comment by ThomasBur** [comment]
Hi @Abonia1 I can't seem to replicate this, and `/nltk$ grep -r "numpy.int"` and `/nltk$ grep -r "np.int"` both don't return any results.

Was this issue resolved when there were other efforts to remove numpy dependencies?

**Comment by liam0949** [comment]
I had a similar issue.

**Comment by lucaswiman** [comment]
This can result from an old version of a related library that nltk conditionally uses, e.g. scikit-learn. I observed this issue in a poetry-managed environment, where there was an old version of scikit-learn pinned in the pyproject.toml file:
```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/venv/lib/python3.8/site-packages/nltk/__init__.py", line 146, in <module>
    from nltk.chunk import *
  File "/venv/lib/python3.8/site-packages/nltk/chunk/__init__.py", line 155, in <module>
    from nltk.chunk.api import ChunkParserI
  File "/venv/lib/python3.8/site-packages/nltk/chunk/api.py", line 13, in <module>
    from nltk.chunk.util import ChunkScore
  File "/venv/lib/python3.8/site-packages/nltk/chunk/util.py", line 12, in <module>
    from nltk.tag.mapping import map_tag
  File "/venv/lib/python3.8/site-packages/nltk/tag/__init__.py", line 72, in <module>
    from nltk.tag.sequential import (
  File "/venv/lib/python3.8/site-packages/nltk/tag/sequential.py", line 26, in <module>
    from nltk.classify import NaiveBayesClassifier
  File "/venv/lib/python3.8/site-packages/nltk/classify/__init__.py", line 97, in <module>
    from nltk.classify.scikitlearn import SklearnClassifier
  File "/venv/lib/python3.8/site-packages/nltk/classify/scikitlearn.py", line 38, in <module>
    from sklearn.feature_extraction import DictVectorizer
  File "/venv/lib/python3.8/site-packages/sklearn/feature_extraction/__init__.py", line 9, in <module>
    from .image import img_to_graph, grid_to_graph
  File "/venv/lib/python3.8/site-packages/sklearn/feature_extraction/image.py", line 172, in <module>
    dtype=np.int):
  File "/venv/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'
```

I suspect something similar happened to OP, though it's hard to tell without the full stack trace.

**Comment by jbbqqf** [comment]
Hi! Triaging older issues — this is `AttributeError: module 'numpy' has no attribute 'int'` coming from a transitive dependency (typically an older `scikit-learn`), not from NLTK itself.

Evidence:
- `grep -rn 'np\.int\b\|numpy\.int\b' nltk/` on `develop` returns no matches — NLTK does not use the removed `numpy.int` alias.
- `numpy.int` was deprecated in NumPy 1.20 and removed in NumPy 1.24 ([NumPy 1.20 deprecations](https://numpy.org/doc/stable/release/1.20.0-notes.html#deprecations)), so the error originates wherever `numpy.int` is still imported — most commonly an older `scikit-learn`, as @lucaswiman pointed out above.
- @ThomasBur already confirmed the absence of `np.int` / `numpy.int` in the NLTK codebase.

If I'm wrong about NLTK being free of `np.int` on `develop` — let me know which file you saw it in. Otherwise the resolution lives downstream (`pip install -U scikit-learn` or pin numpy<1.24), and this can be closed.

---
*Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the grep above and the NumPy release notes were verified manually.*

**Comment by ekaf** [comment]
Not an NLTK bug. Thanks @jbbqqf!
