### ISSUE TITLE
ImportError: mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')

### ISSUE THREAD

**Issue by HuaYuXiao** [nltk/nltk#3171]
Mac version: MacBook Pro M1 2020
MacOS: 13.4.1
python version: 3.11.3

Traceback (most recent call last):
  File "/Users/hyx020222/Library/Mobile Documents/com~apple~CloudDocs/project/NLP/main.py", line 1, in <module>
    import nltk
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nltk/__init__.py", line 138, in <module>
    from nltk.text import *
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nltk/text.py", line 29, in <module>
    from nltk.tokenize import sent_tokenize
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nltk/tokenize/__init__.py", line 65, in <module>
    from nltk.tokenize.casual import TweetTokenizer, casual_tokenize
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nltk/tokenize/casual.py", line 49, in <module>
    import regex  # https://github.com/nltk/nltk/issues/2409
    ^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/regex/__init__.py", line 1, in <module>
    from .regex import *
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/regex/regex.py", line 421, in <module>
    import regex._regex_core as _regex_core
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/regex/_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/regex/_regex.cpython-311-darwin.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/regex/_regex.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/regex/_regex.cpython-311-darwin.so' (no such file), '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/regex/_regex.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

**Comment by malinamedusa** [comment]
(lovenv) malinamedusa@MacBook-Pro test-task-for-Aero % python3 load_data_in_table.py
Traceback (most recent call last):
  File "/Users/malinamedusa/PycharmProjects/test-task-for-Aero/lovenv/lib/python3.12/site-packages/requests/compat.py", line 11, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/malinamedusa/PycharmProjects/test-task-for-Aero/load_data_in_table.py", line 1, in <module>
    from connector import LoadingDataHTTPtoPG
  File "/Users/malinamedusa/PycharmProjects/test-task-for-Aero/connector.py", line 2, in <module>
    import requests
  File "/Users/malinamedusa/PycharmProjects/test-task-for-Aero/lovenv/lib/python3.12/site-packages/requests/__init__.py", line 45, in <module>
    from .exceptions import RequestsDependencyWarning
  File "/Users/malinamedusa/PycharmProjects/test-task-for-Aero/lovenv/lib/python3.12/site-packages/requests/exceptions.py", line 9, in <module>
    from .compat import JSONDecodeError as CompatJSONDecodeError
  File "/Users/malinamedusa/PycharmProjects/test-task-for-Aero/lovenv/lib/python3.12/site-packages/requests/compat.py", line 13, in <module>
    import charset_normalizer as chardet
  File "/Users/malinamedusa/PycharmProjects/test-task-for-Aero/lovenv/lib/python3.12/site-packages/charset_normalizer/__init__.py", line 24, in <module>
    from .api import from_bytes, from_fp, from_path, is_binary
  File "/Users/malinamedusa/PycharmProjects/test-task-for-Aero/lovenv/lib/python3.12/site-packages/charset_normalizer/api.py", line 5, in <module>
    from .cd import (
  File "/Users/malinamedusa/PycharmProjects/test-task-for-Aero/lovenv/lib/python3.12/site-packages/charset_normalizer/cd.py", line 14, in <module>
    from .md import is_suspiciously_successive_range
ImportError: dlopen(/Users/malinamedusa/PycharmProjects/test-task-for-Aero/lovenv/lib/python3.12/site-packages/charset_normalizer/md.cpython-312-darwin.so, 0x0002): tried: '/Users/malinamedusa/PycharmProjects/test-task-for-Aero/lovenv/lib/python3.12/site-packages/charset_normalizer/md.cpython-312-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/malinamedusa/PycharmProjects/test-task-for-Aero/lovenv/lib/python3.12/site-packages/charset_normalizer/md.cpython-312-darwin.so' (no such file), '/Users/malinamedusa/PycharmProjects/test-task-for-Aero/lovenv/lib/python3.12/site-packages/charset_normalizer/md.cpython-312-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
**(lovenv) malinamedusa@MacBook-Pro test-task-for-Aero % arch
arm64**

I have the same problem although I have arm64 
found it here https://dotnet.microsoft.com/en-us/download

**Comment by Higgs32584** [comment]
I got the same issue

**Comment by emburse-manikamidha** [comment]
I get error when I write - from pdfminer.high_level import extract_text 

from .md import is_suspiciously_successive_range
ImportError: dlopen(/Library/Python/3.9/site-packages/charset_normalizer/md.cpython-39-darwin.so, 0x0002): tried: '/Library/Python/3.9/site-packages/charset_normalizer/md.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Python/3.9/site-packages/charset_normalizer/md.cpython-39-darwin.so' (no such file), '/Library/Python/3.9/site-packages/charset_normalizer/md.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

**Comment by rmalouf** [comment]
These don't appear to be problems with NLTK. The first is a problem with regex and the second is a problem with charset_normalizer which is a dependency of requests. And for both of the issue appears to be that you're running python under rosetta 2 but had installed the libraries in native apple silicon mode, or vice versa.

Do you get these same errors with a fresh install of python and NLTK?

**Comment by jbbqqf** [comment]
Hi! Triaging older issues — the error originates in the `regex` package, not in NLTK.

Evidence:
- The traceback ends with `ImportError: dlopen(.../regex/_regex.cpython-311-darwin.so, ...): tried: '...' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))` — the failing `.so` is `regex/_regex.cpython-311-darwin.so`, a compiled extension belonging to the `regex` PyPI package.
- This happens when the `regex` wheel installed in the env was built for x86_64 but the Python interpreter is arm64 (or vice versa). The fix is environment-level: `pip uninstall regex && pip install --no-binary :all: regex` or use a native arm64 Python (e.g. via `python.org` universal2 installer / `arch -arm64 python3 -m pip install regex`).
- NLTK only imports `regex` (see https://github.com/nltk/nltk/blob/develop/nltk/tokenize/casual.py); it does not bundle the extension.

If I'm wrong about the dylib being from the `regex` package on your machine — please run `python -c "import regex; print(regex.__file__)"` and share the output. Otherwise this can be closed as out-of-scope for NLTK.

---
*Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the traceback reading and the `regex` package origin were verified manually.*

**Comment by ekaf** [comment]
Environment / dependency architecture mismatch, not NLTK. Thanks @jbbqqf!
