### ISSUE TITLE
Trouble with installation importing nltk

### ISSUE THREAD

**Issue by davidam** [nltk/nltk#3192]
Hello,

I'm using NLTK installed with pip in a python environment using Python 3.12 installed from sources in Ubuntu.

Now, I import nltk having troubles with sqlite and sqlite is not a dependency:
>>> import nltk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/davidam/.local/lib/python3.12/site-packages/nltk/__init__.py", line 153, in <module>
    from nltk.translate import *
  File "/home/davidam/.local/lib/python3.12/site-packages/nltk/translate/__init__.py", line 24, in <module>
    from nltk.translate.meteor_score import meteor_score as meteor
  File "/home/davidam/.local/lib/python3.12/site-packages/nltk/translate/meteor_score.py", line 13, in <module>
    from nltk.corpus import WordNetCorpusReader, wordnet
  File "/home/davidam/.local/lib/python3.12/site-packages/nltk/corpus/__init__.py", line 64, in <module>
    from nltk.corpus.reader import *
  File "/home/davidam/.local/lib/python3.12/site-packages/nltk/corpus/reader/__init__.py", line 106, in <module>
    from nltk.corpus.reader.panlex_lite import *
  File "/home/davidam/.local/lib/python3.12/site-packages/nltk/corpus/reader/panlex_lite.py", line 15, in <module>
    import sqlite3
  File "/opt/Python-3.12.0/Lib/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/opt/Python-3.12.0/Lib/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

**Comment by davidam** [comment]
Trouble with my personal installation
