### ISSUE TITLE
Problems Running Examples Starting with Babelize

### ISSUE THREAD

**Issue by mdebellis** [nltk/nltk#3196]
I'm an experienced programmer but just learned Python this year and have been focusing on a specific project so I'm probably doing something basic wrong. I started working through the examples in the book and the ones in the first chapter worked until I got to babelize. I'm using the PyCharm IDE. When I do 
`babelize_shell()`
I get the error:
```
Traceback (most recent call last):
  File "C:\Users\mdebe\miniconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-85-7420127cd0cd>", line 1, in <module>
    babelize_shell()
NameError: name 'babelize_shell' is not defined
```
I have everything loaded. In the same shell I did all the previous exercises. The last one that worked was:
```
word length is less than 5
for word in ['Call','me','Ishmael','.']:
    print(word)
    
Call
me
Ishmael
```
Also, when Babelize didn't work I did:
`from nltk.book import *`
Even though I'm virtually certain I had already done that. I don't think the previous examples would have worked otherwise. I didn't mind missing out on the babelize examples because I understood the concept and Machine Translation is not something I need now anyway so I read through those. But then the Corpus examples in Chapter 2 don't seem to be working either. When I do:
`nltk.corpus.gutenberg.fileids()`
I get the error:
```
Traceback (most recent call last):
  File "C:\Users\mdebe\miniconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-89-593d19326ce9>", line 1, in <module>
    nltk.corpus.gutenberg.fileids()
```
I did
`import nltk`
in the Python interpreter before the attempt to invoke gutenberg and didn't get any errors. 
This probably isn't relevant but one other issue I've had is that in the book the print statements don't have parens around the arguments. E.g., 
```
for word in ['Call','me','Ishmael','.']:
    print word 
```
is the way it is in the book but I thought print was a function so the arguments needed to be in parens and I did get an error when I used the book syntax  but when I put the arguments in parens:
```
for word in ['Call','me','Ishmael','.']:
    print(word)
```
Then it works. The thing I really need though is to get the Corpus examples to work because that's very releavant to the work I want to do. Thanks for any help.
Michael DeBellis

**Comment by mdebellis** [comment]
It was just a typing mistake. I still can't see the mistake but when I copied the code from the book and pasted it, it worked.
