### ISSUE TITLE
sourcedstring.doctest fails

### ISSUE THREAD

**Issue by kmike** [nltk/nltk#322]
```
$ tox -e py27 -- -vs sourcedstring.doctest
GLOB sdist-make: /Users/kmike/svn/nltk/setup.py
py27-nodeps sdist-reinst: /Users/kmike/svn/nltk/.tox/dist/nltk-2.0.4.zip
py27-nodeps runtests: commands[0]
Doctest: sourcedstring.doctest ... FAIL

======================================================================
FAIL: Doctest: sourcedstring.doctest
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/doctest.py", line 2163, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for sourcedstring.doctest
  File "/Users/kmike/svn/nltk/nltk/test/sourcedstring.doctest", line 0

----------------------------------------------------------------------
File "/Users/kmike/svn/nltk/nltk/test/sourcedstring.doctest", line 1246, in sourcedstring.doctest
Failed example:
    re.sub('better', 'worse', sent)
Expected:
    'I got worse.'
Got:
    'I got worse.'@[27:33,27:27,...,27:27,39:40]
----------------------------------------------------------------------
File "/Users/kmike/svn/nltk/nltk/test/sourcedstring.doctest", line 1254, in sourcedstring.doctest
Failed example:
    re.sub('better', 'worse', sent)
Expected:
    'I got worse.'
Got:
    'I got worse.'@[27:33,27:27,...,27:27,39:40]
```

So `re.sub(pattern, repl, sourced_string)` returns a SourcedString even without calling `SourcedStringRegexp.patch_re_module()` (it is different from a patched version though).

What is the desired behavior?

**Comment by kmike** [comment]
I boldly removed nltk.sourcedstring in 2and3.
