### ISSUE TITLE
[BUG] _pickle.UnpicklingError: global 'copy_reg._reconstructor' is forbidden

### ISSUE THREAD

**Issue by shrey-gupta-2809** [nltk/nltk#3298]
When using NLTK version `3.8.2`, the following line results in an error:
```bash
$ python
Python 3.8.8 (default, Mar 31 2021, 12:29:49)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
>>> sentence_tokenizer = nltk.data.load("tokenizers/punkt/english.pickle")
/usr/local/lib/python3.8/site-packages/nltk/app/__init__.py:45: UserWarning: nltk.app.wordfreq not loaded (requires the matplotlib library).
  warnings.warn("nltk.app.wordfreq not loaded (requires the matplotlib library).")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/nltk/data.py", line 763, in load
    resource_val = restricted_pickle_load(opened_resource.read())
  File "/usr/local/lib/python3.8/site-packages/nltk/data.py", line 667, in restricted_pickle_load
    return RestrictedUnpickler(BytesIO(string)).load()
  File "/usr/local/lib/python3.8/site-packages/nltk/app/wordnet_app.py", line 664, in find_class
    raise pickle.UnpicklingError(f"global '{module}.{name}' is forbidden")
_pickle.UnpicklingError: global 'copy_reg._reconstructor' is forbidden
```
pickle version is `4.0.0`

Fix: Downgrading NLTK from `3.8.2` to `3.8.1` fixes the above issue.

**Comment by ekaf** [comment]
@shrey-gupta-2809, this is now the expected behaviour when you try to load a complex pickle. It solves a highly critical vulnerability: please see #3266.
Because of the severity of the potential attacks, downgrading to 3.8.1 is not advisable.
