### ISSUE TITLE
Chicken-and-egg problem with downloading wordnet in GitHub Action

### ISSUE THREAD

**Issue by peterbe** [nltk/nltk#3315]
I have in my GitHub Action something like this:

```yaml
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip wheel --progress-bar off
          pip install -r requirements.txt --progress-bar off

      - name: Download NLTK dependencies
        run: python scripts/nltk-downloads.py

```
and in `requirements.txt` it has 

```
nltk==3.9 \
    --hash=sha256:d17863e861bb33ac617893329d71d06a3dfb7e3eb9ee0b8105281c53944a45a1 \
    --hash=sha256:e98acac454407fa38b76cccb29208d377731cf7fab68f323754a3681f104531f
```

The script `scripts/nltk-downloads.py` looks exactly like this:

```python
import nltk

nltk.download("wordnet")
```

But that step of the Action workflow fails with ...

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.[12](https://github.com/peterbe/django-peterbecom/actions/runs/10603699164/job/29388628603#step:17:13).5/x64/lib/python3.12/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nltk/data.py", line 579, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource wordnet not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('wordnet')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/wordnet.zip/wordnet/

  Searched in:
    - '/home/runner/nltk_data'
    - '/opt/hostedtoolcache/Python/3.12.5/x64/nltk_data'
    - '/opt/hostedtoolcache/Python/3.12.5/x64/share/nltk_data'
    - '/opt/hostedtoolcache/Python/3.12.5/x64/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/django-peterbecom/django-peterbecom/scripts/nltk-downloads.py", line 2, in <module>
    import nltk
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nltk/__init__.py", line 153, in <module>
    from nltk.translate import *
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nltk/translate/__init__.py", line 24, in <module>
    from nltk.translate.meteor_score import meteor_score as meteor
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nltk/translate/meteor_score.py", line 14, in <module>
    from nltk.stem.api import StemmerI
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nltk/stem/__init__.py", line 34, in <module>
    from nltk.stem.wordnet import WordNetLemmatizer
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nltk/stem/wordnet.py", line [13](https://github.com/peterbe/django-peterbecom/actions/runs/10603699164/job/29388628603#step:17:14), in <module>
    class WordNetLemmatizer:
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nltk/stem/wordnet.py", line 48, in WordNetLemmatizer
    morphy = wn.morphy
             ^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nltk/corpus/util.py", line 120, in __getattr__
    self.__load()
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nltk/corpus/util.py", line 86, in __load
    raise e
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/nltk/data.py", line 579, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource wordnet not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('wordnet')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/wordnet

  Searched in:
    - '/home/runner/nltk_data'
    - '/opt/hostedtoolcache/Python/3.12.5/x64/nltk_data'
    - '/opt/hostedtoolcache/Python/3.12.5/x64/share/nltk_data'
    - '/opt/hostedtoolcache/Python/3.12.5/x64/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
```

**Comment by ekaf** [comment]
@peterbe, this was solved in #3309 and NLTK release 3.9.1. 

It was a well-known problem with NLTK 3.9 and #3308 suggests a workaround, but the obvious fix is to update your NLTK version to 3.9.1.
