### ISSUE TITLE
ImportError: cannot import name 'Huber' from 'sklearn.linear_model._sgd_fast'

### ISSUE THREAD

**Issue by cesarrodrig** [nltk/nltk#3346]
After installing `nltk==3.9.1` and attempting to download a model:

```python
import nltk

nltk.download("stopwords")
nltk.download("punkt_tab")
```

I get an error:

```
[nltk_data] Downloading package stopwords to /github/home/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt_tab to /github/home/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/wtpsplit/__init__.py", line 12, in <module>
    import skops.io as sio
  File "/usr/local/lib/python3.11/site-packages/skops/io/__init__.py", line 1, in <module>
    from ._persist import dump, dumps, get_untrusted_types, load, loads
  File "/usr/local/lib/python3.11/site-packages/skops/io/_persist.py", line 22, in <module>
    module = importlib.import_module(module_name, package="skops.io")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/skops/io/_sklearn.py", line 15, in <module>
    from sklearn.linear_model._sgd_fast import (
ImportError: cannot import name 'Huber' from 'sklearn.linear_model._sgd_fast' (/usr/local/lib/python3.11/site-packages/sklearn/linear_model/_sgd_fast.cpython-311-x86_64-linux-gnu.so)
```

Also tried with `3.8.1` and the same error happened. 

How can I solve this import error? Thank you.

**Comment by tpanum** [comment]
It's a breaking change from `scikit-learn>=1.6.0`. If you ensure to use `scikit-learn<1.6` it will work again.

`skops` needs to be compatible with the new version, see [this issue](https://github.com/skops-dev/skops/issues/454).

**Comment by cesarrodrig** [comment]
Thanks, I updated the dependency.
