### ISSUE TITLE
NLTK downloader doesn't work without already downloaded files

### ISSUE THREAD

**Issue by szotsaki** [nltk/nltk#3347]
It seems that in order to download files, those files had to be downloaded beforehand. 

```
$ python3 -m nltk.downloader all

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/nltk/data.py", line 579, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource wordnet not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('wordnet')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/wordnet.zip/wordnet/

  Searched in:
    - '/root/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
```

Even by importing the module it shows this error message:

```python
> python3 
Python 3.11.11 (main, Dec 04 2024, 21:44:34) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/nltk/corpus/util.py", line 84, in __load
    root = nltk.data.find(f"{self.subdir}/{zip_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/nltk/data.py", line 579, in find
    raise LookupError(resource_not_found)
LookupError:
[...]
```

Version: 3.9.1-2.2

**Comment by ekaf** [comment]
Nltk 3.9.1 is probably not installed under your default Python3, but somewhere else.
It seems likely that the Nltk version that you have under your default Python3 is a broken, older version of Nltk.

**Comment by szotsaki** [comment]
Hmm, I see; thanks for the reply! Unfortunately, managing python packages is very cumbersome when it has to race with the OS package manager; it can cause this issue.

I'll close this bug then.
