### ISSUE TITLE
segmentation.doctest fails

### ISSUE THREAD

**Issue by kmike** [nltk/nltk#386]
Failure is the following:

```
======================================================================
FAIL: Doctest: segmentation.doctest
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 2166, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for segmentation.doctest
  File "/Users/kmike/svn/nltk/nltk/test/segmentation.doctest", line 0

----------------------------------------------------------------------
File "/Users/kmike/svn/nltk/nltk/test/segmentation.doctest", line 73, in segmentation.doctest
Failed example:
    print(round(pk('100100', '111111', 2), 6))
Expected:
    0.64
Got:
    0.4
----------------------------------------------------------------------
File "/Users/kmike/svn/nltk/nltk/test/segmentation.doctest", line 75, in segmentation.doctest
Failed example:
    print(round(pk('100100', '000000', 2), 6))
Expected:
    0.04
Got:
    0.6
----------------------------------------------------------------------
File "/Users/kmike/svn/nltk/nltk/test/segmentation.doctest", line 77, in segmentation.doctest
Failed example:
    print(pk('100100', '111111', 3))
Expected:
    0.25
Got:
    0.0
----------------------------------------------------------------------
File "/Users/kmike/svn/nltk/nltk/test/segmentation.doctest", line 79, in segmentation.doctest
Failed example:
    print(pk('100100', '000000', 3))
Expected:
    0.25
Got:
    1.0
```

I think they start failing after Pk metric correction in https://github.com/nltk/nltk/commit/f9a895ddef9a57542d311d7fc22432b49e746d82 . 

@DavidDoukhan, do you have ideas which values are correct? 

`nltk/test/runtests.py nltk/test/segmentation.doctest` runs this test (nose should be installed).

**Comment by alvations** [comment]
@kmike is this resolved in https://github.com/nltk/nltk/blob/develop/nltk/test/segmentation_fixt.py ?
