### ISSUE TITLE
childes.doctest is broken

### ISSUE THREAD

**Issue by kmike** [nltk/nltk#411]
It seems that childes.doctest becomes broken after fixing https://github.com/nltk/nltk/issues/347.

Not all words returned by `.tagged_words` are now tagged, it looks like a real issue.

Errors:

```
======================================================================
FAIL: Doctest: childes.doctest
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 2201, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for childes.doctest
  File "/Users/kmike/svn/nltk/nltk/test/childes.doctest", line 0

----------------------------------------------------------------------
File "/Users/kmike/svn/nltk/nltk/test/childes.doctest", line 84, in childes.doctest
Failed example:
    valian.tagged_words('Valian/01a.xml')[:30]
Expected:
    [('at', 'prep'), ('Parent', 'n'), ("Lastname's", 'n'), ('house', 'n'),
     ('with', 'prep'), ('Child', 'n'), ('Lastname', 'n'), ('and', 'coord'),
     ('it', 'pro'), ('is', 'v'), ('March', 'n'), ('fourth', 'adj'),
     ('I', 'pro'), ('believe', 'v'), ('and', 'coord'), ('when', 'adv'),
     ('was', 'v'), ("Parent's", 'n'), ('birthday', 'n'), ("Child's", 'n'),
     ('oh', 'co'), ("I'm", 'pro'), ('sorry', 'adj'), ("that's", 'pro'),
     ('okay', 'adj'), ('February', 'n'), ('first', 'adj'),
     ('nineteen', 'det'), ('eighty', 'det'), ('four', 'det')]
Got:
    [('at', 'prep'), 'Parent', "Lastname's", ('house', 'n'), ('with', 'prep'), 'Child', 'Lastname', ('and', 'coord'), ('it', 'pro'), 'is', 'March', ('fourth', 'adj'), 'I', ('believe', 'v'), ('and', 'coord'), 'when', 'was', "Parent's", ('birthday', 'n'), "Child's", ('oh', 'co'), "I'm", ('sorry', 'adj'), "that's", ('okay', 'adj'), 'February', ('first', 'adj'), 'nineteen', 'eighty', 'four']
----------------------------------------------------------------------
File "/Users/kmike/svn/nltk/nltk/test/childes.doctest", line 94, in childes.doctest
Failed example:
    valian.tagged_sents('Valian/01a.xml')[:10]
Expected:
    [[('at', 'prep'), ('Parent', 'n'), ("Lastname's", 'n'), ('house', 'n'),
     ('with', 'prep'), ('Child', 'n'), ('Lastname', 'n'), ('and', 'coord'),
     ('it', 'pro'), ('is', 'v'), ('March', 'n'), ('fourth', 'adj'),
     ('I', 'pro'), ('believe', 'v'), ('and', 'coord'), ('when', 'adv'),
     ('was', 'v'), ("Parent's", 'n'), ('birthday', 'n')],
     [("Child's", 'n')], [('oh', 'co'), ("I'm", 'pro'), ('sorry', 'adj')],
     [("that's", 'pro'), ('okay', 'adj')],
     [('February', 'n'), ('first', 'adj'), ('nineteen', 'det'),
     ('eighty', 'det'), ('four', 'det')],
     [('great', 'adj')],
     [('and', 'coord'), ("she's", 'pro'), ('two', 'det'), ('years', 'n'), ('old', 'adj')],
     [('correct', 'adj')],
     [('okay', 'co')],
     [('she', 'pro'), ('just', 'adv'), ('turned', 'part'), ('two', 'det'),
     ('a', 'det'), ('month', 'n'), ('ago', 'adv')]]
Got:
    [[('at', 'prep'), 'Parent', "Lastname's", ('house', 'n'), ('with', 'prep'), 'Child', 'Lastname', ('and', 'coord'), ('it', 'pro'), 'is', 'March', ('fourth', 'adj'), 'I', ('believe', 'v'), ('and', 'coord'), 'when', 'was', "Parent's", ('birthday', 'n')], ["Child's"], [('oh', 'co'), "I'm", ('sorry', 'adj')], ["that's", ('okay', 'adj')], ['February', ('first', 'adj'), 'nineteen', 'eighty', 'four'], [('great', 'adj')], [('and', 'coord'), "she's", 'two', ('years', 'n'), ('old', 'adj')], [('correct', 'adj')], [('okay', 'co')], ['she', 'just', ('turned', 'part'), 'two', ('a', 'det'), ('month', 'n'), ('ago', 'adv')]]
----------------------------------------------------------------------
File "/Users/kmike/svn/nltk/nltk/test/childes.doctest", line 131, in childes.doctest
Failed example:
    valian.words('Valian/01a.xml',relation=True)[:10]
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 1289, in __run
        compileflags, 1) in test.globs
      File "<doctest childes.doctest[22]>", line 1, in <module>
        valian.words('Valian/01a.xml',relation=True)[:10]
      File "/Users/kmike/svn/nltk/nltk/corpus/reader/childes.py", line 64, in words
        pos, strip_space, replace) for fileid in self.abspaths(fileids)])
      File "/Users/kmike/svn/nltk/nltk/corpus/reader/childes.py", line 331, in _get_words
        word = (word[0], word[1],
    IndexError: string index out of range
----------------------------------------------------------------------
File "/Users/kmike/svn/nltk/nltk/test/childes.doctest", line 147, in childes.doctest
Failed example:
    valian.MLU()
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 1289, in __run
        compileflags, 1) in test.globs
      File "<doctest childes.doctest[26]>", line 1, in <module>
        valian.MLU()
      File "/Users/kmike/svn/nltk/nltk/corpus/reader/childes.py", line 220, in MLU
        for fileid in self.abspaths(fileids)]
      File "/Users/kmike/svn/nltk/nltk/corpus/reader/childes.py", line 230, in _getMLU
        posList = [pos for (word,pos) in sent]
    ValueError: too many values to unpack
----------------------------------------------------------------------
File "/Users/kmike/svn/nltk/nltk/test/childes.doctest", line 154, in childes.doctest
Failed example:
    valian.MLU('Valian/01a.xml')
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 1289, in __run
        compileflags, 1) in test.globs
      File "<doctest childes.doctest[27]>", line 1, in <module>
        valian.MLU('Valian/01a.xml')
      File "/Users/kmike/svn/nltk/nltk/corpus/reader/childes.py", line 220, in MLU
        for fileid in self.abspaths(fileids)]
      File "/Users/kmike/svn/nltk/nltk/corpus/reader/childes.py", line 230, in _getMLU
        posList = [pos for (word,pos) in sent]
    ValueError: too many values to unpack
```

**Comment by pfeyz** [comment]
it looks like [line 319](https://github.com/nltk/nltk/blob/1b2fbd1cd8742f18f7857d488651d8814e560d88/nltk/corpus/reader/childes.py#L319) needs to be de-indented to be outside the else statement, at least for that tagging issue.

**Comment by kmike** [comment]
@pfeyz thanks. Your suggestion didn't fix all issues, but it makes sense. The code is still broken when relation=True:

```
======================================================================
FAIL: Doctest: childes.doctest
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 2201, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for childes.doctest
  File "/Users/kmike/svn/nltk/nltk/test/childes.doctest", line 0

----------------------------------------------------------------------
File "/Users/kmike/svn/nltk/nltk/test/childes.doctest", line 130, in childes.doctest
Failed example:
    valian.words('Valian/01a.xml',relation=True)[:10]
Expected:
    [[('at', 'prep', '1|0|ROOT'), ('Parent', 'n', '2|5|VOC'), ('Lastname', 'n', '3|5|MOD'), ('s', 'poss', '4|5|MOD'), ('house', 'n', '5|1|POBJ'), ('with', 'prep', '6|1|JCT'), ('Child', 'n', '7|8|NAME'), ('Lastname', 'n', '8|6|POBJ'), ('and', 'coord', '9|8|COORD'), ('it', 'pro', '10|11|SUBJ'), ('be-3S', 'v', '11|9|COMP'), ('March', 'n', '12|11|PRED'), ('fourth', 'adj', '13|12|MOD'), ('I', 'pro', '15|16|SUBJ'), ('believe', 'v', '16|14|ROOT'), ('and', 'coord', '18|17|ROOT'), ('when', 'adv', '19|20|PRED'), ('be-PAST', 'v', '20|18|COMP'), ('Parent', 'n', '21|23|MOD'), ('s', 'poss', '22|23|MOD'), ('birth', 'n', '23|20|SUBJ')], [('Child', 'n', '1|2|MOD'), ('s', 'poss', '2|0|ROOT')], [('oh', 'co', '1|4|COM'), ('I', 'pro', '3|4|SUBJ'), ('be', 'v', '4|0|ROOT'), ('sorry', 'adj', '5|4|PRED')], [('that', 'pro', '1|2|SUBJ'), ('be', 'v', '2|0|ROOT'), ('okay', 'adj', '3|2|PRED')], [('February', 'n', '1|6|VOC'), ('first', 'adj', '2|6|ENUM'), ('nineteen', 'det', '4|6|ENUM'), ('eighty', 'det', '5|6|ENUM'), ('four', 'det', '6|0|ROOT')], [('great', 'adj', '1|0|ROOT')], [('and', 'coord', '1|0|ROOT'), ('she', 'pro', '2|1|ROOT'), ('be', 'aux', '3|5|AUX'), ('two', 'det', '4|5|QUANT'), ('year-PL', 'n', '5|2|ROOT'), ('old', 'adj', '6|5|MOD')], [('correct', 'adj', '1|0|ROOT')], [('okay', 'co', '1|0|ROOT')], [('she', 'pro', '1|0|ROOT'), ('just', 'adv', '2|3|JCT'), ('turn-PERF', 'part', '3|1|XCOMP'), ('two', 'det', '4|6|QUANT'), ('a', 'det', '5|6|DET'), ('month', 'n', '6|3|OBJ'), ('ago', 'adv', '7|3|JCT')]]
Got:
    [[('at', 'prep', '1|0|ROOT'), ('Parent', 'n:prop', '2|5|VOC'), ('Lastname', 'n:prop', '3|5|MOD'), 's', ('house', 'n', '5|1|POBJ'), ('with', 'prep', '6|1|JCT'), ('Child', 'n:prop', '7|8|NAME'), ('Lastname', 'n:prop', '8|6|POBJ'), ('and', 'coord', '9|8|COORD'), ('it', 'pro', '10|11|SUBJ'), ('be-3S', 'v:cop', '11|9|COMP'), ('March', 'n:prop', '12|11|PRED'), ('fourth', 'adj', '13|12|MOD'), ('I', 'pro:sub', '15|16|SUBJ'), ('believe', 'v', '16|14|ROOT'), ('and', 'coord', '18|17|ROOT'), ('when', 'adv:wh', '19|20|PRED'), ('be-PAST', 'v:cop', '20|18|COMP'), ('Parent', 'n:prop', '21|23|MOD'), 's', ('birth', 'n', '23|20|SUBJ')], [('Child', 'n:prop', '1|2|MOD'), 's'], [('oh', 'co', '1|4|COM'), ('I', 'pro:sub', '3|4|SUBJ'), ('b', 'e', '4|0|ROOT'), ('sorry', 'adj', '5|4|PRED')], [('that', 'pro:dem', '1|2|SUBJ'), ('b', 'e', '2|0|ROOT'), ('okay', 'adj', '3|2|PRED')], [('February', 'n:prop', '1|6|VOC'), ('first', 'adj', '2|6|ENUM'), ('nineteen', 'det:num', '4|6|ENUM'), ('eighty', 'det:num', '5|6|ENUM'), ('four', 'det:num', '6|0|ROOT')], [('great', 'adj', '1|0|ROOT')], [('and', 'coord', '1|0|ROOT'), ('she', 'pro:sub', '2|1|ROOT'), ('b', 'e', '3|5|AUX'), ('two', 'det:num', '4|5|QUANT'), ('year-PL', 'n', '5|2|ROOT'), ('old', 'adj', '6|5|MOD')], [('correct', 'adj', '1|0|ROOT')], [('okay', 'co', '1|0|ROOT')], [('she', 'pro:sub', '1|0|ROOT'), ('just', 'adv:int', '2|3|JCT'), ('turn-PERF', 'part', '3|1|XCOMP'), ('two', 'det:num', '4|6|QUANT'), ('a', 'det', '5|6|DET'), ('month', 'n', '6|3|OBJ'), ('ago', 'adv', '7|3|JCT')]]
----------------------------------------------------------------------
File "/Users/kmike/svn/nltk/nltk/test/childes.doctest", line 146, in childes.doctest
Failed example:
    valian.MLU()
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 1289, in __run
        compileflags, 1) in test.globs
      File "<doctest childes.doctest[26]>", line 1, in <module>
        valian.MLU()
      File "/Users/kmike/svn/nltk/nltk/corpus/reader/childes.py", line 220, in MLU
        for fileid in self.abspaths(fileids)]
      File "/Users/kmike/svn/nltk/nltk/corpus/reader/childes.py", line 230, in _getMLU
        posList = [pos for (word,pos) in sent]
    ValueError: need more than 1 value to unpack
----------------------------------------------------------------------
File "/Users/kmike/svn/nltk/nltk/test/childes.doctest", line 153, in childes.doctest
Failed example:
    valian.MLU('Valian/01a.xml')
Exception raised:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 1289, in __run
        compileflags, 1) in test.globs
      File "<doctest childes.doctest[27]>", line 1, in <module>
        valian.MLU('Valian/01a.xml')
      File "/Users/kmike/svn/nltk/nltk/corpus/reader/childes.py", line 220, in MLU
        for fileid in self.abspaths(fileids)]
      File "/Users/kmike/svn/nltk/nltk/corpus/reader/childes.py", line 230, in _getMLU
        posList = [pos for (word,pos) in sent]
    ValueError: need more than 1 value to unpack


----------------------------------------------------------------------
Ran 1 test in 13.264s

FAILED (failures=1)
```

**Comment by alvations** [comment]
3+ years on... Childes doctest works on latest NLTK build https://nltk.ci.cloudbees.com/job/nltk/
