### ISSUE TITLE
Using POS & Python3

### ISSUE THREAD

**Issue by adonoho** [nltk/nltk#477]
Per your request:

I have pulled the master which included the patch for issue #470.

On my Mac running Python 3.3.2, I issued the command: 

```
sudo python3 setup.py install
```

Per your recommendation, I then issued the command:

```
sudo python3 -m nltk.downloader maxent_treebank_pos_tagger
```

and produced the following trace:

```
astraeus:nltk awd$ sudo python3 -m nltk.downloader maxent_treebank_pos_tagger
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/runpy.py", line 140, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/runpy.py", line 102, in _get_module_details
    loader = get_loader(mod_name)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/pkgutil.py", line 482, in get_loader
    return find_loader(fullname)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/pkgutil.py", line 499, in find_loader
    pkg = importlib.import_module(pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1586, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1567, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1534, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 586, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1024, in load_module
  File "<frozen importlib._bootstrap>", line 1005, in load_module
  File "<frozen importlib._bootstrap>", line 562, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 870, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "./nltk/__init__.py", line 116, in <module>
    from . import ccg
  File "./nltk/ccg/__init__.py", line 21, in <module>
    from nltk.ccg.chart import CCGEdge, CCGLeafEdge, CCGChartParser, CCGChart
  File "./nltk/ccg/chart.py", line 34, in <module>
    from nltk.parse import ParserI
  File "./nltk/parse/__init__.py", line 68, in <module>
    from nltk.parse.util import load_parser, TestGrammar, extract_test_sentences
  File "./nltk/parse/util.py", line 16, in <module>
    from nltk.data import load
  File "./nltk/data.py", line 266, in <module>
    class FileSystemPathPointer(PathPointer,compat.text_type):
  File "./nltk/data.py", line 271, in FileSystemPathPointer
    @py3_data
NameError: name 'py3_data' is not defined
```

I also issued the following command: 

```
sudo python3 -m nltk.downloader -d /usr/share/nltk_data all
```

with a similar result to the prior command.

As always, I'm happy to try another incantation.

Anon,
Andrew

**Comment by adonoho** [comment]
Using the latest pull, which defines `py3_data`, fixes the problem.

Anon,
Andrew

**Comment by stevenbird** [comment]
Thanks @adonoho -- sorry for the broken code.
