### ISSUE TITLE
Encoding issues in FrameNet corpus reader

### ISSUE THREAD

**Issue by nschneid** [nltk/nltk#486]
``` python
>>> fn.frame('Imposing_obligation')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nltk/compat.py", line 294, in wrapper
    return method(self).encode('ascii', 'backslash replace')
  File "nltk/corpus/reader/framenet.py", line 314, in __str__
    outstr = _pretty_frame(self)
  File "nltk/corpus/reader/framenet.py", line 227, in _pretty_frame
    outstr += _pretty_longstring(frame.definition, '  ') + '\n'
  File "nltk/corpus/reader/framenet.py", line 40, in _pretty_longstring
    outstr += "{0}{1}\n".format(prefix, line)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 26: ordinal not in range(128)
```

@wooters, any idea how to fix this? Is the XML decoded to Unicode, or read as raw strings?

**Comment by wooters** [comment]
This was a problem with the _pretty_longstring() method. I have fixed it and will submit a pull request.

**Comment by wooters** [comment]
Oops. Looks like this is a bigger issue - the xml file specifies "UTF-8" encoding, but it doesn't appear to be decoding the "definition" correctly...

**Comment by nschneid** [comment]
@wooters, can you confirm that with the changes in #485, Python 3 displays the accented í both with and without `print()`?:

``` python
>>> fn.frame('Imposing_obligation')
>>> print(fn.frame('Imposing_obligation'))
```
