### ISSUE TITLE
py3_data decorator fails in Python 3.3 for zip file pointers

### ISSUE THREAD

**Issue by kmike** [nltk/nltk#489]
Many tests starts to fail in Python 3.3, e.g.

```
File "/Users/kmike/svn/nltk/nltk/test/propbank.doctest", line 175, in propbank.doctest
Failed example:
    propbank.verbs()
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python3/3.3.2/Frameworks/Python.framework/Versions/3.3/lib/python3.3/doctest.py", line 1287, in __run
        compileflags, 1), test.globs)
      File "<doctest propbank.doctest[41]>", line 1, in <module>
        propbank.verbs()
      File "/Users/kmike/svn/nltk/nltk/corpus/reader/propbank.py", line 140, in verbs
        return StreamBackedCorpusView(self.abspath(self._verbsfile),
      File "/Users/kmike/svn/nltk/nltk/corpus/reader/api.py", line 144, in abspath
        return self._root.join(fileid)
      File "/Users/kmike/svn/nltk/nltk/data.py", line 500, in join
        return ZipFilePathPointer(self._zipfile, entry)
      File "/Users/kmike/svn/nltk/nltk/compat.py", line 180, in _decorator
        if item in path:
    TypeError: argument of type 'OpenOnDemandZipFile' is not iterable
```

**Comment by robwahl** [comment]
I've added the following code to docrunner.py in a patch to test zipfile.is_zipfile(filename) and then
def unzip(path):
    """

```
:param path:
"""
zfile = zipfile.ZipFile(path)
for name in zfile.namelist():
    (dirname, filename) = os.path.split(name)
    if filename == '':
        # directory
        if not os.path.exists(dirname):
            os.mkdir(dirname)
    else:
        # file
        fd = open(name, 'w')
        fd.write(zfile.read(name))
        fd.close()
zfile.close()
```

Hopefully this helps

**Comment by stevenbird** [comment]
I'm also seeing this failure with Python 3.2.
@robwahl sorry I'm not sure what you're suggesting here.

**Comment by stevenbird** [comment]
Resolved in https://github.com/nltk/nltk/commit/25c72c0e34db96194951c2430d95fa977c86b328
