### ISSUE TITLE
nltk.internals.compile_regexp_to_noncapturing doctest is broken

### ISSUE THREAD

**Issue by kmike** [nltk/nltk#578]
In Python 2.7:

```
======================================================================
FAIL: Doctest: nltk.internals.compile_regexp_to_noncapturing
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 2201, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for nltk.internals.compile_regexp_to_noncapturing
  File "/Users/kmike/svn/nltk/nltk/__init__.py", line 38, in compile_regexp_to_noncapturing

----------------------------------------------------------------------
File "/Users/kmike/svn/nltk/nltk/__init__.py", line 44, in nltk.internals.compile_regexp_to_noncapturing
Failed example:
    compile_regexp_to_noncapturing('ab(c(x+)(z*))?d')
Expected:
    'ab(?:c(?:x+)(?:z*))?d'
Got:
    <_sre.SRE_Pattern object at 0x7fa09e70b2e0>
```

**Comment by stevenbird** [comment]
Thanks for picking this up @kmike.
