### ISSUE TITLE
nltk.test.unit.test_collocations is broken

### ISSUE THREAD

**Issue by kmike** [nltk/nltk#581]
Using Python 2.7:

```
======================================================================
FAIL: nltk.test.unit.test_collocations.test_bigram2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kmike/svn/nltk/.tox/py27-nodeps/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/kmike/svn/nltk/nltk/test/unit/test_collocations.py", line 29, in test_bigram2
    [(('a', 'a'), 1), (('a', 'test'), 1), (('is', 'a'), 1), (('is', 'is'), 1), (('test', 'test'), 1), (('this', 'is'), 1), (('this', 'this'), 1)]
AssertionError

======================================================================
FAIL: nltk.test.unit.test_collocations.test_bigram3
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kmike/svn/nltk/.tox/py27-nodeps/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/kmike/svn/nltk/nltk/test/unit/test_collocations.py", line 43, in test_bigram3
    [(('a', 'test'), 3), (('is', 'a'), 3), (('this', 'is'), 3), (('a', 'a'), 1), (('is', 'is'), 1), (('test', 'test'), 1), (('this', 'this'), 1)]
AssertionError

======================================================================
FAIL: nltk.test.unit.test_collocations.test_bigram5
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kmike/svn/nltk/.tox/py27-nodeps/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/kmike/svn/nltk/nltk/test/unit/test_collocations.py", line 57, in test_bigram5
    [(('a', 'test'), 4), (('is', 'a'), 4), (('this', 'is'), 4), (('is', 'test'), 3), (('this', 'a'), 3), (('a', 'a'), 1), (('is', 'is'), 1), (('test', 'test'), 1), (('this', 'this'), 1)]
AssertionError
```

**Comment by jnothman** [comment]
Oh! Any idea when this began to fail? It was only introduced recently, in
#414.

Also, that's not a very useful error message. Can I propose that we use
things like nose or unittest's assert_equal to get better output upon
failure?

**Comment by kmike** [comment]
No ideas, I've been away from active NLTK development recently. Error messages: +1.

It looks like an ordering issue; this passes:

```
assert set(b.ngram_fd.items()) == \
    set([(('a', 'a'), 1), (('a', 'test'), 1), (('is', 'a'), 1), (('is', 'is'), 1), (('test', 'test'), 1), (('this', 'is'), 1), (('this', 'this'), 1)])
```

**Comment by jnothman** [comment]
surprising that we never explicitly sorted it in the first place.

**Comment by kmike** [comment]
It seems you've got it: FreqDist was reimplemented using collections.Counter, and keys/items became unsorted - see https://github.com/nltk/nltk/commit/514ee4996f555fd152874fa6ee9db8167168d155.

**Comment by jnothman** [comment]
So one way we could make this work is to use `most_common` instead of
`items`?

**Comment by kmike** [comment]
I also thought so, but no, most_common would sort items based on values, while old sorting was based on keys and values. Using "sorted" should fix it.
