### ISSUE TITLE
nltk.data.load: relative paths don't work anymore

### ISSUE THREAD

**Issue by heatherleaf** [nltk/nltk#594]
I just noted that I can't load a grammar in my current directory:

```
>>> g = nltk.data.load("file:grammar.fcfg", verbose=True)
<<Loading file:///grammar.fcfg>>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/peter/Projekt/NLTK/nltk/nltk/data.py", line 768, in load
    opened_resource = _open(resource_url)
  File "/Users/peter/Projekt/NLTK/nltk/nltk/data.py", line 876, in _open
    return find(_path, ['']).open()
  File "/Users/peter/Projekt/NLTK/nltk/nltk/data.py", line 615, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource u'/grammar.fcfg' not found.  Please use the NLTK
  Downloader to obtain the resource:  >>> nltk.download()
  Searched in:
    - u''
**********************************************************************
```

The same thing happens if I try `"file:./grammar.fcfg"`. It did use to work, and I think it changed somewhere around here: 03c3b1ea287a3fbe01ced1fce0b8ff9ee0ac7acb, a25c7335ffd08401f3a5c7637ff1e74ebafc54d5

Is this a desired behaviour? For me, it's not.

**Comment by stevenxxiu** [comment]
@heatherleaf I've tried to fix this, does this work for you now?

**Comment by heatherleaf** [comment]
Sorry, I missed your fix before. Yes, it seems to work fine now, thanks!
