### ISSUE TITLE
finder.nbest(trigram_measures.likelihood_ratio raises ValueError: math domain error in python 3.2

### ISSUE THREAD

**Issue by helmanofer** [nltk/nltk#610]
Tested in python 2.7.2 and it worked
the code:

```
trigram_measures = nltk.collocations.TrigramAssocMeasures()
finder = TrigramCollocationFinder.from_words(words)
ignored_words = nltk.corpus.stopwords.words('english')
finder.apply_word_filter(lambda w: len(w) < 3 or w.lower() in ignored_words)
finder.apply_freq_filter(10)
print(finder.nbest(trigram_measures.likelihood_ratio, 10))

Traceback (most recent call last):
  File "D:/SourceCode/topic-extraction-python/snadbox/sand_box.py", line 45, in <module>
    print(finder.nbest(trigram_measures.likelihood_ratio, 10))
  File "C:\Python32\lib\site-packages\nltk\collocations.py", line 115, in nbest
    return [p for p,s in self.score_ngrams(score_fn)[:n]]
  File "C:\Python32\lib\site-packages\nltk\collocations.py", line 111, in score_ngrams
    key=_itemgetter(1), reverse=True)
  File "C:\Python32\lib\site-packages\nltk\collocations.py", line 102, in _score_ngrams
    score = self.score_ngram(score_fn, *tup)
  File "C:\Python32\lib\site-packages\nltk\collocations.py", line 235, in score_ngram
    n_all)
  File "C:\Python32\lib\site-packages\nltk\metrics\association.py", line 134, in likelihood_ratio
    for obs, exp in zip(cont, cls._expected_values(cont))))
  File "C:\Python32\lib\site-packages\nltk\metrics\association.py", line 134, in <genexpr>
    for obs, exp in zip(cont, cls._expected_values(cont))))
ValueError: math domain error
```

**Comment by stevenbird** [comment]
I get the same error in Python 2.6.9.

**Comment by jnothman** [comment]
I'll try to take a look at this soon...

**Comment by jnothman** [comment]
For reference, a more minimal and complete example:

``` python
from nltk.collocations import *
from nltk.metrics.association import *
from nltk.corpus import brown
finder = TrigramCollocationFinder.from_words(brown.words()[:2000])
finder.nbest(TrigramAssocMeasures.likelihood_ratio, 1)
```

**Comment by helmanofer** [comment]
Seems like it's fixed, thanks a lot
Do you want me to close the bug?

**Comment by stevenbird** [comment]
Resolved in https://github.com/nltk/nltk/commit/7a6369dcc6a1d5f332ffa2457f2692e16ab2381f
