### ISSUE TITLE
OS X: downloader GUI crashes in Python 3 when mouse wheel is used for scrolling

### ISSUE THREAD

**Issue by kmike** [nltk/nltk#696]
I have no idea why is it happening, but when a mouse wheel is used for scrolling the downloader GUI crashes. Keyboard works fine. For Python 3.3 from python.org the exception is the following:

```
python -m nltk.downloader
showing info http://nltk.github.com/nltk_data/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/runpy.py", line 160, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/runpy.py", line 73, in _run_code
    exec(code, run_globals)
  File "./nltk/downloader.py", line 2263, in <module>
    halt_on_error=options.halt_on_error)
  File "./nltk/downloader.py", line 656, in download
    self._interactive_download()
  File "./nltk/downloader.py", line 968, in _interactive_download
    DownloaderGUI(self).mainloop()
  File "./nltk/downloader.py", line 1703, in mainloop
    self.top.mainloop(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/tkinter/__init__.py", line 1071, in mainloop
    self.tk.mainloop(n)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 0: invalid start byte
```

For Python 3.4 from homebrew the exception is the same.

**Comment by naoyak** [comment]
Looks like this is a Tk issue, solvable by upgrading ActiveTcl:
http://stackoverflow.com/questions/16995969/inertial-scrolling-in-mac-os-x-with-tkinter-and-python
http://bugs.python.org/issue10731
https://sourceforge.net/p/tktoolkit/bugs/2966/
