### ISSUE TITLE
Toolbox character encoding problem

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#717]
```
from nltk import data
from nltk.toolbox import ToolboxData

grammar = r"""
lexfunc: {<lf>(<lv><ln|le>*)*}
"""

db = ToolboxData()
db.open(data.find('corpora/toolbox/iu_mien_samp.db'))
lexicon = db.parse(grammar, encoding='utf8')
```

This program from chapter 11 of the NLTK book produces the following error:

```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    lexicon = db.parse(grammar, encoding='utf8')
...
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/re.py", line 156, in match
    return _compile(pattern, flags).match(string)
TypeError: can't use a string pattern on a bytes-like object
```

**Comment by stevenbird** [comment]
This will be left unresolved for the NLTK 3.0 final release.
