### ISSUE TITLE
SpanishStemmer raises IndexError on 'algue'

### ISSUE THREAD

**Issue by tobami** [nltk/nltk#759]
"algue" is the only word it happens out of many tens of thousands I went through.

To reproduce:

``` python
from nltk.stem.snowball import SpanishStemmer
stemmer = SpanishStemmer()
stemmer.stem('algue')
```

``` python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/local/lib/python2.7/site-packages/nltk/stem/snowball.py", line 3555, in stem
    if word[-2:] == u"gu" and rv[-1] == u"u":
IndexError: string index out of range
```

Happens both with nltk 2.0.4 and 3.0.0

**Comment by jnothman** [comment]
To be IndexError-safe, that should be rv[-1:] not rv[-1]. You can submit a
PR...

**Comment by tobami** [comment]
OK, I'll do that now
