### ISSUE TITLE
Cannot import NLTK

### ISSUE THREAD

**Issue by progval** [nltk/nltk#797]
After a Python 3.4 upgrade:

```
ppp@Hydrogen:~$ python3
Python 3.4.2 (default, Nov 13 2014, 07:01:52) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ppp/.local/lib/python3.4/site-packages/nltk/__init__.py", line 117, in <module>
    from nltk.align import *
  File "/home/ppp/.local/lib/python3.4/site-packages/nltk/align/__init__.py", line 15, in <module>
    from nltk.align.ibm1 import IBMModel1
  File "/home/ppp/.local/lib/python3.4/site-packages/nltk/align/ibm1.py", line 18, in <module>
    from nltk.corpus import comtrans
  File "/home/ppp/.local/lib/python3.4/site-packages/nltk/corpus/__init__.py", line 64, in <module>
    from nltk.tokenize import RegexpTokenizer
  File "/home/ppp/.local/lib/python3.4/site-packages/nltk/tokenize/__init__.py", line 65, in <module>
    from nltk.tokenize.regexp   import (RegexpTokenizer, WhitespaceTokenizer,
  File "/home/ppp/.local/lib/python3.4/site-packages/nltk/tokenize/regexp.py", line 201, in <module>
    blankline_tokenize = BlanklineTokenizer().tokenize
  File "/home/ppp/.local/lib/python3.4/site-packages/nltk/tokenize/regexp.py", line 172, in __init__
    RegexpTokenizer.__init__(self, r'\s*\n\s*\n\s*', gaps=True)
  File "/home/ppp/.local/lib/python3.4/site-packages/nltk/tokenize/regexp.py", line 119, in __init__
    self._regexp = compile_regexp_to_noncapturing(pattern, flags)
  File "/home/ppp/.local/lib/python3.4/site-packages/nltk/internals.py", line 54, in compile_regexp_to_noncapturing
    return sre_compile.compile(convert_regexp_to_noncapturing_parsed(sre_parse.parse(pattern)), flags=flags)
  File "/home/ppp/.local/lib/python3.4/site-packages/nltk/internals.py", line 50, in convert_regexp_to_noncapturing_parsed
    parsed_pattern.pattern.groups = 1
AttributeError: can't set attribute
```

**Comment by progval** [comment]
Should I report this to Debian? It happened after upgrading from 3.4.2-1 to 3.4.2-2.

**Comment by stevenbird** [comment]
@ProgVal can you please help narrow this down? E.g. try to import `internals.py` on its own? Or better still, identify something problematic within `internals.py`?

**Comment by progval** [comment]
I added some print statements to  `compile_regexp_to_noncapturing`:

```
def compile_regexp_to_noncapturing(pattern, flags=0):
    """
    Compile the regexp pattern after switching all grouping parentheses
    in the given regexp pattern to non-capturing groups.

    :type pattern: str
    :rtype: str
    """
    def convert_regexp_to_noncapturing_parsed(parsed_pattern):
        res_data = []
        for key, value in parsed_pattern.data:
            if key == sre_constants.SUBPATTERN:
                index, subpattern = value
                value = (None, convert_regexp_to_noncapturing_parsed(subpattern))
            elif key == sre_constants.GROUPREF:
                raise ValueError('Regular expressions with back-references are not supported: {0}'.format(pattern))
            res_data.append((key, value))
        parsed_pattern.data = res_data
        print(repr(parsed_pattern))
        print(repr(parsed_pattern.pattern))
        print(repr(parsed_pattern.pattern.groups))
        parsed_pattern.pattern.groups = 1
        parsed_pattern.pattern.groupdict = {}
        return parsed_pattern

    print(repr(pattern))
    print(repr(sre_parse.parse(pattern)))
    return sre_compile.compile(convert_regexp_to_noncapturing_parsed(sre_parse.parse(pattern)), flags=flags)
```

Here is the output I get:

```
ppp@Hydrogen:~/.local/lib/python3.4/site-packages$ python3
Python 3.4.2 (default, Nov 13 2014, 07:01:52) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
'\\s*\\n\\s*\\n\\s*'
[('max_repeat', (0, 4294967295, [('in', [('category', 'category_space')])])), ('literal', 10), ('max_repeat', (0, 4294967295, [('in', [('category', 'category_space')])])), ('literal', 10), ('max_repeat', (0, 4294967295, [('in', [('category', 'category_space')])]))]
[('max_repeat', (0, 4294967295, [('in', [('category', 'category_space')])])), ('literal', 10), ('max_repeat', (0, 4294967295, [('in', [('category', 'category_space')])])), ('literal', 10), ('max_repeat', (0, 4294967295, [('in', [('category', 'category_space')])]))]
<sre_parse.Pattern object at 0x7ffda2c69550>
1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ppp/.local/lib/python3.4/site-packages/nltk/__init__.py", line 117, in <module>
    from nltk.align import *
[…]
```

It looks like on this specific Python version, `sre_parse.Pattern.groups` is a read-only property.

**Comment by progval** [comment]
Confirmed:

```
class Pattern:
    # master pattern object.  keeps track of global attributes
    def __init__(self):
        self.flags = 0
        self.groupdict = {}
        self.subpatterns = [None]  # group 0
    @property
    def groups(self):
        return len(self.subpatterns)
    def opengroup(self, name=None):
        gid = self.groups
        self.subpatterns.append(None)
        if name is not None:
            ogid = self.groupdict.get(name, None)
            if ogid is not None:
                raise error("redefinition of group name %s as group %d; "
                            "was group %d" % (repr(name), gid,  ogid))
            self.groupdict[name] = gid
        return gid
    def closegroup(self, gid, p):
        self.subpatterns[gid] = p
    def checkgroup(self, gid):
        return gid < self.groups and self.subpatterns[gid] is not None
```

(code from /usr/lib/python3.4/sre_parse.py)

**Comment by progval** [comment]
The issue seems to be fixed in 3.4.2-3. The code of sre_parse in this version is the same as in 3.4.2-1:

```
class Pattern:
    # master pattern object.  keeps track of global attributes
    def __init__(self):
        self.flags = 0
        self.open = []
        self.groups = 1
        self.groupdict = {}
    def opengroup(self, name=None):
        gid = self.groups
        self.groups = gid + 1
        if name is not None:
            ogid = self.groupdict.get(name, None)
            if ogid is not None:
                raise error("redefinition of group name %s as group %d; "
                            "was group %d" % (repr(name), gid,  ogid))
            self.groupdict[name] = gid
        self.open.append(gid)
        return gid
    def closegroup(self, gid):
        self.open.remove(gid)
    def checkgroup(self, gid):
        return gid < self.groups and gid not in self.open
```

Maybe Debian undid its change, but I can't find it in the [changelog](http://metadata.ftp-master.debian.org/changelogs//main/p/python3.4/python3.4_3.4.2-3_changelog)

**Comment by stevenbird** [comment]
Thanks for the analysis, @ProgVal. I guess it is not surprising that directly setting `groups` is a slightly risky thing to do. I take it that this was only an issue in 3.4.2-2, so will not try to fix it.

**Comment by ssbb** [comment]
Got in on 3.5.0

**Comment by AnilRedshift** [comment]
This repros again on `python 3.5.0`
@stevenbird, would you like me to open a new issue on this, or reactivate this one?
File "/server/utils/cache.py", line 3, in <module>
    from nltk.tokenize import sent_tokenize
  File "/opt/envs/worker/lib/python3.5/site-packages/nltk/__init__.py", line 117, in <module>
    from nltk.align import *
  File "/opt/envs/worker/lib/python3.5/site-packages/nltk/align/__init__.py", line 15, in <module>
    from nltk.align.ibm1 import IBMModel1
  File "/opt/envs/worker/lib/python3.5/site-packages/nltk/align/ibm1.py", line 18, in <module>
    from nltk.corpus import comtrans
  File "/opt/envs/worker/lib/python3.5/site-packages/nltk/corpus/__init__.py", line 64, in <module>
    from nltk.tokenize import RegexpTokenizer
  File "/opt/envs/worker/lib/python3.5/site-packages/nltk/tokenize/__init__.py", line 65, in <module>
    from nltk.tokenize.regexp   import (RegexpTokenizer, WhitespaceTokenizer,
  File "/opt/envs/worker/lib/python3.5/site-packages/nltk/tokenize/regexp.py", line 201, in <module>
    blankline_tokenize = BlanklineTokenizer().tokenize
  File "/opt/envs/worker/lib/python3.5/site-packages/nltk/tokenize/regexp.py", line 172, in __init__
    RegexpTokenizer.__init__(self, r'\s*\n\s*\n\s*', gaps=True)
  File "/opt/envs/worker/lib/python3.5/site-packages/nltk/tokenize/regexp.py", line 119, in __init__
    self._regexp = compile_regexp_to_noncapturing(pattern, flags)
  File "/opt/envs/worker/lib/python3.5/site-packages/nltk/internals.py", line 54, in compile_regexp_to_noncapturing
    return sre_compile.compile(convert_regexp_to_noncapturing_parsed(sre_parse.parse(pattern)), flags=flags)
  File "/opt/envs/worker/lib/python3.5/site-packages/nltk/internals.py", line 50, in convert_regexp_to_noncapturing_parsed
    parsed_pattern.pattern.groups = 1

**Comment by AnilRedshift** [comment]
The 3.5.0 source has group set via a property. An ideal fix here would not muck around with the guts of the pattern object. I will take a quick look.
```
   self.subpatterns = [None]  # group 0
        self.lookbehindgroups = None
    @property
    def groups(self):
        return len(self.subpatterns)
```

**Comment by intentionally-left-nil** [comment]
Sorry, I see this is referenced in https://github.com/nltk/nltk/issues/1106 for python 3.5
