### ISSUE TITLE
nltk.download gives an HTTP 301

### ISSUE THREAD

**Issue by westhomas** [nltk/nltk#812]
I installed nltk and i typed the following commands
 import nltk   nltk.download() 

The dialog comes up but the stack immediately outputs at 301:

BadStatusLine: HTTP/1.1 301Moved Permanently

Here's the stack:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1470, in **call**
    return self.func(_args)
  File "/Users/wes/.virtualenvs/liberty/lib/python2.7/site-packages/nltk/downloader.py", line 1433, in _info_save
    callback(entry.get())
  File "/Users/wes/.virtualenvs/liberty/lib/python2.7/site-packages/nltk/downloader.py", line 1449, in _set_url
    self._ds.url = url
  File "/Users/wes/.virtualenvs/liberty/lib/python2.7/site-packages/nltk/downloader.py", line 903, in _set_url
    self._update_index(url)
  File "/Users/wes/.virtualenvs/liberty/lib/python2.7/site-packages/nltk/downloader.py", line 826, in _update_index
    ElementTree.parse(compat.urlopen(self._url)).getroot())
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(_args)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 399, in _read_status
    raise BadStatusLine(line)
BadStatusLine: HTTP/1.1 301Moved Permanently

**Comment by westhomas** [comment]
https://github.com/nltk/nltk/blob/develop/nltk/downloader.py#L380

This line should be: 

`DEFAULT_URL = 'http://www.nltk.org/nltk_data/'`

**Comment by westhomas** [comment]
Seems downloader.py cannot follow 301s. There are more in the XML file: http://www.nltk.org/nltk_data/index.xml.

**Comment by stevenbird** [comment]
@edgecaselabs – thanks for reporting this problem.

**Comment by westhomas** [comment]
You bet. However that commit won't solve the problem completely as the downloader still fails on the individual packages which also contain 301s:

```
$ curl http://nltk.github.com/nltk_data/packages/chunkers/maxent_ne_chunker.zip
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by stevenbird** [comment]
Oh, right. The problem is here:

```
BASEURL = http://nltk.github.com/nltk_data/packages
```

Line 2 of https://github.com/nltk/nltk_data/blob/gh-pages/Makefile
