### ISSUE TITLE
Bug in DependencyGraph._tree

### ISSUE THREAD

**Issue by stevenbird** [nltk/nltk#851]
Running the dependencygraph doctests produces an error, probably due to recent changes in `DependencyGraph`. It shows up in https://github.com/nltk/nltk/blob/develop/nltk/parse/dependencygraph.py#L265

@dimazest – would you be able to look at this please?

```
Traceback (most recent call last):
  File "dependencygraph.py", line 627, in <module>
    demo()
  File "dependencygraph.py", line 421, in demo
    malt_demo()
  File "dependencygraph.py", line 451, in malt_demo
    tree = dg.tree()
  File "dependencygraph.py", line 281, in tree
    return Tree(word, [self._tree(i) for i in deps])
  File "dependencygraph.py", line 281, in <listcomp>
    return Tree(word, [self._tree(i) for i in deps])
  File "dependencygraph.py", line 265, in _tree
    word = node['word']
KeyError: 'word'
```

**Comment by stevenbird** [comment]
There's a related problem for the non-projective dependency parser:

```
Traceback (most recent call last):
  File "nonprojectivedependencyparser.py", line 766, in <module>
    demo()
  File "nonprojectivedependencyparser.py", line 724, in demo
    nonprojective_conll_parse_demo()
  File "nonprojectivedependencyparser.py", line 743, in nonprojective_conll_parse_demo
    for parse_graph in npp.parse(['Cathy', 'zag', 'hen', 'zwaaien', '.'], ['N', 'V', 'Pron', 'Adj', 'N', 'Punc']):
  File "nonprojectivedependencyparser.py", line 465, in parse
    g_graph.connect_graph()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nltk-3.0.0-py3.4.egg/nltk/parse/dependencygraph.py", line 110, in connect_graph
    node1['deps'].append(node2['address'])
AttributeError: 'collections.defaultdict' object has no attribute 'append'
```

**Comment by dimazest** [comment]
I'll try to have a look by the end of the week.

**Comment by stevenbird** [comment]
Thanks. It's one of the few things to resolve before 3.0.2 can be released.

**Comment by stevenbird** [comment]
There's another downstream problem with the projective dependency parser:

```
  File "projectivedependencyparser.py", line 557, in <module>
    demo()
  File "projectivedependencyparser.py", line 468, in demo
    projective_rule_parse_demo()
  File "projectivedependencyparser.py", line 487, in projective_rule_parse_demo
    for tree in trees:
  File "projectivedependencyparser.py", line 195, in parse
    dg = DependencyGraph(conll_format)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/site-packages/nltk-3.0.0-py3.2.egg/nltk/parse/dependencygraph.py", line 71, in __init__
    cell_separator=cell_separator,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/site-packages/nltk-3.0.0-py3.2.egg/nltk/parse/dependencygraph.py", line 245, in _parse
    "The graph does'n contain a node "
nltk.parse.dependencygraph.DependencyGraphError: The graph does'n contain a node that depends on the root element.
```

This is holding up 3.0.2.

**Comment by stevenbird** [comment]
I just saw the PR. Thanks @dimazest – I hope that solves the problems.

**Comment by stevenbird** [comment]
Unfortunately there are still problems with our dependency parsers, which seem to have arisen after #822 was merged. @dimazest I'd be grateful if you would look into it some more please.

**Comment by dimazest** [comment]
right, i've noticed problems with `nltk.parse.nonprojectivedependencyparser.ProbabilisticNonprojectiveParser` but didn't see a clear solution right on spot. I'll have a look later this week.

**Comment by stevenbird** [comment]
@longdt219 would you please take a look at these problems soon? They're holding up 3.0.2. I'd rather not have to revert @dimazest's PR #822.

**Comment by longdt219** [comment]
yes I will @stevenbird

**Comment by stevenbird** [comment]
Thanks for #869 @longdt219

**Comment by stevenbird** [comment]
These issues have been resolved in #870 and #872.

**Comment by stevenbird** [comment]
We still seem to have a problem stemming from #822:

```
Traceback (most recent call last):
  File "/scratch/jenkins/python/python-2.6.9-x86_64/lib/python2.6/unittest.py", line 279, in run
    testMethod()
  File "/scratch/jenkins/workspace/nltk/TOXENV/py26-jenkins/jdk/oraclejdk8/nltk/test/unit/test_corpora.py", line 137, in test_parsed_sents
    '.'
  File "/scratch/jenkins/python/python-2.6.9-x86_64/lib/python2.6/unittest.py", line 350, in failUnlessEqual
    (msg or '%r != %r' % (first, second))
AssertionError: Tree('fortaleci\xf3', ['hoy', 'considerablemente', Tree('aumento', ['El', Tree('del', [Tree('\xedndice', [Tree('de', [Tree('desempleo', ['estadounidense'])])])])]), '.', Tree('al', [Tree('euro', [Tree('cotizaba', [',', 'que', Tree('a', ['0,9452_d\xf3lares']), Tree('a', [Tree('15.35', ['las', 'GMT'])]), Tree('en', [Tree('mercado', ['el', Tree('de', ['divisas']), Tree('de', ['Fr\xe1ncfort'])])]), Tree('frente_a', [',', Tree('0,9349_d\xf3lares', ['los', Tree('de', [Tree('ma\xf1ana', ['esta'])])])]), 'se'])])])]) != Tree('fortaleci\xf3', [Tree('aumento', ['El', Tree('del', [Tree('\xedndice', [Tree('de', [Tree('desempleo', ['estadounidense'])])])])]), 'hoy', 'considerablemente', Tree('al', [Tree('euro', [Tree('cotizaba', [',', 'que', Tree('a', [Tree('15.35', ['las', 'GMT'])]), 'se', Tree('en', [Tree('mercado', ['el', Tree('de', ['divisas']), Tree('de', ['Fr\xe1ncfort'])])]), Tree('a', ['0,9452_d\xf3lares']), Tree('frente_a', [',', Tree('0,9349_d\xf3lares', ['los', Tree('de', [Tree('ma\xf1ana', ['esta'])])])])])])]), '.'])
```

https://nltk.ci.cloudbees.com/job/nltk/TOXENV=py26-jenkins,jdk=oraclejdk8/lastCompletedBuild/testReport/nltk.test.unit.test_corpora/TestCoNLL2007/test_parsed_sents/

**Comment by stevenbird** [comment]
The dependencies doctest is also broken by this PR:

```
cd nltk/test
make dependency.errs
```

@dimazest this is blocking the 3.0.2 release

**Comment by dimazest** [comment]
I'll have a look as soon as I get to my laptop.
